### ISSUE TITLE
Problems deleting an already published annotation

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#1009]
I deleted the annotation for Outgrowers' program 10 hours ago for the below two contracts but it is still present on the front end for both of the contracts. 

http://www.openlandcontracts.org/contract/ocds-591adf-7497994880/view#/pdf
http://www.openlandcontracts.org/contract/ocds-591adf-7812180414/view#/pdf

http://resourcecontracts.elasticbeanstalk.com/contract/1133
http://resourcecontracts.elasticbeanstalk.com/contract/1134

**Comment by manishgs** [comment]
When i tried on new contract it was working. 

Could you please tell me which annotation, that you deleted, showing on frontend?

**Comment by manishgs** [comment]
Seems like you deleted the annotation but didn't publish it again.

There is an issue when you delete the annotation, annotation status doesn't changed to draft and can't republished the changes.

**Solution** 
Change the status to draft state whenever annotation deleted so that user can republish the changes.

@SamCCSI 
Let me know if this make sense to you.

**Comment by charlesyoung** [comment]
Thanks @manishgs. 

We should possibly, if this happens often, update the workflow to automatically change the annotation status to draft whenever annotations are deleted. 

cc @SamCCSI

**Comment by charlesyoung** [comment]
Liked to Update annotation workflow #1016
