### ISSUE TITLE
Separate comments for each metadata and annotation in the publishing workflow

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#101]
Sam suggested to have the separate commenting features for each metadata and individual annotation in the publishing workflow. Publishing workflow #75 doesn't currently allow separate commenting. This might still need further discussion and also think about the UI aspects before making changing in the system.

**Comment by anderspeders** [comment]
Yes, agree that this will need some further thought.

**Comment by byndcivilization** [comment]
This was brought up again in the review. Hope is for:
-commenting functionality (could be stored as an object array?) so that reviewers and annotators can have back and forth (priority)
-move to next annotation with comment function (blue sky)
-annotation diff so that reviewer can show correction for annotators future work (blue sky)

**Comment by SamCCSI** [comment]
Just checking - will this feature be included in the next sprint?

**Comment by anjesh** [comment]
userstory: As a reviewer, I need to be able to attach a comment on an annotation or metadata entry, so that the annotator / uploader who made the entry knows what I am referring to and can swiftly make the amendment needed.

**Comment by anjesh** [comment]
There will be comment popup for each annotation and for the metadata, that allows the users to comment/discuss on the particular annotation/metadata. There's a slight complication for the metadata which takes multiple values like company, government entity as these values could be removed by the user, which will also affect the comments that have been entered if any.

**Comment by anjesh** [comment]
This commenting feature is not way part of the publishing workflow - meaning this won't block the publishing of the metadata and annotation by the researchers. It's just for the info flow between the reviewer and annotator/uploader.

**Comment by SamCCSI** [comment]
Hi Anjesh, can you illustrate what you mean by 'pop-up'? I just want to make sure that the comment will be stable and present when reading or editing the annotation -- I had imagined this as a separate text box on the page, rather than a pop-up (but I could be convinced if there is a specific reason for having it as a pop up). Many thanks.

**Comment by anjesh** [comment]
The purpose of popup is to ensure that the user knows the page s/he is working on on the background. It's deployed now, do verify.

**Comment by SamCCSI** [comment]
Thanks Anjesh.

1. The functionality of the pop up while I am typing is fine, though I don't see the value-add compared to if it was a stable comment box next to the metadata / annotation entry, where the page and the comment would still both be visible. 

2. It is hard for the annotator to see my comment and amend their annotation or metadata entry at the same time. When I edit the text, the comment pop up is not visible. When the pop up is visible I cannot edit the text. This is why my mock up (https://github.com/NRGI/resourcecontracts.org/issues/566) suggested that the text of the comment needs to be visible to the person amending the annotation.

3. Lengthy annotations are not displayed in full while I write my comment, which makes it hard for me to write the comment without switching between multiple pages so that I can see the entire annotation. It would be less burdensome if I could expand the annotation so that all of the text is visible and then click on the comment button and type my comment with all of the annotation text in view.

![image](https://cloud.githubusercontent.com/assets/12913915/11514765/38603c18-9848-11e5-91a0-93682f88ceb5.png)

**Comment by anjesh** [comment]
> The functionality of the pop up while I am typing is fine, though I don't see the value-add compared to if it was a stable comment box next to the metadata / annotation entry, where the page and the comment would still both be visible.

> It is hard for the annotator to see my comment and amend their annotation or metadata entry at the same time. When I edit the text, the comment pop up is not visible. When the pop up is visible I cannot edit the text. This is why my mock up (#566) suggested that the text of the comment needs to be visible to the person amending the annotation.

Stable comment box means the page would get distorted as the comments might be long. There would be multiple comments. Perhaps we can have a mechanism when we click the box, we get the non-modal (meaning you can see the popup and type at the same time) view only comment in the contract edit mode, which needs to be closed manually. Something like there, from there you can add comment, which will open up the existing commenting box. Does that look ok to you?

![image](https://cloud.githubusercontent.com/assets/120488/11525945/1543410a-98ff-11e5-8118-843a6c7d0096.png)

> Lengthy annotations are not displayed in full while I write my comment, which makes it hard for me to write the comment without switching between multiple pages so that I can see the entire annotation. It would be less burdensome if I could expand the annotation so that all of the text is visible and then click on the comment button and type my comment with all of the annotation text in view.

Will fix this.

**Comment by SamCCSI** [comment]
Thank you very much @anjesh  

Your proposed solution sounds great to me.

Just checking: this would mean that: 
(1) I can open the comment box and type into the metadata / annotation entry while viewing the entire comment; and 
(2) I can open the comment box and type into the comment box while also viewing the entire metadata contract entry?

CC @KaitlinCCSI @jesseccsi

**Comment by anjesh** [comment]
We are thinking to update the UI so that the metadata could be viewed/edited and comments could be viewed/added at the same time. Clicking on the [Open] link on the right will open up the comment box under the metadata like this. Clicking on [Open] link again will close the box. Similarly you can click on other [open] link and view the comments for other metadata as well. 

![image](https://cloud.githubusercontent.com/assets/120488/11676120/82e67314-9e57-11e5-8983-6fda2e993bd3.png)

**Comment by anjesh** [comment]
The new commenting UI fix is done. Please check and re-open if any issue. 

![image](https://cloud.githubusercontent.com/assets/120488/12256965/2bb2a534-b92a-11e5-88de-086d885b0a1f.png)
