### ISSUE TITLE
Clipping button on search page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#1022]
Is it on purpose that we have not placed a clipping button on the search page?

![image](https://cloud.githubusercontent.com/assets/1101585/21278083/3ab78f6c-c3a7-11e6-9d06-4b45b4f0fb83.png)

**Comment by manishgs** [comment]
This issue will be addressed on issue #980

**Comment by jedm** [comment]
@anderspeders Yes, I believe that together the full group decided not to include Clipping on/off switch on Search results pages. Specifically, we decided that you can only turn on Clipping and select Clips from the Contract View/Summary pages because those are the only pages that display individual Annotations. A search results page displays a combination of full contracts and single annotations, which would be confusing for Clipping workflow. 

See instruction #6 in this comment https://github.com/NRGI/resourcecontracts.org/issues/893#issuecomment-223736128 - from June, 2016

(Further background: Originally the Clipping specifications I submitted recommended that full contracts OR single Annotations could be clipped, but it was decided before final Clipping specs were given to YI that Clipping would only be available from Contract View/Summary pages.) 

Final reminder: If Clipping is "ON," the "View Clips" button would display on all pages in upper-right, as also noted in June comments from #893 

So, my recommendation is that we revert to 2016 group decision (no enable-clipping button on Search pages) or we reopen that question as a group before giving final instruction to YI. What do others think? @KaitlinCCSI @anderspeders @charlesyoung

**Comment by anjesh** [comment]
We have shared this feature during demo as well, but we didn't get any feedback so thought this is part of the overall clipping improvement. We will hide this on search page for now till we hear back from the group on whether to re-enable this or not.

**Comment by KaitlinCCSI** [comment]
Agree with @jedm - let's please go with 2016 group decision of NOT enabling clipping button on Search pages. (If I'm remembering correctly, I think decision was partly b/c we decided that clipping was for annotations and not for saving full contracts, and all search results can be saved by just downloading the CSV files, so the clipping functionality didn't add much to this page.)

**Comment by KaitlinCCSI** [comment]
Sorry to reverse my stance so quickly, but have been persuaded that we might need to revisit this. Think we should take convo offline to quickly discuss whether it is possible to have clips on search results page that would allow clipping specific annotations searched? If not, seems like there is no way for a  user to efficiently search for, and then work inside clipping functionality with, annotations for specific issues? (Could only generate CSV files, which takes you outside of clipping functionality?) 

(Also, note that I actually see a clip button on search results page of OLC, but it just doesn't work when you click on it.)

![screen shot 2017-03-17 at 11 11 49 am](https://cloud.githubusercontent.com/assets/14825437/24052203/a373ce60-0b02-11e7-998a-9d0ef02a7bf4.png)


@anderspeders @jedm @charlesyoung @JesseCCSI

**Comment by jedm** [comment]
Yes, the Clips button should not be on the Toolbar anywhere except Contract View/Summary pages until we resolve this. Especially on live site.

I will return to the many notes we have on this idea from last year and try to circulate some thoughts this week. 

@charlesyoung, if we end up doing a phone call would suggest Anjesh also could join to discuss capabilities.

**Comment by JesseCCSI** [comment]
See comment in #996
