### ISSUE TITLE
OpenLandContracts.com

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1057]
OpenLandContracts.com currently opens the Tunisia RC country site. Please point it to OpenLandContracts.org.

**Comment by manishgs** [comment]
done.

**Comment by SamCCSI** [comment]
Thanks @manishgs 

We really just want the .com URL to redirect to the.org URL. Right now if a user goes to the .com URL and then finds contracts, the URL remains .com, which is confusing / not ideal.

Example: 
![image](https://cloud.githubusercontent.com/assets/12913915/23461247/1d50a5f4-fe57-11e6-992a-ed8ceb6612ac.png)

Could you please make it so that .com redirects to .org (so that users copying the URL of a specific contract will always have a .org URL), rather than the way it is set up right now?

**Comment by charlesyoung** [comment]
@iprunache will you be able to assist with this request?

**Comment by iprunache** [comment]
@charlesyoung we'll look at this tomorrow

**Comment by iprunache** [comment]
@SamCCSI @charlesyoung I've implemented a 301 redirect from .com to .org. Could you please check again? Thanks!

**Comment by SamCCSI** [comment]
@iprunache many thanks! Working perfectly.
