### ISSUE TITLE
Searching for annotation tags

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#110]
The search layout obscures the first result
![image](https://cloud.githubusercontent.com/assets/12913915/8570535/fecdd558-254e-11e5-97b9-d45156c46bc1.png)

Also, is it possible to have a similar typed text search for the annotation categories? (I assume tags are for metadata).

**Comment by anjesh** [comment]
@anderspeders 
I feel that the whole annotation process needs further discussion regarding linkages. We introduced category so that the related annotation are grouped. Tags are there, but haven't linked as such with the metadata as per this issue https://github.com/NRGI/resourcecontracts.org/issues/113

**Comment by anjesh** [comment]
This is fixed now. Select2 is used for both tags and categories. We still need to define what goes in tags, though users can add free-text in tags along with predefined list.
