### ISSUE TITLE
Elasticsearch update

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1112]
For discussion. 

Update index.resourceontracts.org and api.resourcecontracts.org to use the latest version of Elasticsearch.

**Comment by adinuca** [comment]
Thank you @charlesyoung .
The version that we are currently using is 2.4 which is no longer maintained since the beginning of this year. The latest version is 6.3.

Activities involved would be : 
- updating Elasticsearch cluster
- updating the PHP Elasticsearch client used by index.resourcecontracts.org and api.resourcecontracts.org
- fixing incompatibilities between versions
- testing

**Comment by adinuca** [comment]
Email from Compose from the 2nd of August: 

> At the end of February 2018, Elasticsearch 2.4.x came to the end of its supported life. In line with our database lifecycle policy, we have therefore deprecated all Elasticsearch 2.4.x deployments on Compose. Also in line with that policy, we will retire those all Elasticsearch 2.4.x deployments on October 31st 2018.What you need to do:Existing Elasticsearch 2.4.X users can upgrade by using our backup and restore to a new deployment capability.With a major version change such as this, we recommend that you use this process to create an Elasticsearch 5.6.9 deployment. That new deployment can then be used to test your applications and allow you to make any required changes.Consult the new Upgrading and Migration Guide in the help documentation for more details on how to do this: https://help.compose.com/docs/elasticsearch-upgrade-and-migrations.If you have any concerns or questions, please contact us, we are always happy to help The Compose Team
> --

**Comment by adinuca** [comment]
Created #1125 for handling the migration.
