### ISSUE TITLE
Improve Pinning feature

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#116]
This is followup from Sprint3 pinning https://github.com/NRGI/resourcecontracts.org/issues/70 

* There should be proper instructions to the user on how to Pin
* Pin numbers should increase when the user does the selection
* There should be Pin option in the annotation list as well so that user can click and it gets pinned
* Pinning in the contract comparison page
* Date to be captured during pinning so that users can see when the pins are pinned

**Comment by anderspeders** [comment]
Pinning is not functional on front end. 

Can you please remove until we have a funcitonal model implemented?

**Comment by anjesh** [comment]
As per our previous discussion, we will pinning the annotations only. For ease, we will have a separate page for pins to see the annotations that have been pinned. The researcher may quickly pin the annotations of their interest when they are browsing the contracts and then quickly 

In the annotations listing page (in contract view and contract summary page), there will be icons beside the annotations-text. Clicking on it will save the annotations in the local storage of the browser.

![image](https://cloud.githubusercontent.com/assets/120488/11233421/861e2766-8de5-11e5-93d6-636719787f96.png)

Now the users may see all the pinned annotations in different contracts in a separate page. The user may remove one at a time or download all the annotations in a csv file. These annotations will also have link to the annotations in contract view page. 

![image](https://cloud.githubusercontent.com/assets/120488/11233448/acef0220-8de5-11e5-8a3b-d9380f62707e.png)

**Comment by SamCCSI** [comment]
1. prefer a star rather than the pin icon (the pin reminds us of the location pin on google maps or uber, which might be confusing for the user).

2. The word "Pinning" is meaningless for non-tech users. More intuitive to refer to this feature as 'Store for Later'/ 'Save for Later' (or similar) 

3. Need to delete that /!\ icon -- that icon is used in most sites / programs to indicate a system error, and so is not appropriate here.

4. Can we see a more complete mock up of the 'Pins' page? Still struggling to understand how the page would actually look/ work. 

5. How would the user navigate from a contract page to the 'Pins' page?

**Comment by jedm** [comment]
Do we have any user-facing language explaining what Pins are? I find myself not understanding what they are for. What is the User Story associated with Pins exactly?

**Comment by anjesh** [comment]
Userstory from https://github.com/NRGI/resourcecontracts.org/issues/70
> As a user I should have the ability to select and cache individual clauses across contracts for comparison. These clauses should be possible to store in session and export to excel or PDF as a report. Example: I wish to compare stabilization clauses. I search contracts for clauses tagged as such, pin those clauses for later comparison and export a report of the pinned html, data and associated metadata.

**Comment by jedm** [comment]
For a variety of reasons it may be better to merge Pinning and the various Comparison features being considered/requested into one type of function under a single name. Top reasons being not confusing the users and leveraging maximum amount of functionality being created or spec-ed by YI. 

What do others think? @byndcivilization? @anderspeders @kaitlinccsi? @charlesyoung?

**Comment by KaitlinCCSI** [comment]
Fine with merging two features if it can be done in a way that is not
confusing. And if pinning is mainly to enable comparisons, then I agree it
makes sense to merge them. On CCSI's side, we think the pinning feature
could be useful, but that it is not an intuitive feature as currently
presented, which is why we suggested some changes in icons/language and
also requested a mockup to better understand how it would look and work.

On Thu, Dec 3, 2015 at 3:47 AM, jedm <notifications@github.com> wrote:

> For a variety of reasons it may be better to merge Pinning and the various
> Comparison features being considered/requested into one type of function
> under a single name. Top reasons being not confusing the users and
> leveraging maximum amount of functionality being created or spec-ed by YI.
>
> What do others think? @byndcivilization? @anderspeders @kaitlinccsi?
> @charlesyoung?
>
>
> > On Dec 3, 2015, at 1:04 AM, Anjesh <notifications@github.com> wrote:
> >
> > Userstory from #70
> >
> > As a user I should have the ability to select and cache individual
> clauses across contracts for comparison. These clauses should be possible
> to store in session and export to excel or PDF as a report. Example: I wish
> to compare stabilization clauses. I search contracts for clauses tagged as
> such, pin those clauses for later comparison and export a report of the
> pinned html, data and associated metadata.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/116#issuecomment-161570329>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PMVKT4i&m=13b2a4de3edc&t=20151203&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PMVKT4i&m=13b2a4de3edc&t=20151203&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PMVKT4i&m=13b2a4de3edc&t=20151203&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by jedm** [comment]
@anjesh and @anderspeders Am now completing slides to recommend UX for pinning and comparison (merged under the term "Clipping"). Regarding the above thread, do we assume each user has their own Pins? If so, is this based on cookies? Otherwise we are creating the need for user login, yes? Because how would the system know whose pins are whose?

**Comment by jedm** [comment]
@anjesh any thoughts on this?

**Comment by manishgs** [comment]
This issue will address in https://github.com/NRGI/resourcecontracts.org/issues/789
