### ISSUE TITLE
Investigate if we can do only one request per search page viewed

### ISSUE THREAD

**Issue by adinuca** [NRGI/resourcecontracts.org#1172]
## Why
For every page viewed on the RC subsites, there are 26 requests made to RC API. 

## What
- [x] Investigation is made if one or 2 requests made to RC API could return the results needed for RC subsites search page
- [x] Further issues are raised after the investigation for implementing the changes needed.

## Notes
At the moment RC subsites page works in the following way:
- one request is made to RC-API with the search parameters, this returns a list of contracts
Eg: http://api-staging.resourcecontracts.org/contracts?country_code=&year&resource=&per_page=25&from=0&sort_by&order&all=0&download=&lang=fr&category=rc
- one request for each contract is made to retrieve details about the contract
Eg: http://api-staging.resourcecontracts.org/contract/995/annotations?lang=fr&category=rc

**Comment by adinuca** [comment]
Hi @anjesh ,

Do you have any input for this issue? 
To handle your concerns about other systems, the plan is to add to the API, not to change or remove endpoints.

Thank you!

**Comment by anjesh** [comment]
This might also need refactoring the code-base both on the API and subsite. I understand that these cases might be due to additions of features on top (like showing annotations number in the contracts-list) and we might have used the existing API for that, instead of adding that number in contracts-list-API - urgency vs system thinking. Again suggest to create a new issue under "performance" label or something similar :) 

These fixes might also do some cost savings on the server-side and would justify the fixes-cost at NRGI end.

**Comment by adinuca** [comment]
Thank you @anjesh .

Issue #1176 has been raised for decreasing the number of requests made to RC API.
