### ISSUE TITLE
OLC is down 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#1190]
OLC is currently down (screenshot below). Several people experiencing same issue. Seems that RC not currently down. 

@anjesh could your team pls look into why? 

Tagging issue #1154 in case related. 

![image](https://user-images.githubusercontent.com/14910764/54202765-1f7ca380-44a7-11e9-8016-4d9030e3095b.png)

I don't think we received a notification when the site went down, so also flagging that as an issue. cc @SamCCSI

**Comment by adinuca** [comment]
Hi @JesseCCSI , I will have a look. It doesn't seem like the same issue as before as RC and RC subsites are working.

**Comment by SamCCSI** [comment]
Confirming that no one at CCSI received an email notification that the OLC site was down.

**Comment by SamCCSI** [comment]
(and thanks, @adinuca !)

**Comment by JesseCCSI** [comment]
Thanks @adinuca !

**Comment by anjesh** [comment]
Somehow the A record is different for openlandcontracts.org, shouldn't it be same as rc as both are hosted in the same container.

![image](https://user-images.githubusercontent.com/120488/54215889-c5b0c380-4510-11e9-8567-dd65a77021e0.png)

Also i see that domain looks expired yesterday and renewed today. Maybe something happened during that gap.

https://whois.icann.org/en/lookup?name=openlandcontracts.org 

```
Updated Date: 2019-03-12T01:31:07Z
Creation Date: 2014-03-11T17:35:24Z
Registry Expiry Date: 2020-03-11T17:35:24Z
```
And http://staging.openlandcontracts.org/ shows namecheap.com page

**Comment by adinuca** [comment]
Normally the application should work as all the other RC sites work fine. There have been no logs since the 10th. I am just testing if the application is running.

Do you have access to the domain registrar?I get this when accessing the site on http, which makes me think it is related to the domain registration:
<img width="1042" alt="Screenshot 2019-03-12 at 18 07 01" src="https://user-images.githubusercontent.com/3942821/54216162-cab24a80-44f1-11e9-9b8d-681fdd78b95e.png">

**Comment by anjesh** [comment]
yes, so the port 80 is working - which i think the uptime checks at the moment so it didn't trigger any email.

**Comment by JesseCCSI** [comment]
Many thanks @adinuca ! We're working on figuring out access to the domain registrar. We'll confirm here once we've resolved the issue and can close the tkt.

**Comment by anjesh** [comment]
I found the info in my email - forwarded to 3 of you. For your action.

**Comment by JesseCCSI** [comment]
Great, many thanks @anjesh

**Comment by JesseCCSI** [comment]
Closing as domain registration issue resolved. Thanks again @adinuca and @anjesh !

**Comment by anderspeders** [comment]
Glad to hear!

**Comment by SamCCSI** [comment]
OLC site was down for 30min on weekend. 

cc @charlesyoung @iprunache @anjesh 

> PingdomAlert UP:
> OLC Subsite (openlandcontracts.org) is UP again at 08/22/2020 09:39:15 AM, after 30m of downtime.

**Comment by candrei** [comment]
@SamCCSI We're investigating the stability of all RC subsites (all are affected): https://github.com/nrgi/nrgi-dcos/issues/548

**Comment by candrei** [comment]
@charlesyoung yes, we can close it for now. Site has been operating properly for the past few weeks.

**Comment by SamCCSI** [comment]
OLC has been down for substantial chunks (30 mins) on 3 occasions in last 3 days. @candrei @charlesyoung not sure if anything can be done, but i can forward notifications if helpful

**Comment by charlesyoung** [comment]
We have increased the Elasticsearch instance to accommodate the current downtime issue. This has impacted OLC, RC and all the RC country sites. We are monitoring the situation.

**Comment by iprunache** [comment]
Sam, thanks for notifying us.

The Elasticsearch servers were timing out during the weekend and that caused the outage. Catalin had to forcefully restart them to get them back working.

This does not seem to be related to our application, it's more likely a bug with Elasticsearch that we're hitting because we've upgraded to the latest version which still has some rough edges to iron out. This issue is a likely candidate: https://github.com/elastic/elasticsearch/issues/44981

I am enabling detailed logging and monitoring to get a better understanding of what's wrong if it happens again. If we confirm it's an issue with the latest Elasticsearch version we'll downgrade to a slightly earlier version to try to mitigate it.

**Comment by SamCCSI** [comment]
Thank you for the update, Ionut!

**Comment by SamCCSI** [comment]
They're working for me
