### ISSUE TITLE
Test of loading and view of an associated document

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#122]
1) Load a contract A

2) Load a contratc marked as Translated contract as associated with contract A

Display how this will appear on the front end site.

**Comment by anjesh** [comment]
How does this work? Allow the researcher to select the contract from the dropdown if she selects yes to "Translatedfrom original". Does that mean contracts will be listed  in translated parent and researcher selects the parent? 
--
![image](https://cloud.githubusercontent.com/assets/120488/8905231/3d454822-3484-11e5-9c78-bb802ca4c8da.png)

This issue is linked with https://github.com/NRGI/resourcecontracts.org/issues/38, though #38 seems to have more documents that need to be linked with the contract.

**Comment by anjesh** [comment]
Covered in #111
