### ISSUE TITLE
Develop API for "Latest contracts"

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#1262]
> part of https://github.com/NRGI/resourcecontracts.org/issues/1244 and this might still need further discussion

- [ ] API should have the following definition /recentgroupedcontracts 
- [ ] sort order is the last published date and then by ES score if there are multiple documents on the same date
- [ ] following fields will be searched for free-text search but the list will always be sorted by last published date and then by ES score
  * title - high weight
  * country field – high weight
  * resource field – high weight
  * company name – high weight
  * annotation title or text – medium weight
  * raw text – low weight

These are the assumptions we will take into account for recent contracts API based on the discussion [here](https://docs.google.com/document/d/1_Mkx7BRUWFhuKzrh-XWIC9D6S1ZIClQBxMZrO0Dr6bE/edit#)

* The grouping feature will be as it is for gsearch
* The threshold date to tag the document as new = (re)published in last 3 months
* we will show all the documents (in case of new associated documents but old main document, main document will be grayed out). All non-new documents will be grayed out.
* users will not be able to use sort feature (sort by country, title) as this will remove the recent-date-wise sort and there's no return back unless the user clicks search again. 
* recent documents to be tagged as `new` for now in the interface but could change later.

<del>We discussed about listing the recent contracts and there are still few confusions on this list feature. </del>

cc @charlesyoung

**Comment by charlesyoung** [comment]
Thanks @anjesh 

Would initial 'new' documents that move past the 3 month publication period be tagged as something else so that these documents can be removed from the most recent list? 

Which aspects are still unclear?

**Comment by anjesh** [comment]
I wrote the assumptions list to clarity the confusions. That was extra line - supposed to be deleted. 

>Would initial 'new' documents that move past the 3 month publication period be tagged as something else so that these documents can be removed from the most recent list?

[From this document](https://docs.google.com/document/d/1_Mkx7BRUWFhuKzrh-XWIC9D6S1ZIClQBxMZrO0Dr6bE/edit#) -- Jed: I think it would be better to show all documents in reverse-chron but to change display to flag/star/change color of documents from last 3 mos. I think this is better than cutting off the list.

--

Also one thing that came in our internal discussion is the last published date vs document created date. Using of last published date means that the first document which is now updated and republished will also appear in the recent list. Is this ok?

**Comment by charlesyoung** [comment]
Yes lets use the last modified date as changes to the metadata, etc should be highlighted. 

Only noticed the 'change display to flag/star/change color' comment now. Would it not be easier and make more sense to only show the documents published during the past 3 months? The user is specifically looking for that info and not a list of all documents.

**Comment by anjesh** [comment]
> Would it not be easier and make more sense to only show the documents published during the past 3 months? The user is specifically looking for that info and not a list of all documents.

There might be exception for those recent associated doc whose main doc is not recent. We need to show main inorder to show associated for group result.

- [ ] We need decision on this before we work on the API. cc @jedm 

In fact we need ok on all our assumptions above.

**Comment by charlesyoung** [comment]
OK, will wait for feedback from @jedm

**Comment by jedm** [comment]
I would want to confirm with @samccsi before we make that change. 

Question: if final decision is to limit this view to show ONLY the recent docs, then what would be the prompt and the path that informs user about getting back to all-docs view?

**Comment by anjesh** [comment]
> Question: if final decision is to limit this view to show ONLY the recent docs, then what would be the prompt and the path that informs user about getting back to all-docs view?

In this case, the user will go to all-docs view by going to home page (long route), or we could add a button in the search panel to "show all docs".

**Comment by charlesyoung** [comment]
The "show all docs" option could be a better. 

cc @jedm

**Comment by jedm** [comment]
If there is a way to go from recent to all without too many extra clicks, I think that is most logical. But suggest we wait for @SamCCSI on this decision.

**Comment by charlesyoung** [comment]
Sounds like the  "show all docs" button will be 1 click away from showing all the docs. Will wait for @SamCCSI input next week.

**Comment by SamCCSI** [comment]
Thanks all, and apologies for my delay in replying.
1)
I'm happy for the new documents view to show only docs from last 3 months. Agree that a Show all docs button in that view would also be great.

2)
> Also one thing that came in our internal discussion is the last published date vs document created date. Using of last published date means that the first document which is now updated and republished will also appear in the recent list. Is this ok?

I actually thought we had discussed this and that we would stick with date initially published. Seems better to me, as I will often have to correct a metadata error, and wouldn't think that this would justify the doc showing up in the new docs list again.

3)
Am I correct in thinking that we are talking about a "New docs" window? I ask because of @anjesh's comment:
> following fields will be searched for free-text search *but the list will always be sorted by last published date and then by ES score*

If a user just does a basic text search, I am strongly of the view that relevance trumps publishing date. The bolded part above would suggest otherwise. Apologies if I am forgetting a conversation (very possible), but if I am I think it's worth discussing before we proceed. I see the [google doc](https://docs.google.com/document/d/1Rqtsm-B-T0yEhm5rAUjYVDQ_2pGiW7B03rR9LLJJHwg/edit?usp=sharing) mentions something about this in point e. at end of doc.

cc @jedm and @charlesyoung

**Comment by jedm** [comment]
Trying to reply to all outstanding questions here. But all will still need to confirm before we sign off:

- Charles and Sam are OK with a view that shows **only** most recent docs, so that user will still need to click on a NEW "Show All Docs" button. If this is agreed, please share demo/sample once more so we can review and approve.

- It seems better to stick with INITIAL PUBLISH DATE to count recency, not modification date. This is per discussions with @SamCCSI. @charlesyoung is this OK?

- We did not imagine that most-recent view would retain sort/date cutoff after usr initials a search or filter. Once user searches on list, the result would display as normal.

If this our shared understanding, then Sam and Charles should confirm with @anjesh and YI can execute.

**Comment by charlesyoung** [comment]
I'm happy with above @jedm 

cc @SamCCSI @anjesh

**Comment by SamCCSI** [comment]
Thanks @charlesyoung. I am as well @jedm @anjesh

**Comment by anjesh** [comment]
> We did not imagine that most-recent view would retain sort/date cutoff after user initiates a search or filter. Once user searches on list, the result would display as normal.

@jedm  This is confusing. Do you mean that most-recent view will switch to all-docs view after user initiates the search? I was assuming that the filter/search will be  applicable to the documents in recent-list only. 

cc @charlesyoung

**Comment by jedm** [comment]
Hi @anjesh,

Apologies for adding any confusion. The confusion is because I was imagining that the recent-list was like a filter. (I continue to think this is better because it requires no new “back” buttons and no extra clicks.)

Is it possible to see a mock-up or even hand-drawn sketch of the most-recent feature so we can confirm basic UX?

Either way, if you and Charles and Sam are all agreed that the “extra clicks” are ok, then you are correct to note that we could filter and search /within/ the partial/most-recent list.

**Comment by charlesyoung** [comment]
Thanks @jedm 

I agree that the filter/search will only be applicable to the documents in recent-list. 

cc @anjesh

**Comment by SamCCSI** [comment]
Nb for @nirvanalama we should be describing this view as recent "**_documents_**", not recent "**_contracts_**"

cc @charlesyoung @jedm @anjesh

**Comment by charlesyoung** [comment]
Just checking if you are you waiting for anything from us to complete this ticket? 

cc @anjesh

**Comment by nirvanalama** [comment]
@charlesyoung @jedm 
### Hello. This is how the user would be able to switch between recent docs and all docs. 
![image](https://user-images.githubusercontent.com/57661914/75429986-c4bbb080-5972-11ea-81c6-4e4891a929e2.png)

### But we think the button "hide search tools" should be placed on the right to not cramp up the content together. (See below for reference)
![image](https://user-images.githubusercontent.com/57661914/75430054-dc933480-5972-11ea-93be-5274eeb5f88a.png)

**Comment by jedm** [comment]
Thanks, @nirvanalama! 

@charlesyoung @SamCCSI let's discuss this proposal for tabbed viewing.

**Comment by bizaybsnt** [comment]
@jedm We have implemented the tabbed viewing for recent and all documents. Please provide us your feedback on the changes.

**Comment by SamCCSI** [comment]
@jedm will have comments re tabbed viewing.

One small point - the light grey dividing lines above the "View [x] other docs" sections don't extend all the way. (see red circle)

But rather than making them extend all the way, i suggest removing them ONLY for these "View [x] other docs] entries. I suggest this because right now it looks awkward where none of the associated docs appear in the list -- eg look at Convention Kerkouane -- there is too much space under the title and the "View [x] other docs" section doesn't feel visually connected. 
![image](https://user-images.githubusercontent.com/12913915/76315881-f2c4bd00-62af-11ea-917e-33ed9f27850a.png)

**Comment by jedm** [comment]
Hi @nirvanalama - My apologies for a slow response. 

To simply the Recent Documents view, and to avoid adding a new style/UI for "toggling," we suggest the attached controller for Recent Documents, matching the style of the "Annotated Contracts Only" controller.

See attached for example.

I agree with @SamCCSI's suggestion about removing the hairline between the previous result and "View # Other Documents." I think it looks best to keep the spacing the same as current version, but remove the line (or make the line white/invisible, to retain spacing). @charlesyoung what do you think?

[RCOLC_recent.pdf](https://github.com/NRGI/resourcecontracts.org/files/4340721/RCOLC_recent.pdf)

**Comment by charlesyoung** [comment]
Thanks @jedm, works for me. 

Just to confirm that we remove the 'hide search tools' as noted in your diagram but retain it as before, below 'Search all documents'?

**Comment by bizaybsnt** [comment]
Hello everyone, Hope you all are doing well.
We have implemented the toggling of recent contract as per @jedm suggestion. Please check it.
![image](https://user-images.githubusercontent.com/25411368/76928685-61d28f00-690a-11ea-8404-d0b11908cd10.png)


We have also changed the style for "View # Other Documents." with the slight background on it.
![image](https://user-images.githubusercontent.com/25411368/76928801-a9591b00-690a-11ea-81cd-ef51d3b2ed57.png)

We are ready to close this issue. Please mention if any changes is needed.

cc: @anjesh @man-git007

**Comment by SamCCSI** [comment]
Thanks @bizaybsnt -- could the "View # Other Documents." please be indented to be in line with the associated document listed?

**Comment by bizaybsnt** [comment]
@SamCCSI we have updated the indentation.. please check it.(May require hard refresh)

**Comment by SamCCSI** [comment]
Thanks @bizaybsnt.

CC @jedm -- Jed do you think the color background should also be indented, so that it only starts where the first word appears, rather than extending all the way to the left as it does now? Here's an example 

![image](https://user-images.githubusercontent.com/12913915/77070597-e253c700-69c0-11ea-933f-27eabf5e2856.png)
(Search term to get this example is https://staging.resourcecontracts.org/search/group?q=&resource%5B%5D=Gold

**Comment by SamCCSI** [comment]
@jedm can you respond to the prev comment?


> CC @jedm -- Jed do you think the color background should also be indented, so that it only starts where the first word appears, rather than extending all the way to the left as it does now? Here's an example
> 
> ![image](https://user-images.githubusercontent.com/12913915/77070597-e253c700-69c0-11ea-933f-27eabf5e2856.png)
> (Search term to get this example is https://staging.resourcecontracts.org/search/group?q=&resource%5B%5D=Gold

**Comment by jedm** [comment]
No, I think it will be more busy if the color background does not begin at the left margin (that would create an extra "stripe"). 

So I would recommend keeping it the way it is in the screenshot above.

**Comment by SamCCSI** [comment]
Thanks @jedm 

@bizaybsnt I think this is all resolved now. Thanks!
