### ISSUE TITLE
Code list updates

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1367]
Allow administrators the ability to update the Document Types, Contract Types and Resources.

**Comment by man-git007** [comment]
@charlesyoung For this we need to make these changes

1. Need UI in admin panel to update code list
2. Will need to migrate code list from file to DB
3. Might need to discuss the UI

This will take time

**Comment by charlesyoung** [comment]
How much time?

**Comment by man-git007** [comment]
@charlesyoung The time estimate for this ticket would be 28hrs.

**Comment by charlesyoung** [comment]
@man-git007 I've added this task as a new S30 support ticket. 

Can we arrange a Skype call this week to discuss the requirements and solution?

**Comment by charlesyoung** [comment]
Add 2 hrs to include only super admin access.

Total: 30 hours

**Comment by sriza** [comment]
@charlesyoung
We have started working on the UI for this issue and have decided on the wireframes as following:

**Comment by sriza** [comment]
@charlesyoung 
It was a blunder on my part that I mistakenly closed the issue. I have opened it again.

We have started working on the UI for this issue and have decided on the wireframes as follows:
- We will be adding a new menu to the sidebar named "Code List" which leads to the listing page for document types, contract types, and resources. They will be present in different tabs. Each tab will contain a button to add a new document type, contract type, or resource and will also contain the table with English, French and Arabic translations to the metadata(document type, contract type or resources) along with the button to edit and delete them.
 
![image](https://user-images.githubusercontent.com/24825118/119476042-68119600-bd6d-11eb-8e09-85be17a7a4f1.png)
- Clicking the add button will open the create form. On cancel, we will be redirected to the listing page.
![image](https://user-images.githubusercontent.com/24825118/119476864-2d5c2d80-bd6e-11eb-911a-1e69d4611224.png)
- Clicking the edit button will open the edit form for respective metadata. 
![image](https://user-images.githubusercontent.com/24825118/119477115-68f6f780-bd6e-11eb-8fe4-010b7b9fe53b.png)
The English translation is a required field for both edit and add form.

It would be wonderful to get your feedback on the wireframes so we could continue with our development process.
Thank you

@man-git007 @adhikari-anish

**Comment by charlesyoung** [comment]
Many thanks @sriza 

Couple points. 
- We need to factor in a login page because it will only be able to be accessed by super users 
- What happens if you try to delete a document type for instance that is been used? 
- I think that English and French should be required 
- Just as an FYI, OLC only uses French and English but that won't be a problem if Arabic isn't required 

cc @SamCCSI

**Comment by sriza** [comment]
@charlesyoung
Thank you for the feedback.

We have planned on adding a new role "super admin editor". Only the user with this role will have access to the code list. 

As for clicking the delete button, an alert message will pop up. 
- For the document type that has not been previously used the message states " Are you sure you want to delete this document type?"
- In the case of the document type that is already used by the contract, the message states " The document type is already in use. Deletion of this document type can only proceed after deleting the contracts that use it". 
Thus, deleting the document type is only possible after the deletion of contracts that already uses it.

We can have both English and French as required fields for the forms.

cc @man-git007 @adhikari-anish

**Comment by charlesyoung** [comment]
Thanks @sriza 

What is the design timeframe?

**Comment by sriza** [comment]
@charlesyoung
We won't be carrying out the extensive design process for this issue. The design will be based on the current theme of the admin site of Resource Contract.

cc @man-git007 @adhikari-anish

**Comment by sriza** [comment]
@charlesyoung 
Based on the wireframes, we have developed the UI for the code list as following : 
- On clicking the code list
![image](https://user-images.githubusercontent.com/24825118/120275811-947b6400-c2d1-11eb-8641-40c483c6ac16.png)
- Add form
![image](https://user-images.githubusercontent.com/24825118/120275906-b543b980-c2d1-11eb-94a8-e169740e0ef3.png)
- Edit form
![image](https://user-images.githubusercontent.com/24825118/120275948-c55b9900-c2d1-11eb-81b2-9072d4ccafe1.png)

It would be wonderful to get your feedbacks on these UI. Please let us know if any changes are to be made.
Thank you

cc @man-git007 @adhikari-anish

**Comment by charlesyoung** [comment]
Thanks @sriza 

Looking good, some minor edits, please. 

- In the menu item rename 'Code List' to 'Code Lists' 
- In the tabs rename 'Contract Type' and 'Document Type' to 'Contract Types' and 'Document Types'
- Rename 'Create New Contract Types' to 'Add Contract Type' (this should also apply to doc type and resources) 

cc @SamCCSI

**Comment by SamCCSI** [comment]
Nice.

Have we made clear that only a select few users would be able to add? I
think so, I remember you mentioning 'super users'. Maybe just make it that
only admins can add? That saves YI adding a new type of user. Then you and
I can just change any ppl who shouldnt be admins back to another status?



*SAM SZOKE-BURKE*
*Senior Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| +1-646-630-4123 <+1646-630-4123> | ***@***.***
| ccsi.columbia.edu <http://www.ccsi.columbia.edu/> | @CCSI_Columbia
<https://twitter.com/CCSI_Columbia> | @samszokeburke
<http://twitter.com/samszokeburke>
| Pronouns: he/him

**Comment by sriza** [comment]
@charlesyoung 

We have added 'Code List' to the admin site as per the above wireframes and discussions. The changes are yet to be properly deployed and migrated at the staging site due to the build failure.

We realized that the user is able to add new resources in the contract form even when those resources don't currently exist in the system.
![image](https://user-images.githubusercontent.com/24825118/121338647-6b944800-c93d-11eb-8217-d0247772a992.png)
This will be quite problematic since the resource isn't present in the database but is mapped to the contract. We can deal with this issue in either of the following ways:

- Removing the ability to add resources directly from the contract form.
- Checking the resources after each contract form save and automatically saving the ones that are not currently present in the database. 

The latter approach wasn't quite in the scope of 'Code List' thus would require additional time to be completed. Also, the user should manually edit the corresponding resource to add the french translation ( which is the required field in the resource form).

Please let us know how you suggest we proceed on solving this issue.
Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza

I've always worried about users having the ability to add resources but couldn't argue the point without providing an alternative, which we now have. My feeling is that we should remove the ability to add resources directly from the form. @SamCCSI what do you think?

**Comment by SamCCSI** [comment]
So this means that the uploader would have to request a new addition to the
admin, and the admin would then add in a separate screen before the new
term was an option?

It seems a bit work intensive, but I agree it is problematic to have
uploaders, who are often new to the database, adding in any resource they
like.

Ok to proceed from OLC's perspective.


---------- Forwarded message ---------
From: Charles Young ***@***.***>
Date: Wed, Jun 9, 2021 at 7:15 AM
Subject: Re: [NRGI/resourcecontracts.org] Code list updates (#1367)
To: NRGI/resourcecontracts.org ***@***.***>
Cc: SamCCSI ***@***.***>, Mention ***@***.***>


Thanks @sriza <https://github.com/sriza>

I've always worried about users having the ability to add resources but
couldn't argue the point without providing an alternative, which we now
have. My feeling is that we should remove the ability to add resources
directly from the form. @SamCCSI <https://github.com/SamCCSI> what do you
think?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NRGI/resourcecontracts.org/issues/1367#issuecomment-857608127>,
or unsubscribe

**Comment by man-git007** [comment]
@charlesyoung The changes have been deployed to the [staging](https://admin-staging.resourcecontracts.org/codelist/contract_types) server. Please verify and provide us feedback if any. Since Shreeja is on a leave we might able to implement feedbacks next week only.

cc @SamCCSI @sriza @adhikari-anish

**Comment by charlesyoung** [comment]
Thanks @man-git007 

Couple points.
- Disallow the manual addition of resources
- I get this [crash ](https://admin-staging.resourcecontracts.org/contract/4641)when adding a resource manually 
- I removed my cache but I still don't see the new resource (Test Resource) in the list 

cc @SamCCSI @sriza @adhikari-anish

**Comment by charlesyoung** [comment]
OK so it seems that the resource was added. 

Issues.
- Should be added in alphabetical order
- I added Test Resource but that was changed to test_resource_

![image](https://user-images.githubusercontent.com/13888372/121873923-2be7aa80-cd07-11eb-987a-fae80afcb159.png)

**Comment by sriza** [comment]
@charlesyoung 
We were only focused on adding the ability to update the resources, document types, and contract types from the admin site with 'Code List'. 

Similar to the admin site the public site has its own set of language files to store different resources, document types, contract types, and their translations. They had always been updated manually at the file level as previously done at the admin site. Thus, retrieving the resources from elastic search will return the keyword of the resource alone ( like test_resource_ in this case) which later gets translated to the value present in the language file before being displayed.

In order to display the values associated with the resources, contract types, and document types added through 'Code List', we would require an open API at the admin site through which the metadata can be obtained as a response by the public site.
Creating this API and integrating it with the public site would require 6 more hours of work than previously estimated.

Please let us know if we can proceed further with this.
Thank you

cc @man-git007 @anjesh

**Comment by charlesyoung** [comment]
@sriza I don't understand why the development would only cover the backend work. What is the point of adding new doc types or resources and not have this displayed on the public site? Why were we not told that the time estimate is only for the backend work? This development methododology is totally nonsensical. 

cc @SamCCSI @man-git007 @anjesh

**Comment by man-git007** [comment]
@charlesyoung During our discussion we were focused on the admin side only hence the subsite part was overlooked. We will work on this.

cc @anjesh @SamCCSI @sriza

**Comment by charlesyoung** [comment]
@man-git007 just checking what the latest is with this ticket.

**Comment by sriza** [comment]
@charlesyoung 
We are currently working on integrating API with subsite. 
The resources and document type metadata seems to have additional data than initially present in the language files. Missing resources, document type or contract type in seeder could later cause error in subsite when codelist is deployed.  We have listed the data we have added to the seeder in the [spreadsheet](https://docs.google.com/spreadsheets/d/11_IC9JTvqG8zdWlmexCzOQL3VmQ6nk4fmu38RInnZeI/edit?usp=sharing). 
Could you please have a look and add the data that we have missed?

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza

I don't fully understand what you are asking. Do you want me to update the Arabic translations?

**Comment by sriza** [comment]
@charlesyoung 
Not the translations but the resources, document type, and contract type that we might have missed but are associated with contracts in OLC or RC.
Could you please review the spreadsheet and add the resources, document type, or contract type that we have missed?
Please let me know if it still sounds unclear.
Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks but I still don't understand. Can you not just pull all the resources, document and contract types from the database? Will be better if I try to do it manually.

**Comment by sriza** [comment]
@charlesyoung 
We will certainly pull the resources, document types, and contract types from the database but it would still be wonderful to get your confirmation on the data that we have collected so far. This would help us be assured on the fact that we have not missed any of the data.
Also I will be on leave for the next three days of this week. So we will resume working on this issue on the next week.

Thank you

cc @man-git007

**Comment by sriza** [comment]
@charlesyoung 
We have completed the development of open API and have integrated it with subsite. These changes are now deployed to the staging sites.
Could you please have a look and let us know if they are ok or if any changes are to be made?
Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks @sriza. I did some tests and it works as expected. 

Something small but can I ask that you remove the 'Whoops' text and update the text for the existing types to 'This entry already exists in the database' or something to that effect. 

![image](https://user-images.githubusercontent.com/13888372/126120038-521979ce-614f-47e1-97c3-5f373dda203d.png)

**Comment by sriza** [comment]
@charlesyoung 
We can surely remove the 'Whoops' text.
About the update on the error message for the existing types, each field is being individually tested for uniqueness, and the error message is similarly generated for the clarity of the user. Do you want us to place a single error message related to the existing entry instead of multiple error messages for each field?
![image](https://user-images.githubusercontent.com/24825118/126148384-cc1c439e-a0d8-49b4-9728-83622685b5a1.png)
cc @man-git007

**Comment by charlesyoung** [comment]
That's a good point. Can we change the text to show below if the new type exists individually (so just the one shown if already exist) or globally (if more than one entry already exists)?

The English entry already exists in the database
The French entry already exists in the database
The Arabic entry already exists in the database

**Comment by sriza** [comment]
@charlesyoung 
These changes have been made and deployed to the staging site.
![image](https://user-images.githubusercontent.com/24825118/126158226-ed20467b-d7c3-4619-a0aa-bdbe69030cc0.png)

Also, the dropdown list of resource select field in subsite has been ordered alphabetically.

Please have a look and let us know if anymore changes are to be made.
Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Thanks. Just a small request, please. Capitalise all references to English French and Arabic. You can then move it to the Prod site. 

![image](https://user-images.githubusercontent.com/13888372/126175956-c0946822-3a4c-44f7-ae47-1ba0cddce808.png)

**Comment by man-git007** [comment]
@charlesyoung The changes are deployed on the [live](https://admin.resourcecontracts.org/) site. Please verify.

cc @sriza @anjesh @adhikari-anish

**Comment by charlesyoung** [comment]
OK thanks. I've added a new resource in the backend and it works but don't have a contract to link to the new resource. 

@SamCCSI do you have any new code lists that can be linked to a document? 

If not then I suggest we close this ticket.

**Comment by SamCCSI** [comment]
Let's close and reopen if we encounter issues when we need this?
