### ISSUE TITLE
Add "complete" and "publish" button at end of metadata form

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#141]
User feedback: 
"Another thing that is notable are the steps to publish—there are many buttons which is not very efficient: e.g., after filling in all the metadata I click “submit” at the bottom of the page.  Next, I get relocated to “all contracts” page, so I have to then click again on the contract that I just entered the metadata for.  Once there I have to click “Make Complete” then it ask if I am sure I want to, so I then click “OK”, then I have to click “publish”, then it asks if I am sure again so I have to click “OK.” Over time and several uploads, all of those steps would slow me down."

**Comment by anjesh** [comment]
The purpose of separate complete and publish is that researcher will "Complete" the contract and the admin will "Publish" it. However like you said, we will show the contract view page (instead of the listing) when the contract is added or edited. 

Perhaps we could bring new action "Complete and Publish" for the users with admin role. They would see two buttons - "Complete" and "Complete & Publish". If they are sure about the content, they would click "Complete & Publish", otherwise just "complete" if they would like to get verified by some admin before it gets published. 
cc @anderspeders

**Comment by anjesh** [comment]
This is mostly UI issue. Will look into it during the design phase. 
Thoughts?
https://projects.invisionapp.com/d/main/default/#/console/3736944/94419366/preview
https://projects.invisionapp.com/d/main/default/#/console/3736944/94419783/preview

Moving to Sprint 6.

**Comment by anjesh** [comment]
I think we can drop this as we will have "publish all" button without having to go through the existing workflow.

**Comment by anjesh** [comment]
Closing this. This might not make sense as we have publish all functionality.
