### ISSUE TITLE
Develop technical documentation

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1438]
1. List current versions of DB, all 4 repos libraries and packages
2. List out and manage the installation guide for all 4 repositories
3. Document how to use Admin (includes contract upload, publish, contract upload, MTurk workflow, pdf annotations, associated documents) 
4. Abby documentation, MTurk API documentation and Elastic Search API documentation
5. List out libraries and packages that can be upgraded for all repos
6. Make a workflow block diagram 

cc  @SamCCSI @man-git007

**Comment by charlesyoung** [comment]
@man-git007 what is the latest with this ticket? I'm on leave from tomorrow.

**Comment by man-git007** [comment]
@charlesyoung We are working on the documentation part. It is in the draft phase. We will share it with you by tomorrow.

cc @sriza

**Comment by charlesyoung** [comment]
OK, I'm on leave from tomorrow so will review in the new year.

**Comment by charlesyoung** [comment]
@man-git007 what is the latest with this ticket?

**Comment by man-git007** [comment]
@charlesyoung We have worked on it. This is the [link to the documentation](https://docs.google.com/document/d/1rg_WneKU3VFXgr3NZfqjwdub5Y5FXKb8JwcNHbeGokY/edit#heading=h.kyw4eykrrpvl). Small changes are remaining regarding `abby API` on which we are working. We might need some help from cloudEnlight team as well regarding the server deployment and configuration

**Comment by charlesyoung** [comment]
@man-git007 will you be able to finish the document early next week?

**Comment by sriza** [comment]
@charlesyoung @SamCCSI 
@zaid-azmat @mabuturabcloudelligent @yahyagulshancloudelligent 

We have developed the final draft for the technical [documentation](https://docs.google.com/document/d/1rg_WneKU3VFXgr3NZfqjwdub5Y5FXKb8JwcNHbeGokY/edit?usp=sharing). The [documentation](https://docs.google.com/document/d/1rg_WneKU3VFXgr3NZfqjwdub5Y5FXKb8JwcNHbeGokY/edit?usp=sharing) contains the details about the installation, API, deployment, and how-to guides of RC repositories and is open to revision with modifications in API and working of the application. The revision date will be added and updated in every change hereafter.

Please have a look at the [documentation](https://docs.google.com/document/d/1rg_WneKU3VFXgr3NZfqjwdub5Y5FXKb8JwcNHbeGokY/edit?usp=sharing) and update us with feedback, corrections, and further additions if there are any to be made.

Since the documentation is complete for now, please let us know if the issue can be closed.

Thank you

cc @man-git007

**Comment by charlesyoung** [comment]
Many thanks
