### ISSUE TITLE
Remove general comment feature for metadata / deploy granular metadata comment field

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#146]
![comment feature for metadata - rc](https://cloud.githubusercontent.com/assets/1101585/8882533/90a0c936-3215-11e5-8dbc-7239d9a40cd6.JPG)

As a user I would like to be able to comment on field that are missing in the metadata form. 

Would it be possible to add a comment feature for the metadata?

**Comment by anjesh** [comment]
Will the user complete the metadata in that case? Or wait for the admin to suggest on what to do next? 
Now there's commenting feature in every action (complete, publish, reject) so that researcher can comment about the missing field in the complete action. If that doesn't work, we could then have separate "comment" action, apart from "Complete". Thoughts?

**Comment by anderspeders** [comment]
Can a comment feature be added to **each metadata field**?

**Comment by anderspeders** [comment]
Based on feedback from users I have the following request: 
- Remove the general comment section for metadata
- Create a non-mandatory comment feature for each metadata field

These issues should be treated separately, so for now please go ahead and remove the metadata comment feature.

**Comment by anjesh** [comment]
This can wait for a while as we have "Publish all" functionality.

**Comment by anjesh** [comment]
commenting for each metadata field is enabled here https://github.com/NRGI/resourcecontracts.org/issues/101
