### ISSUE TITLE
Feature for UI on front page: Common seach terms

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#149]
As a start one could consider automatic generated searches in the documents for phrases or words: 
- stabilization clause
- local content
- environmental protection
- other categories as outlined in the tagging guide

Each search result could feature a snippet from the text as well as the metadata from that specific contract. 

This would be search terms available across both annotations and the raw text.

**Comment by anjesh** [comment]
I am thinking of annotations explorer as a separate interface, as it appears that annotation is of utmost importance. It is tricky to incorporate annotations in a usable way in the existing search functionality.  I hope i am in the right direction, suggest if you see this being part of the current search functionality - https://github.com/NRGI/resourcecontracts.org/issues/43#issuecomment-117150332 

There will be a separate link to annotations explorer,which lists all the annotation categories on the right.  All the contracts will be listed by default (with pagination). We can decide what fields to show when the contracts are listed. The shown list is just for example only for now. 

![image](https://cloud.githubusercontent.com/assets/120488/9109627/e5b6c34e-3c56-11e5-8e6b-6e65d7722d8f.png)

User clicks on any one category on the right and sees how many of the contracts has that particular annotation say "Stabilisation clause". Since there will be lots of categories, user may also filter category for quick find. 

![image](https://cloud.githubusercontent.com/assets/120488/9109668/0ef8a1b4-3c57-11e5-8989-f30d919ff02d.png)

User clicks on the contract and sees all the annotations of that particular contract. 

User clicks on the other category and sees all the contracts which have both the category annotated. The categories will be ANDed. User can click on the selected category to de-select it again. 

![image](https://cloud.githubusercontent.com/assets/120488/9109699/4fdc126a-3c57-11e5-9d07-2150927dcf59.png)

User searches for the particular term within the selected annotations categories to quickly find the contracts of his/her interest. 

![image](https://cloud.githubusercontent.com/assets/120488/9109722/7781e876-3c57-11e5-9610-3f62fa7f2b75.png)

Thoughts? @anderspeders @byndcivilization

**Comment by anjesh** [comment]
We can see the requestsed features in the current search results.
