### ISSUE TITLE
Prepare migration of OLC contracts and annotation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#185]
Check list 
- upload 60-70 OLC contracts from dropbox using an automatic load workflow
- create load workflow for 60-70 XLS based annotations (Sam to provide an example)

Sam to provide context:

**Comment by SamCCSI** [comment]
On the old platform, users list all annotations on a template XLS spreadsheet. This spreadhseet is then uploaded, and an uploader physically assigns each annotation to the relevant position on the relevant page.

Example: https://drive.google.com/a/columbia.edu/file/d/0B_20gOENmcGnMWRjY0lGLXNOXzQ/view?usp=sharing

The category, string annotation, article reference, and page number/position are listed in separate columns. 

We will have 60-80 completed spreadsheets that also need to be factored into the migration onto the new platform (in Sprint 7). They are different from the existing online annotations, because there is no ribbon placed on the page - rather there is only a page reference. Example 6 (bottom) = page 6, located in the bottom third of the page.

**Comment by anderspeders** [comment]
@anjesh We will need to schedule a call during sprint 6 to discuss the migration of these contracts and annotation during sprint 7.

**Comment by byndcivilization** [comment]
This is kind of related to annotation bundling. If we used annotation group to point to a a bundle record that actually contains the content of the annotation. If theres a group table with each record being a bundle, the template could feed into this table.

**Comment by anjesh** [comment]
The [google spreadsheet](https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit#gid=605754846) is created for 31 OLC contracts with the metadata, the annotations will be inserted directly into the database, with the appropriate position like top meaning somewhere in the top of the page. 

Need to do the insert into the database - sprint 7.

**Comment by anjesh** [comment]
We have migrated the OLC data to Staging.
