### ISSUE TITLE
Rename <Translation from Original> to <Contract has parent> 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#192]
This option will need to be functioning for not only translations of contracts but also for various other document types. 

For example: 
A *Production Sharing Agreement* might have multiple childs including:
- a translation of the contract
- an annex to the contract
- an environment impatc assessment

**Comment by anderspeders** [comment]
This issue therefore also helps explain the issues of bundling of multiple contracts.

See issue #111 #185

**Comment by anjesh** [comment]
So that means we don't need to have "translation field" now. The translations if available will be part of the associated contracts. We need to add a new field for "Parent Contract", under "Associated Contracts" section.

The section will be removed 
![image](https://cloud.githubusercontent.com/assets/120488/9486557/829712d6-4be8-11e5-996b-885019f233d2.png)

"Parent Contract" will be added under "Supporting Documents" block.
"Supporting Documents" will be renamed to "Associated Documents"
![image](https://cloud.githubusercontent.com/assets/120488/9486567/950d4d7c-4be8-11e5-8dcf-a2f7002a8d20.png)

**Comment by anjesh** [comment]
The parent contract will be shown in the subsite contract view page as well.

**Comment by anjesh** [comment]
Fixed.
