### ISSUE TITLE
Bug in mech turk results page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#221]
![mech turk bug in results page](https://cloud.githubusercontent.com/assets/1101585/9495544/16f99322-4bda-11e5-9952-7fc0f954c4cc.JPG)

**Comment by anjesh** [comment]
It appears that this is due to the slow loading of the pdf when the worker is loading the task page. That's the error message, which appears when the contract fails to load. We will need to change the error message to something like this. 

@anderspeders we need to reject this assignment and ask worker to do it again. 

--
Error in loading pdf file. 

There's error loading the pdf file. If you are seeing this text, please reload the page again. If you continue seeing this, please inform the administrator or email at resourcecontracts@yipl.com.np. Your assignment will be rejected if you transcribe this error message.
--

**Comment by anjesh** [comment]
We need to setup separate Https server to host the MTurk HITs.

**Comment by anjesh** [comment]
This is not bug but rather a pdf-load issue. We need to reject this page and need to fix the server issue. Will create a new issue for https setup.
