### ISSUE TITLE
CCSI to pick color codes - YI to implement

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#272]
@samCCSI I understand some adjustments to the color codes is needed. I suggest that CCSI selects the exact colors codes that you prefer, rather than having Young Innovations guessing what you prefer.  

Here is one site where you can go to find the color codes:  
http://html-color-codes.info/

**Comment by SamCCSI** [comment]
The color code for blue is 0033cc and for green is 009900.

**Comment by anjesh** [comment]
You mean the color code for these home page colors 

![image](https://cloud.githubusercontent.com/assets/120488/9953131/9855717c-5dfd-11e5-8037-3bc155671990.png)

**Comment by SamCCSI** [comment]
Yes, thanks - as Anders mentioned, the background photo will change.

**Comment by SamCCSI** [comment]
@anderspeders

**Comment by anderspeders** [comment]
Based on the implemented: http://alpha.openlandcontracts.org/

@SamCCSI Can you confirm that this can be closed?

**Comment by SamCCSI** [comment]
Many thanks @anders !

I assume the color codes are correct.

Can you confirm that you will incorporate our previous request to move the
position of the background photo so that it shows 50% sky, 50% land, rather
than right now, which shows only sky?

(Also the photo seems to load slowly, but I'm not sure if compression is
available without harming the quality of the photo; interested in your
thoughts)

Many thanks,
Sam

On Mon, Sep 21, 2015 at 8:00 PM, Anders <notifications@github.com> wrote:

> Based on the implemented: http://alpha.openlandcontracts.org/
>
> @SamCCSI <https://github.com/SamCCSI> Can you confirm that this can be
> closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/272#issuecomment-142062073>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment]
This ticket is for color codes so I am closing this. 

@SamCCSI I have created a sep. ticket for the image crop https://github.com/NRGI/resourcecontracts.org/issues/352
