### ISSUE TITLE
Setup SSL certificate of Mechanical Turk HIT page

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#275]
issue 1:

Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Apache/2.2.15 (Red Hat) Server at task-manish707.rhcloud.com Port 443
ten task accepted but no service available

**Comment by anjesh** [comment]
Currently we are using free version of https://www.openshift.com/ for hosting the Mturk task page, as Mturk requires https for the task to be displayed, and they seem to have some problems at times. We could host in AWS but need ssl certificate. 

The problem is the tasks that are already created will continue using the same URL. Only the newly created HIT will then taken the new url.
Thoughts?

**Comment by anjesh** [comment]
@byndcivilization We need to have https. I will setup a new free-tier instance for this purpose only, which will ensure it's up. Can you purchase the ssl certificate and pass on the info to us. We will setup in the amazon instance.

**Comment by anjesh** [comment]
@santosh-neupane please document the process of setting up ssl here.

**Comment by santosh-neupane** [comment]
``yum -y  install httpd mod_ssl``

create ssl.conf at ``/etc/httpd/conf.d``
configure ``ssl.conf`` as:

``Listen 443``

``<VirtualHost *:443>``

    ServerName 127.0.0.1:443

    SSLEngine on

    SSLCertificateFile /path/to/myserver.crt

    SSLCertificateKeyFile /path/to/myserver.key

``</VirtualHost>``

- Restart webserver
`` sudo service httpd restart``

**Comment by anderspeders** [comment]
I suggest we push to sprint 10.

**Comment by manishgs** [comment]
This will address in issue #930
