### ISSUE TITLE
Add contract "End Date" to metadata

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#298]
Should consider adding the following metadata field to the form. 

**Field name | Description | Format**
endDate	The end date for the period.	date-time string

The data field should be added in accordance with the Open Contracting Data Standard: 
http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#period

**Comment by anderspeders** [comment]
Let's postpone this to blue sky. removing from sprint 9.

**Comment by anderspeders** [comment]
Quesiton for @KaitlinCCSI @samccsi, Perrine: Do you encounter often that contracts will include an *end date* or a *XX year period* from signatory date? If yes, this would enable us to add *end date* as metadata field. 

I am asking because this is one of the fields that the Open Contracting team has pointed out this as a missing metadata field in RC/OLC.

**Comment by KaitlinCCSI** [comment]
With the contracts I've viewed, it's more common to have a term/duration
that is specified (e.g., 50 years, 70 years, 99 years), rather than a
specified end date, although the forestry contracts from the DRC provide a
specific end date. (Note that I just checked some of the contracts on RC as
well and duration from effective date also seems much more common than
specified end date.)

While you can sometimes calculate the end date using the term/duration, I
would strongly suggest not doing this. This is because the term will
generally run from the effective date of the contract (when the contract
comes into force), and that date may rely on external actions (for example,
it may need to be ratified before it is effective, or it may depend on a
condition precedent, etc). So since the signature date does not always
equal the effective date, trying to calculate the end date by adding the
term to the signature date may give an incorrect answer.

So if we do add an end date metadata field, we should make sure that it
only filled out if the end date is specified in the contract, which I think
would be relatively infrequent.


On Thu, Dec 3, 2015 at 5:35 PM, Anders <notifications@github.com> wrote:

> Quesiton for @KaitlinCCSI <https://github.com/KaitlinCCSI> @samccsi
> <https://github.com/samccsi>, Perrine: Do you encounter often that
> contracts will include an *end date* or a *XX year period* from signatory
> date? If yes, this would enable us to add *end date* as metadata field.
>
> I am asking because this is one of the fields that the Open Contracting
> team has pointed out this as a missing metadata field in RC/OLC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/298#issuecomment-161824633>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PNbRMBD&m=825b85f7cf6b&t=20151203&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PNbRMBD&m=825b85f7cf6b&t=20151203&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PNbRMBD&m=825b85f7cf6b&t=20151203&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
Thanks @KaitlinCCSI, 
Very helpful context.

**Comment by upasna01** [comment]
The issue is further discussed on 
https://github.com/NRGI/resourcecontracts.org/issues/867
