### ISSUE TITLE
Annotations in left bar should be linked to the contract text itself

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#337]
![image](https://cloud.githubusercontent.com/assets/1101585/9951264/42752d58-5d92-11e5-8933-70393883fd9a.png)

**Comment by anjesh** [comment]
This might take a while as the existing annotatorjs and annotarious libraries don't have such feature by default. Pushing to Sprint 9.

**Comment by anderspeders** [comment]
How can the linkage between left bar and the contract itself be displayed: 
- When I hover over the annotation in the contract page and the annotatin text pops up - I want the annotation in the left bar to interact eg. by highlight.
- Can the annotation pop-up have cluster category added at the bottom of the pop-up?

**Comment by KaitlinCCSI** [comment]
To clarify/expand on Anders's points:
- When I click on the annotation in the contract page and the annotation text pops up -- I also want the annotations in the left bar to scroll so that I can see the annotation there (if it only highlights but does not scroll, a user would miss that interaction unless the annotation happened to be one of the few that is visible at that time)
- We don't want the annotation pop-up to have the cluster category added at the bottom of the pop-up, but rather the annotation title at the bottom of the pop-up. So, for example, if you are viewing the pop-up linked to "Infrastructure", you would want to see "Infrastructure//L'infrastructure" at the bottom of the pop-up (and not "Operational", which is the cluster that the annotation is assigned to). 
- The annotation title should be distinguishable from the annotation text -- ideally it would look visually similar to how the annotation title is shown in the left bar, but at the very least it should not be italicized, which will help distinguish it.

cc @jedm @samccsi in case I forgot something

**Comment by byndcivilization** [comment]
Can we use a jquery function to call both annotation and left bar divs based on custom class?

**Comment by byndcivilization** [comment]
This is implemented right @anjesh ?

**Comment by anjesh** [comment]
Yes the annotation when clicked on the pdf is linked to the annotation on the left bar. But linking annotation from left bar to the pdf needs a little more time and requires change in annotatorjs events handling as i have mentioned here https://github.com/NRGI/resourcecontracts.org/issues/389#issuecomment-143728872 

Will be closing this.
