### ISSUE TITLE
Clean annotation categories which have no value

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#366]
![image](https://cloud.githubusercontent.com/assets/1101585/10029698/66eb504c-6141-11e5-85a0-8128af3f763c.png)

http://alpha.openlandcontracts.org/search?q=&annotation_category%5B%5D=parent-companies-or-affilates-outside-of-the-country-if-different-from-the-above-mentioned-and-their-corporate-headquarters

**Comment by anjesh** [comment]
@hello-deepak options with not contract shouldn't appear in any of dropdown.

**Comment by anjesh** [comment]
As i discuss with you earlier, this is due to the fact that metadata is in draft state and annotations is published. So the search options lists all the annotations but when the results are fetched, the metadata is not present and hence no results listed. 

Ideally this shouldn't appear if we do publish all. So closing this.
