### ISSUE TITLE
Assign contract URL based on open contracting id

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#377]
Add the OCDS ID to the URL for each contract. 

For RC and OLC this should be implemented in this way:
resourcecontracts.org/contract/[OCDS ID]
openlandcontracts.org/contract/[OCDS ID]

This will follow standard best practises of for example:
For UK companies house - https://beta.companieshouse.gov.uk/company/03323845 where [03323845] is the ID

**Comment by jedm** [comment]
Would these be aliases or the only permanent URL for the contract. Per #375 on linking to contracts and annotations, aligning RC/OLC with OCDS should not delay creation of permanent links, correct? Just confirming.

**Comment by anderspeders** [comment]
As I understand these should be separete issues. But let's hear from @anjesh

**Comment by anjesh** [comment]
We are thinking of having the url as follows 
resourcecontracts.org/contract/[Internal ID]-[OCDS ID]
Would this pose any problem? 
The internal ID is the one that we see now - the auto-assigned numbers to each contract when it is added to the system. Since all the processing is done in the system based on the internal ID now, we won't have to make much change in the codebase to append OCDS ID in the existing system. We just need to get Internal ID from the URL and process as it's now. 

Also OCDS ID generator has been properly placed now and what country is changed (then OCDS id will need to be updated again, which we have put in place in the codebase). Theoretically this shouldn't happen but during data entry, it might - human err.

**Comment by anjesh** [comment]
OCID now part of the URI http://www.openlandcontracts.org/contract/683-ocds-591adf-CD0848066778OL/view

**Comment by anderspeders** [comment]
Looking at this again I do think that adding the internal identifier makes little sense in URL, as it essentially makes external users unable to reproduce calls and links. (I understand the small winfrom an admin point of view but think the overall setup appears to be a loss with the user being unable to fetch a consistent URL). 

@byndcivilization thoughts?

**Comment by anjesh** [comment]
We will make change in the API to fetch the contract based on ocid or just simply id. cc @hello-deepak

**Comment by anjesh** [comment]
Now only OCID is used. Internal id removed from the URLs.
