### ISSUE TITLE
OLC data review

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#402]
![non-capitalised annotation categories](https://cloud.githubusercontent.com/assets/1101585/10164910/3f779892-668a-11e5-8021-a1c1c80f6f90.JPG)

I see a series of non-capitalised annotation categories which makes them appear non-standardised:
- audit, 
- other
- other-financial-fiscal
- right-to-access-concession
- social-human-rights-monitoring
- state-agency
- water-user

@KaitlinCCSI @samCCSI Is it correct to assume that we need to map each of these categories one from the a current annotation category codelist?

*If* these should be added as additions to the category we need them in *capitalised final wording* and with a *French translation*.

**Comment by anderspeders** [comment]
Adding an example: 

The annotation category *other* should be capitalised and provided a French translation: 
![image](https://cloud.githubusercontent.com/assets/1101585/10165269/566a51fa-668c-11e5-87fe-87f189fda08b.png)

**Comment by KaitlinCCSI** [comment]
Yes, any non-capitalized annotation category is an error. I have specifically raised this issue multiple times, including in emails and calls, in the context of how they are appearing in dropdown menus. We have already put together a mapping for the dropdowns to fix, which I've sent and linked to several times. This includes annotation categories that are appearing in this way, and presumably the mapping is the exact same regardless of whether it shows up in the annotation column or the dropdown. See this document ("Dropdowns to fix" tab): https://docs.google.com/spreadsheets/d/18xCuXuxQSbxlhxUgufNWLiLO_V22wh3pd7oC0Q8Ts1k/edit#gid=852958550

The only new error that I know of is "other" - it can be "Other - miscellaneous" and the French translation we've been using is "Autre - divers"

cc @samccsi

**Comment by anderspeders** [comment]
Hi @KaitlinCCSI, 
As indicated in these conversations we needed to have all OLC contracts loaded to the database before we could take on the full data quality review. As addressed in email yesterday we did indeed reserve resources to address this - this is now going forward as all contracts are in the database. 

Please see your mapping data - which has now been added to a sheet of the current annotation code list in the database:
https://docs.google.com/spreadsheets/d/1bK2Bzmv87HupuhZnuPopER6hd5XWk2fq4cHHJ7X2R-c/edit#gid=0

For annotation categories that you have requested to be deleted: Do you still need these to be deleted if they contain annotation content. For example: 
general-information				DELETE
local-company-name				DELETE

**Comment by KaitlinCCSI** [comment]
Yes, we asked for those 2 to be deleted, though we could also just hide
them until after the RC re-launch and then re-assess. There shouldn't be
anything under general information, so we didn't know where else to map
this. For local company name - Perrine suggested getting rid of this
category for now because there are a lot of errors in the data on the RC
side. I didn't want to map it to another company name field, though,
because that could result in wrong and misleading information. If "local
company name" could be hidden rather than deleted, however, that might be
useful until RC is able to do a full review of this category after the
launch.

If any new terms/errors need to be mapped that are not covered by our
previous mapping, please contact @samccsi or my colleague Jesse (via email
- will send you her details now), as I'm on my way to Bern so will be
unavailable to work on this until at least Wednesday. Thanks.

On Tuesday, September 29, 2015, Anders <notifications@github.com> wrote:

> Hi @KaitlinCCSI <https://github.com/KaitlinCCSI>,
> As indicated in these conversations we needed to have all OLC contracts
> loaded to the database before we could take on the full data quality
> review. As addressed in email yesterday we did indeed reserve resources to
> address this - this is now going forward as all contracts are in the
> database.
>
> Please see your mapping data - which has now been added to a sheet of the
> current annotation code list in the database:
>
> https://docs.google.com/spreadsheets/d/1bK2Bzmv87HupuhZnuPopER6hd5XWk2fq4cHHJ7X2R-c/edit#gid=0
>
> For annotation categories that you have requested to be deleted: Do you
> still need these to be deleted if they contain annotation content. For
> example:
> general-information DELETE
> local-company-name DELETE
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/402#issuecomment-144098751>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn3IJzL&m=b8132f80286a&t=20150929&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn3IJzL&m=b8132f80286a&t=20150929&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pn3IJzL&m=b8132f80286a&t=20150929&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Can you verify this once more?

**Comment by SamCCSI** [comment]
I checked the search annotations category and the 2 categories don't appear there - is that what you mean?

**Comment by anjesh** [comment]
Yes. I think we could close this now.
