### ISSUE TITLE
For RC.org: Publish all contracts

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#434]
A few hundred contracts have been loaded without being published, thus: 

If contract category = ResourceContracts --> Publish all

**Comment by anjesh** [comment]
@anderspeders 
All the RC contracts are published, there are few contracts that didn't get indexed because there were problems with the signature date (like incomplete dates like 2007-11-00). They weren't indexed. 

Need to go through these contracts and edit dates to make them appear in alpha.rc

* Contrat de Partage de Production Entre La Republique Democratique du Congo Et L'Association South Africa Congo Oil (PTY) Ltd - La Congolaise des Hydrocarbures (Bloc III Du Graben Albertine)
 * I changed the date 2007-11-00 to 2007-11-01 and it's working now. 
* Republique de Guinea Royalty and Production Sharing Agreement between the Republic of Guinea and USOil Corporation
* Mauritania Contrat de Partage de Production Entre La Republique Islamique de Mauritanie et * * International Petroleum Grouping (Block 11)
* Albania Block-2-3 dd20081107 PSC
* Albania Block-A-B PSC
* Albania Block-D-E dd20070731 PSC

**Comment by anderspeders** [comment]
@charlesyoung COuld you lent a hand to review these contracts *signatory date* to a) ensure that each will fit the date format and then b) publish.

**Comment by charlesyoung** [comment]
Feedback:

1. Republique de Guinea Royalty and Production Sharing Agreement between the Republic of Guinea and USOil Corporation -  the contract only mentions 2002 which is why the person captured 2002-00-00

2. Mauritania Contrat de Partage de Production Entre La Republique Islamique de Mauritanie et International Petroleum Grouping (Block 11) - the contract text has been published although a full transcription is still outstanding; no date to make out because OCR too bad and we should block text publishing if still waiting for transcription. 

3. Albania Block-2-3 dd20081107 PSC - date format is correct without me applying changes and can be accessed from RC

4. Albania Block-A-B PSC - date format is correct without me applying changes and can be accessed from RC

5. Albania Block-D-E dd20070731 PSC - date format is correct without me applying changes and can be accessed from RC

**Comment by anjesh** [comment]
All RC contracts republished again.
