### ISSUE TITLE
RC Searching Results

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#458]
I searched for a contract with title 'Platinum Group' (not the full title) through the simple search presented on the RC landing page. The resulting contract is only shown on the last page (5 pages) of the search results with the first 4 pages showing contracts which contain the word 'group'. I would have thought that the search should first identify matching words ('Platinum Group') than single words ('Group').

**Comment by anjesh** [comment]
That is because we sorted the results by year by default as per request from Kaitlin, and 1992 went last. Otherwise the results appear by relevancy as processed by the elasticsearch engine. I think we might need to rethink the default sorting feature. We still need to add the sorting functionality in the list page. 

Just to add to your query, the search supports binary search meaning AND/OR.
By default the search is OR, that means any contract containg Platinum or Group will appear. "Platinum Group" is equivalent to "Platinum OR group". Anding the terms is "Platinum AND Group" and only the contracts containing both words will appear. 

We might need some instruction regarding search somewhere in later sprints. 

cc @anderspeders @byndcivilization

**Comment by KaitlinCCSI** [comment]
I agree rethinking search feature in later sprints would be useful. I had
requested that contracts be sorted on advanced search page by year simply
because there didn't seem to be any rationale behind how contracts were
displayed when you just went to the list of all contracts. But in terms of
returning search results as in Charles's example, agree with Charles that
it would be useful to have the more relevant contracts arise first. I'm not
a search expert, or tech expert, at all, but intuitively it would make
sense to me to have:

AND results returned first
OR results returned second
within each set of results, some way of ordering (perhaps sequentially,
perhaps another way like alphabetically)

Assume @byndcivilization or @jedm might have suggestions on this for moving
forward



On Mon, Oct 5, 2015 at 9:50 AM, Anjesh <notifications@github.com> wrote:

> That is because we sorted the results by year by default as per request
> from Kaitlin, and 1992 went last. Otherwise the results appear by relevancy
> as processed by the elasticsearch engine. I think we might need to rethink
> the default sorting feature. We still need to add the sorting functionality
> in the list page.
>
> Just to add to your query, the search supports binary search meaning
> AND/OR.
> By default the search is OR, that means any contract containg Platinum or
> Group will appear. "Platinum Group" is equivalent to "Platinum OR group".
> Anding the terms is "Platinum AND Group" and only the contracts containing
> both words will appear.
>
> We might need some instruction regarding search somewhere in later
> sprints.
>
> cc @anderspeders <https://github.com/anderspeders> @byndcivilization
> <https://github.com/byndcivilization>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/458#issuecomment-145555083>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpqOehW&m=461673d4ee21&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpqOehW&m=461673d4ee21&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PpqOehW&m=461673d4ee21&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by jedm** [comment]
Would be good to see any instructions given to date re search approach, weighting, what is search and what isn't. (Also raised in #367) 

>>We might need some instruction regarding search somewhere in later sprints.

**Comment by anderspeders** [comment]
+1 on making search results appear by relevancy in elasticsearch engine rather than year. 

Not aware of any weighting, but the search is being made across annotations, text and metadata: 
![image](https://cloud.githubusercontent.com/assets/1101585/10307079/ad0c9a8c-6bf9-11e5-9667-00acae5b7fb3.png)

**Comment by charlesyoung** [comment]
@anderspeders any chance that this update can be done in Sprint #10?

**Comment by charlesyoung** [comment]
@anderspeders any chance that this update can be done in Sprint #11?

**Comment by jedm** [comment]
Whenever we are able to turn to this, there was good thinking by @anderspeders (in his OKF-consultant role) about user needs for search, sort and filtered results back in 2014. Those materials might be a good place to start.

**Comment by KaitlinCCSI** [comment]
Another example of confusing search results is when user uses  " " marks. A search on OLC for *failure to develop* returns 27 contracts, but a search for same phrase bounded by quotation marks, i.e., *"failure to develop"* returns 0. This doesn't seem intuitive. 

![screen shot 2015-12-03 at 9 58 38 am](https://cloud.githubusercontent.com/assets/14825437/11567807/839c2da6-99ae-11e5-9c09-324c95045148.png)

![screen shot 2015-12-03 at 9 58 53 am](https://cloud.githubusercontent.com/assets/14825437/11567805/7dc2e636-99ae-11e5-8c55-1a4a25c93939.png)

**Comment by anjesh** [comment]
Now " works and gives less results when without "

![image](https://cloud.githubusercontent.com/assets/120488/12384499/b0eac81c-bdda-11e5-952c-ef0a7a9d62e3.png)
