### ISSUE TITLE
Question re internal hyperlinks

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#461]
Hi @anderspeders @anjesh 

If I want to include internal links, e.g. hyperlink certain terms in the 'About' text letting users go directly to the FAQ, Home or Search pages, can I include the links as they currently stand or will the links be different once public? E.g. if I use this link http://rc-site-stage.elasticbeanstalk.com/olc/public/  for the Home page, will it work once the site is live?

Many thanks!

**Comment by anjesh** [comment]
Lets use the link alpha.openlandcontracts.org though later we will have openlandcontracts.org, and we can always redirect alpha.openlandcontracts.org to openlandcontracts.org.

Also http://rc-site-stage.elasticbeanstalk.com/olc/public/  doesn't load the css properly because of folder structure. Please use alpha.openlandcontracts.org.

**Comment by JesseCCSI** [comment]
Many thanks @anjesh - so if I use the alpha links for all pages (Home, Advanced Search, About, etc.), can these be redirected for the launch to the public pages? I want to make sure that we don't get any error messages during the demonstration of the site.

**Comment by anjesh** [comment]
What do you mean by public pages? alpha.openlandcontracts.org will not have any problems at all.
I don't know whether domain would be openlandcontracts.org or alpha.openlandcontracts.org for the launch. @byndcivilization should be able to add on this.

**Comment by byndcivilization** [comment]
I think what @JesseCCSI is asking is if links are added, will they manually managed or will links that are alpha. change automatically if and when we move from alpha.olc.org to olc.org. My guess is that the full url is being entered, the links will have to be updated by hand.

**Comment by JesseCCSI** [comment]
Many thanks for clarifying @byndcivilization and apologies for not explaining myself clearly @anjesh - we essentially just need to make sure that the internal links we use now (i.e. alpha.olc.org links) will work once the site goes live

**Comment by KaitlinCCSI** [comment]
@byndcivilization - assume that on Wednesday when we go live, the site will
just be "www.openlandcontracts.org" rather than "
www.alpha.openlandcontracts.org"?

Since Jesse is manually adding some links into the text, can she just drop
the "alpha" and assume that this will be fine and the links won't break?
For example, if she wants to link to "About" page, can she use the link "
http://openlandcontracts.org/about" instead of how we currently access it (
http://alpha.openlandcontracts.org/about), even though the first link does
not currently work?

On Mon, Oct 5, 2015 at 10:19 AM, JesseCCSI <notifications@github.com> wrote:

> Many thanks for clarifying @byndcivilization
> <https://github.com/byndcivilization> and apologies for not explaining
> myself clearly @anjesh <https://github.com/anjesh> - we essentially just
> need to make sure that the internal links we use now (i.e. alpha.olc.org
> links) will work once the site goes live
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/461#issuecomment-145566899>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PprjfAV&m=790131d302ad&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PprjfAV&m=790131d302ad&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PprjfAV&m=790131d302ad&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by byndcivilization** [comment]
Yes we're actually moving things over tomorrow just to make sure we have a smooth wednesday.

That sounds right on links to me. You're hardcoding links so you would just have to re-hard code them tomorrow when we move over. Better just to point them to the future link now.

**Comment by KaitlinCCSI** [comment]
Okay, great. So Jesse will point to the future links for now, and then
we'll check tomorrow to make sure that nothing is broken. Could you please
let us know when things have been moved over tomorrow so we know when we
can start checking the links? Thanks.

On Mon, Oct 5, 2015 at 10:40 AM, Chris Perry <notifications@github.com>
wrote:

> Yes we're actually moving things over tomorrow just to make sure we have a
> smooth wednesday.
>
> That sounds right on links to me. You're hardcoding links so you would
> just have to re-hard code them tomorrow when we move over. Better just to
> point them to the future link now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/461#issuecomment-145574687>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PprEHNI&m=c82b492680aa&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PprEHNI&m=c82b492680aa&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PprEHNI&m=c82b492680aa&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anjesh** [comment]
Closing this. We are good to go once https://github.com/NRGI/resourcecontracts.org/issues/463 is done.
