### ISSUE TITLE
OLC: Tweak to crop and design of image on front page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#479]
As discussed in #203, the image on OLC front page will need some design tweaks. 

@samCCSI @KaitlinCCSI will provide guidance on requested adjustments.

**Comment by byndcivilization** [comment]
just to be clear, as soon as possible this should not be something that falls to @anjesh and YI. Photo assests like the front page photo should be managed in the same way that FAQs and basic content are managed.

**Comment by anderspeders** [comment]
Therefore @anjesh, could you please transfer the admin for the front page to CCSI. In this way CCSI can easily edit the last changes to the image on the front page, which is not acceptable at the moment.

**Comment by anjesh** [comment]
Right now there's some filter applied to the image in the CSS for olc. The image should have the proper dimensions. So you think it's ok to allow the admin to change the front page image directly?

**Comment by SamCCSI** [comment]
Hi Anjesh,

If your team tells us at CCSI exactly what you need, we can arrange for our
designer to deliver that to you. Whatever is easier - we just need to know
what info your team needs.

Many thanks!
Sam

On Tue, Oct 20, 2015 at 9:27 AM, Anjesh <notifications@github.com> wrote:

> Right now there's some filter applied to the image in the CSS for olc. The
> image should have the proper dimensions. So you think it's ok to allow the
> admin to change the front page image directly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/479#issuecomment-149568057>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by KaitlinCCSI** [comment]
And to provide further details - we are fine with how the image is cropped,
but we think it is now too dark. So we will be asking a designer to help us
figure out how to use the picture's original colors while ensuring the
words are legible. Hopefully it will be a simple fix.

On Tue, Oct 20, 2015 at 8:59 AM, SamCCSI <notifications@github.com> wrote:

> Hi Anjesh,
>
> If your team tells us at CCSI exactly what you need, we can arrange for our
> designer to deliver that to you. Whatever is easier - we just need to know
> what info your team needs.
>
> Many thanks!
> Sam
>
> On Tue, Oct 20, 2015 at 9:27 AM, Anjesh <notifications@github.com> wrote:
>
> > Right now there's some filter applied to the image in the CSS for olc.
> The
> > image should have the proper dimensions. So you think it's ok to allow
> the
> > admin to change the front page image directly?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/NRGI/resourcecontracts.org/issues/479#issuecomment-149568057
> >
> > .
> >
>
>
>
> --
>
>
>
> *SAM SZOKE-BURKE*
> *Legal Researcher**Columbia Center on Sustainable Investment*
> Columbia Law School - The Earth Institute, Columbia University
> Level 1, Warren Hall, 410 W116th St. New York, NY 10027
> | (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
> | s.burke@columbia.edu
> | www.ccsi.columbia.edu | @CCSI_Columbia <
> https://twitter.com/CCSI_Columbia>
> | @samszokeburke <http://twitter.com/samszokeburke>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/479#issuecomment-149576343>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PvpWVui&m=1722aa1cc758&t=20151020&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PvpWVui&m=1722aa1cc758&t=20151020&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PvpWVui&m=1722aa1cc758&t=20151020&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by anderspeders** [comment]
@anjesh, 

It would be good to finalise this. 

I see two options: 
1) Either YI provide another round of iterations based on the description from CCSI
2) If not please indicate what CCSI needs to provide (an image with the adjusted tone - for example)?

**Comment by anjesh** [comment]
We will have the option in the CMS admin to upload the front page image.

**Comment by KaitlinCCSI** [comment]
@anjesh What does this mean? I am unclear if you need something from CCSI at this point?

**Comment by anjesh** [comment]
No, we don't need anything from CCSI at this moment. I meant CCSI will be able to upload the frontpage image by yourself. Will let you know when done.

**Comment by KaitlinCCSI** [comment]
Will we also be able to change the color of the home page words? I ask because we are fine with the original picture we sent; it is just now shaded too darkly, which was done to make the words legible. If we don't have the option to also change the home page words, then the ability to upload the frontpage image won't help. (Unless we have the option to remove the words completely, so that we could just superimpose them on the photo that we will upload.)

**Comment by anjesh** [comment]
Changing the homepage words can be tricky as we change the font-size based on the word length so that it fits in different screen sizes. I was under the assumption that CCSI wants to the ability to change the front page image, so that they can tweak the colors/contracts, upload and test. I am not sure if we are to go ahead with this or not now. As for the changing word-colors, that is doable but very specific - meaning the colors of the words for the title text only as i understand These colors codes are all listed in CSS.

**Comment by anderspeders** [comment]
From conversation with @anjesh, 

2-3 revised proposals for lighter image tone will be provided to @SamCCSI @KaitlinCCSI by Wednesday for review. Then selected image will be implemented.

**Comment by anjhero** [comment]
Hi there, 

Here're 3 options on the homepage. 

The first one has just the image with no overlays. The second one has a bit of overlay with 10% opacity. The third option has the image as it is with 80% opacity that bounds only the texts and search box. 
![option i](https://cloud.githubusercontent.com/assets/528549/11396424/6c0beb7e-9399-11e5-8b93-a3899a9ae5b8.png)
![option ii](https://cloud.githubusercontent.com/assets/528549/11396426/6c163016-9399-11e5-81cc-20977ccf228d.png)
![option iii](https://cloud.githubusercontent.com/assets/528549/11396427/6c202cec-9399-11e5-8976-f7755579e7dc.png)

**Comment by anjesh** [comment]
@KaitlinCCSI let us know if you still want some more ideas around the home page image and text around it.

**Comment by KaitlinCCSI** [comment]
Thanks, @anjesh. Could you please provide 2 more mockups:

1. Showing the first option (image with no overlays) with the letters "An online repository of Open Land Contracts" in the same green that is used for the search button?
2. Showing the third option (image as it is with 80% opacity that bounds only the texts and search box) with changes to the spacing of "Open Land Contracts" so that either (a) Open Land Contracts stays on one line or (b) "Open Land" is the same length as "Contracts" (as it is in the left top corner, with the "D" in Land roughly over the "S" in Contracts)

**Comment by anjhero** [comment]
Here they are:

1. Showing the first option (image with no overlays) with the letters "An online repository of Open Land Contracts" in the same green that is used for the search button?
![option iv](https://cloud.githubusercontent.com/assets/528549/11556009/3265ee36-99cc-11e5-8e11-852e436d0676.png)

Its really hard to read the texts in the above option. 

2. Showing the third option (image as it is with 80% opacity that bounds only the texts and search box) with changes to the spacing of "Open Land Contracts" so that either
(a) Open Land Contracts stays on one line or
![option vi](https://cloud.githubusercontent.com/assets/528549/11555936/b9274b28-99cb-11e5-87a4-eb4d4d826a8c.png)

(b)"Open Land" is the same length as "Contracts" (as it is in the left top corner, with the "D" in Land roughly over the "S" in Contracts)
![option v](https://cloud.githubusercontent.com/assets/528549/11555946/c60556b4-99cb-11e5-906a-a0b62dbe528f.png)

**Comment by KaitlinCCSI** [comment]
Thanks, Anjesh. Could you please implement the second image (image as it is with 80% opacity that bounds only the texts and search box with Open Land Contracts on one line)?

**Comment by anjesh** [comment]
This UI to be implemented for OLC only @sweetanzell @sadhakbj 

![option vi](https://cloud.githubusercontent.com/assets/528549/11555936/b9274b28-99cb-11e5-87a4-eb4d4d826a8c.png)

**Comment by anjesh** [comment]
Fixed the image now. http://www.openlandcontracts.org/
Please reopen if you find any issues here.

**Comment by KaitlinCCSI** [comment]
Looks great; thanks.

On Fri, Dec 11, 2015 at 12:19 AM, Anjesh <notifications@github.com> wrote:

> Fixed the image now. http://www.openlandcontracts.org/
> Please reopen if you find any issues here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/479#issuecomment-163853424>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PQ6jcmk&m=1695e486c787&t=20151211&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PQ6jcmk&m=1695e486c787&t=20151211&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PQ6jcmk&m=1695e486c787&t=20151211&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>
