### ISSUE TITLE
Editing/ formatting thumbnails 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#483]
Hi @anderspeders this isn't a priority pre-launch but I noticed that when you add an image to a post (e.g. on http://www.openlandcontracts.org/page/resources) you can't hyperlink from the thumbnail, move the thumbnail easily around the page (so that it appears alongside text rather than solely above/ below, etc). Would be great to have the ability to make these edits. 

Many thanks.

**Comment by anjesh** [comment]
Hi @JesseCCSI you could do that directly from the code (by clicking on code view), but requires some very basic HTML knowledge. For now i have made quick fixes there just to verify that it works.

![image](https://cloud.githubusercontent.com/assets/120488/10328050/4087c810-6ccf-11e5-8bd1-28c33e8cb9f5.png)

**Comment by JesseCCSI** [comment]
Great many thanks @anjesh

**Comment by anderspeders** [comment]
Consider this covered. Closing.

**Comment by SamCCSI** [comment]
Anders, this issue is not ready for closing. We at CCSI don't have html
knowledge, so that would mean that we would need to contact YI every time
we need to add an image or do other formatting, which is not efficient.

Fine for this to not be an immediate priority but I don't think it should
be closed.

On Thu, Oct 8, 2015 at 6:33 PM, Anders <notifications@github.com> wrote:

> Closed #483 <https://github.com/NRGI/resourcecontracts.org/issues/483>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/483#event-430872673>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by KaitlinCCSI** [comment]
Re-opened per Sam's comment

**Comment by JesseCCSI** [comment]
Hi @anderspeders do you know if there is a solution for this yet? Many thanks.

**Comment by anjesh** [comment]
We will need to change the existing editor (or add plugins in the existing one). If there's anything urgent, let us know, otherwise we will have this covered in next sprint.

**Comment by anjesh** [comment]
The editor is changed and now you may add links to the image as well. 

![image](https://cloud.githubusercontent.com/assets/120488/11176522/f0c87e6c-8c65-11e5-9cf2-b1ad11e26263.png)

**Comment by JesseCCSI** [comment]
Many thanks @anjesh - if I remember correctly, with the previous editor you could select a JPEG file to upload. With the new editor, when I click Insert > Insert/edit video, it looks like I don't have the option of selecting a file. What should I be entering in "Source" to insert an image/ video?

**Comment by anjesh** [comment]
You can't upload the files here, you have to upload somewhere and paste link. It's a good practice as well, as the uploaded image might get removed when re-deployed. Does that sound ok to you?

**Comment by JesseCCSI** [comment]
Thanks @anjesh - do we need to use amazon s3 for this, same as for PDFs?

**Comment by mojbenzcar** [comment]
![image](https://cloud.githubusercontent.com/assets/5144570/11274121/48a8ffb2-8eff-11e5-9316-7db4b4ff3162.png)

**Comment by anjesh** [comment]
Ideally it would be good to use S3 and put the link in the editor.
