### ISSUE TITLE
Auto-generate metadata for supporting document based on parent document

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#507]
This is a user request documented by PH-EITI. cc @charlesyoung 

@anjesh: When would it be possible to implement this?

**Comment by charlesyoung** [comment]
linked to 'Associated Documents - Metadata', case #289

**Comment by anjesh** [comment]
We might need to change the flow here for the supporting documents in this case. I am thinking of the following process.

There will be a new link/button called "Add supporting document" in the contract page or there could also be the link in the contract listing page.
Step 1: User clicks on "Add supporting document". 
Step 2: Users will see the parent contract being selected in the list of contracts (if clicked from the "Contract Page"), otherwise user will be able to choose the contract from the list
Step 3: User will upload the supporting document
Step 4: User will be taken to the Contract edit page with all the metadata imported from the parent contract. User will be able to make edits and save to the database. 

We will need to remove the existing supporting documents/parent document option from the contract edit page. They will only be able to unlink these documents from the edit page.

**Comment by charlesyoung** [comment]
Sounds good. Can the list of parent contracts somehow be sorted or searched by country? You don't want a user to have to wade through 600 contracts, and counting, to locate the relevant parent contract.

**Comment by anderspeders** [comment]
Sounds good. 

@charlesyoung We might have time to circle this suggested workflow by PH-EITI if relevant?

**Comment by charlesyoung** [comment]
Will be good but I however do think that all the available time should be spent ensuring that the site is stable and fast before the launch.

**Comment by anjesh** [comment]
There is going to be some major change in the flow to incorporate supporting document functionality. The process and flow is documented clearly here https://github.com/NRGI/resourcecontracts.org/issues/624

This issue can be closed now.
