### ISSUE TITLE
Dealing with spelling differences across languages

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#51]
As a user I need to be able to search terms across contracts presented in multiple languages and spelling methods (US vs. Brittish English). As an example I need search features that incorporate different spellings of "stabilization" so that I can compare stabilization clauses across contracts in US-English, British English and French. 

Suggested solutions: 
A) First option is to define the *tag list* for annotations in one single language across contracts
B) Another solution to this could be fuzzy mathing or a codelist of faceted/grouped terms aross languages.

**Comment by byndcivilization** [comment]
I go for having consistent internal code list for terms with maybe an associated object with language:translation key value pairs.

**Comment by anjesh** [comment]
This is for the free-text search where the user may type "stabilization" or "stabilisation". It doesn't matter what we use internally. ES has fuzzy query and need to do a research and testing and see how this works https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-fuzzy-query.html

**Comment by anjesh** [comment]
We have done some testing on fuzzy matching - which takes care of different language structs like stabilisation and stabilization, mistakes in spellings. 

For e.g. http://rc-site-demo.elasticbeanstalk.com/rc/public/search?q=stabilisation suggests the following words 

![image](https://cloud.githubusercontent.com/assets/120488/11557643/e54be6a0-99d5-11e5-8eff-7740bcaeed10.png)

You may notice there are other variations of stabilisation there - stabilization , stabilisation.t , stabilisatioh , stablisation. They are listed based on the presence of those words in the contracts index, even though they are not correct. However clicking on some of those words might not bring the results because these words are taken from the entire index, rather than the filtered contracts only. 

One thing we will need to do is to have another API which checks whether the contracts are present for each of those listed words, after the filters are applied. We haven't done this, first we want to test how this works. 

We do need to have the proper text when listing those suggested words. 

Thoughts? @anderspeders @byndcivilization

**Comment by KaitlinCCSI** [comment]
Have we progressed with fuzzy matching that addresses spelling mistakes? Similarly, is it possible for search to return results where there is a partial word that matches a full word? (For example, if the user searches only half of a word?) See for example these screenshots:

![screen shot 2016-02-19 at 9 55 00 am](https://cloud.githubusercontent.com/assets/14825437/13180736/4df01f0e-d6ef-11e5-8275-3ebf0a353c74.png)
![screen shot 2016-02-19 at 9 55 23 am](https://cloud.githubusercontent.com/assets/14825437/13180735/4defbe38-d6ef-11e5-9ff1-9439fb7bd03c.png)
![screen shot 2016-02-19 at 9 55 12 am](https://cloud.githubusercontent.com/assets/14825437/13180737/4df0cf3a-d6ef-11e5-8b59-f525a2dbe952.png)

**Comment by anderspeders** [comment]
@anjesh: Could we include a review of the search functionality in sprint 14. Multiple tickets are open but this one would be a good place to start.

**Comment by manishgs** [comment]
We've implemented fuzzy search and deployed in demo. Please review [here](http://rc-site-demo.elasticbeanstalk.com/olc/public/search?q=karutur) once and let us know your feedback.

**Comment by KaitlinCCSI** [comment]
Thanks, @manishgs. It would be great to get feedback from @byndcivilization and @jedm on this. Two initial impressions:
1. I'm not sure how the site decides when to match/not match, but, for example, "Karutu" returns a contract for Karuturi, but "Karut" does not return anything. Is there a good reason for this difference, or is it just that you've manually entered in a few misspellings that you think might be most common? Another example is that if the contract is misspelled as "karaturi" (with an "a" in the middle instead of the "u"), nothing is returned. 
2. The "Similar word" line that now appears before the documents does not look good, because it just shows multiple misspelled words, even when the word you search is spelled correctly. (See screenshot.) Particularly when you search the correct word, this isn't helpful, but even if you search a misspelled word, I don't think it's necessary to show other misspellings (and these are not words anyway). Can this be done more like a google search results, so that (A) if you spell a word "correctly", the similar word line does not show up; (B) if you just misspell a word, it shows a line that says "Showing results for [correct spelling]"? I think the trickier situation is (C) if you type in a word with multiple spellings (stabilization v stabilisation) -- in that situation, perhaps it would be possible for the line to say something like "Also showing results for X" or "Showing results for _stabilization_ and _stabilisation_"?
![screen shot 2016-03-03 at 9 59 17 am](https://cloud.githubusercontent.com/assets/14825437/13500395/ff528ce0-e127-11e5-9a99-d99bc91eca32.png)

**Comment by jedm** [comment]
If others are confident that the similar word list can be curated on the back end to account for multiple languages AND misspellings all in one feature, then I think this is a great solution. It will entail both vigilance and multilingual knowledge or research by all uploaders, however!

And I agree exactly with @KaitlinCCSI suggestion. The "similar word" list is highly useful for back-end and not really useful at all for front-end. It should not be surfaced to users. Instead, a UX like Kaitlin describes should be used.

**Comment by SamCCSI** [comment]
Another example of fuzzy searching:

Searching for "Ivoire" produces zero results on OLC, even though we have a contract tagged as from "Côte d'ivoire"

**Comment by jedm** [comment]
This may relate to [conversation from Issue 367](https://github.com/NRGI/resourcecontracts.org/issues/367#issuecomment-144914674) regarding what text is being searched, annotation titles, summaries, raw text or all three.

**Comment by hello-deepak** [comment]
###  Fuzzy Logic

Elasticsearch fuzzy matching in fulltext search deals with typos and spelling mistakes.
Fuzzy matching treats two words that are “fuzzily” similar as if they were the same word by substitution, insertion, deletion or transposition of character. Here is the [link](https://www.elastic.co/guide/en/elasticsearch/guide/current/fuzziness.html) for detail explanation.

So it find certain word from pdf_text indexed in elasticsearch database which are fuzzily similar and match those words.

### Term and Phrase Suggestion

If the query length is equal to 1 than the word is suggested by [term suggestion](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-term.html) else [phrase suggestion](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-phrase.html) .

We have set fuzzy_prefix_length = 4  cause maximum spelling mistakes occur in the word length greater than 4 , which means if a word length is less than or equal to 4 then the fuzzy logic is not applied.

Examples: 
 http://rc-site-demo.elasticbeanstalk.com/rc/public/search?q=stabilisation

![1](https://cloud.githubusercontent.com/assets/7577697/13807445/44d6eafc-eb89-11e5-9fa5-6d16ba09b3e1.png)

You may notice there are other variations of stabilisation there - stabilization , stabilisation.t , stabilisatioh , stablisation. 

![2](https://cloud.githubusercontent.com/assets/7577697/13807558/c3bcbebe-eb89-11e5-9be1-cb33fa7c98d7.png)

They are listed based on the presence of those words in the contracts index, even though they are not correct. Clicking on those word/phrase shows the exact result by disabling fuzzy matching.

We do not proper text, so the spelling in the suggestion can be wrong .

 The suggested word can be fixed by checking the spelling but still the results are shown with wrong spelling.

#### Other solution :

If the spelling in the query is wrong simply suggest the word/phrase with right word/phrase found in our pdf text without showing the result using fuzzy logic . And when those word/phrase are clicked we can show the result.

**Comment by KaitlinCCSI** [comment]
Can't you show the result using fuzzy logic without showing what the misspelled words are? For example, the second screenshot that shows 148 contracts related to "stabilisation", "stabilization" "stabilisatioh" but without that line that says "Also showing results for: ..."?

**Comment by jedm** [comment]
Agree with @KaitlinCCSI. Same question came up 3 weeks ago in this thread.

**Comment by hello-deepak** [comment]
We will be using https://github.com/NRGI/resourcecontracts.org/issues/932 issue for further discussion.
