### ISSUE TITLE
RC: Add CC-BY-SA license badge and text in footer

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#512]
Ad CC-BY-SA badge on all relevant pags including frontpage

https://licensebuttons.net/l/by-sa/3.0/88x31.png

Text with link: 
[Content is licensed under Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)] link: https://creativecommons.org/licenses/by-sa/4.0/

**Comment by anjesh** [comment]
CC license added in the footer

![image](https://cloud.githubusercontent.com/assets/120488/10533323/5f1ee7bc-73e7-11e5-9d22-4aa1251f9a66.png)

**Comment by jedm** [comment]
This link is currently broken and showing as a typo in the footer. Looks like the exact text provided at the top was pasted verbatim instead of using the brackets to distinguish the text from the link.

To clarify what @anderspeders instructions meant, the code would be:

full text: Content is licensed under Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
linked portion of text: CC BY-SA 4.0
link: https://creativecommons.org/licenses/by-sa/4.0/

(I wonder if it may also relate to the problem in #594.)

**Comment by sadhakbj** [comment]
![512](https://cloud.githubusercontent.com/assets/5828622/10964664/9b171ee4-83d0-11e5-9e53-f3ed2b368493.png)
