### ISSUE TITLE
APIs not working

### ISSUE THREAD

**Issue by giorgiacek** [NRGI/resourcecontracts.org#518]
time outs

**Comment by anjesh** [comment]
Where did you get the timeout?

**Comment by giorgiacek** [comment]
http://rc-elasticsearch.elasticbeanstalk.com/api/contract/999/text

**Comment by anjesh** [comment]
Correct. Please use IP http://54.173.9.19/ for the timebeing. 

We are looking to change the current infrastructure for the API  https://github.com/NRGI/resourcecontracts.org/issues/517

**Comment by anderspeders** [comment]
API seems to be out again. We really need a stable API (as soon as possible or) by Friday so that we can use this during the data dive next week.

@giorgiacek has more details.

**Comment by anjesh** [comment]
http://api.resourcecontracts.org/ is working fine at my end. There's also second one http://rc-elasticsearch-api1.elasticbeanstalk.com/api/ which is different from http://api.resourcecontracts.org/ but both uses the same ES in the backend. ES is now scaled to 4 instances, so this should be stable. 

By API out, what do you mean?

**Comment by byndcivilization** [comment]
Did you do a reindex? Might have been an issue with unlucky timing. or maybe the call happened during the scaling event.
Seems to be working now.

**Comment by giorgiacek** [comment]
It was definitely unlucky timing, it’s working again now.

**Comment by anjesh** [comment]
we did re-indexing last friday and yes the index was changed because there required a remapping of some field. We will make sure that recent index is mentioned everytime it's changed here https://github.com/NRGI/resourcecontracts.org/wiki/Elasticsearch-Usage 

Also we realize that when remapping is required for even one field, use of existing index gives some problems so we delete that one and create a new one. This one doesn't look good though rc_nrgi1

**Comment by anjesh** [comment]
Please reopen if you find issues in api again.
