### ISSUE TITLE
Annotation module

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#519]
1. Open by default on the text doc and not the PDF doc
2. Spell check all categories i.e. Community
3. Different font, size between the English and French categories
4. Page not opened when clicking on the link on the relevant annotation 
5. What is ‘See all Annotations’ suppose to do as it takes you back to the general publishing page? 
6. Searching for 'tax' through RC admin site returns 2 results while searching on the actual contract document returns 3 results
7. What is the difference between the 'By Page' and 'By Category' links?
8. The annotation capture presentation style and fields will need to be looked at although its seems only in November
9. Incorrect page reference with annotation captured for instance from page 3 while the summary notes page 1

**Comment by charlesyoung** [comment]
More details re the the 'By Page' and 'By Category' links. 

Works on the user site:

![image](https://cloud.githubusercontent.com/assets/13888372/10510187/c1812764-7331-11e5-833a-2fed51ad8d08.png)

Not however on the admin site:

![image](https://cloud.githubusercontent.com/assets/13888372/10510204/dd1c51a6-7331-11e5-9fab-c4861b80b170.png)

**Comment by charlesyoung** [comment]
99 annotations captured: http://resourcecontracts.elasticbeanstalk.com/contract/69/annotate

98 annotations shown on the public site: http://alpha.resourcecontracts.org/contract/ocds-591adf-PH4623081838RC/view#/text

**Comment by charlesyoung** [comment]
The actual main document shouldn't be shown as a related doc. 

![image](https://cloud.githubusercontent.com/assets/13888372/10510319/83326e22-7332-11e5-85f3-1afc1b5e79a9.png)

**Comment by charlesyoung** [comment]
On page 16 (text doc) of the contract. Clicking on an annotation link doesn't just not take me to the relevant page but opens page 1 of the PDF doc. This is for all annotation links. 

http://alpha.resourcecontracts.org/contract/ocds-591adf-PH4623081838RC/view#/text

**Comment by anjesh** [comment]
Open by default on the text doc and not the PDF doc
- now it opens pdf by default

Spell check all categories i.e. Community
- there's a separate issue to review all the categories

Different font, size between the English and French categories
- this should be taken care of during localisation implementation. The current design was shared and implemented. 

Page not opened when clicking on the link on the relevant annotation
- fixed

What is ‘See all Annotations’ suppose to do as it takes you back to the general publishing page?
-  "see all" now takes to annotations list in contract summary page where one can see the full annotations in single page

Searching for 'tax' through RC admin site returns 2 results while searching on the actual contract document returns 3 results
- that's because in admin, the query searches in title only. 

What is the difference between the 'By Page' and 'By Category' links?
- to sort the annotations by page and by category.

The annotation capture presentation style and fields will need to be looked at although its seems only in November

Incorrect page reference with annotation captured for instance from page 3 while the summary notes page 1
- fixed.
