### ISSUE TITLE
Bulk download of annotations across Advanced search and the specific contract view

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#552]
User request 1: As a user I would like to be able to download metadata and annotations for a contratcs in XLSX. This would likely be from the *contract view page*.

User request 2: As a user I would like to download annotations from the contracts I have captured in my search. This should be available form *advanced search*.

**Comment by anjesh** [comment]
User request 2 is fixed. The annotations (if annotation-category selected in the search filter) are now part of the csv download. 

User request 1 to be done.

**Comment by sadhakbj** [comment]
Request 1:  Annotation download at Contract View Page has been implemented in demo sub site.  Please check it once on: 
![annotation](https://cloud.githubusercontent.com/assets/5828622/12714451/f5b7940c-c8fc-11e5-9368-1a72b0d794d2.png)

http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-NG5057885784RC/view#

**Comment by KaitlinCCSI** [comment]
1. How does this interact with pinning/comparison feature? cc @jedm 
If we move forward with this, then:
2. This excel doesn't include metadata.
3. What does "annotations type" in column F mean, and is it necessary?
4. What is "Quote" in column C?
5. Is Page Number in column E the page number of PDF? Should probably clarify (i.e., "PDF Page NumbeR"
6. The categories listed in Row 1 should match the frontend terminology (i.e., cluster = topic)
7. As mentioned in another Github ticket, certain symbols are not appearing properly in excel downloads and should be fixed.
8. Useful that excel doc is named after the contract, but (a) would be useful to have "annotations" somewhere in name of document and (b) would put a space or _ between the contract year and the download date, as otherwise the numbers run together and are difficult to understand.

**Comment by anjesh** [comment]
> 1. How does this interact with pinning/comparison feature? cc @jedm
> If we move forward with this, then:
> 2. This excel doesn't include metadata.

Do we want metadata here and mix with the annotations list? Please confirm. 

> 3. What does "annotations type" in column F mean, and is it necessary?

Annotation type is either pdf or text based on where the annotation is done. Since you raised this, this looks redundant now and no use to general audience. 

> 4. What is "Quote" in column C?

Quote is selected text in OCR content only and won't be present in PDF. This can also be removed if you think this is redundant. 

> 5. Is Page Number in column E the page number of PDF? Should probably clarify (i.e., "PDF Page NumbeR"

This could be page number of either text or PDF based on where the annotation is done and in properly done/edited OCR content, it will be the same. Do you think "PDF Page Number" should be the header? Please confirm.

> 6. The categories listed in Row 1 should match the frontend terminology (i.e., cluster = topic)

Correct. It should be topic (as used in the subsite)

> 7. As mentioned in another Github ticket, certain symbols are not appearing properly in excel downloads and should be fixed.

This works with the Libre office in Linux, MS Excel seems to have this problem http://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically We will fix this. 

> 8. Useful that excel doc is named after the contract, but (a) would be useful to have "annotations" somewhere in name of document and (b) would put a space or _ between the contract year and the download date, as otherwise the numbers run together and are difficult to understand.

Sounds good. I would suggest the following name `Annotatations--Contract_name--Download_date.csv` and spaces in the contract name to be replaced with underscore (_).

**Comment by KaitlinCCSI** [comment]
- Metadata - @anderspeders, that was in your user case at top, which is why I had asked. 
- Yes, would delete column F.
- Column C Quote - I think this goes to question of whether everything will be annotated to both text and PDF, or just one or the other, and also whether we are MT-ing Ks before quoting from them. As we are currently proceeding (annotating to 1 or the other, not MTing a lot of Ks), I would suggest removing quote column, but interested in others' thoughts. cc @jedm @SamCCSI 
- Are we ever annotating to improperly edited OCR text? If not, then I think "PDF Page Number" would be appropriate header.
- Name for download doc is fine, except spell as "Annotations".

**Comment by jedm** [comment]
@anderspeders and I worked on a sample download CSV format for the "Clippings" function being spec-ed (function to combine Compare and Pin). 

We should make sure the sample he and I made and the format for this one are the same.

**Comment by sadhakbj** [comment]
Column C and F are deleted , we have changed to PDF Page Number and Cluster to Topic and the CSV file has name as Annotations--Contract_name--DownloadDate.csv (Date consists of Year Month Date Hour Second ) eg. 
```
Annotations--Ethiopia,_Nega_Mamay_Mihret,_Land_Lease_Agreement,_30_September_2011--20160205051358 (1).csv
```

**Comment by jedm** [comment]
Others know better than I do but should commas be omitted from autocreated filenames? @anderspeders @jpmckinney

**Comment by anjesh** [comment]
Correct. This might be standard, but i would suggest replacing all the characters (besides text and numbers) to underscore ie punctuations and spaces.

We will replace all the select (punctuations, space) characters to underscore and if there are two or more underscores in tandem, they will be replaced with one underscore.

**Comment by upasna01** [comment]
This is fixed now. Please review the changes.

**Comment by anderspeders** [comment]
I will be sharing an update on the schema for the download file.

**Comment by jedm** [comment]
Some elements from [February recommendations](https://github.com/NRGI/resourcecontracts.org/issues/552#issuecomment-178641254) still needed in download template.
