### ISSUE TITLE
Add disclaimer for French language for generic language to Mechanical turk

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#553]
DISCLAIMER - IF YOU ARE NOT A FRENCH SPEAKER PLEASE DO NOT COMPLETE TASKS FOR FRENCH LANGUAGE DOCUMENTS. DUE TO ERRORS BY PREVIOUS TRANSCRIBERS, WE ARE NOT IN A POSITION TO PAY FOR TRANSCRIPTIONS OF FRENCH LANGUAGE DOCUMENTS BY NON-FRENCH SPEAKERS.

**Comment by SamCCSI** [comment]
An update on French mechanical turk: We are still not receiving any French MT transcriptions that contain accents.

1 - Has the disclaimer been posted in MT?

2 - @anderspeders any thoughts on other ways forward?

**Comment by anderspeders** [comment]
Not implemented yet. This is assigned for sprint 11 along with several other issues related to the Mech Turk workflow.

**Comment by sadhakbj** [comment]
![disclaimer](https://cloud.githubusercontent.com/assets/5828622/10990406/db16a55a-847a-11e5-8090-8ec08ce0daa0.png) - done

**Comment by anderspeders** [comment]
Thanks, 

@sadhakbj: Can you add the following guidance as well, which does not require to be in capital letters. 

Other instructions to be included: 
1) Original letters and accents should be preserved (for example for French language contracts, the letter/ symbols “œ” and “æ” and the following accents should be transcribed: à ç è é ê ö)
2) Original symbols should be transcribed where possible (for example: ° as used in “N°”, or in coordinates like 53°14’477’’)  
3) For non-transcribed objects such as maps, photos or illegible signatures, please provide a bracketed entry (for example: [map], [photo] or [signature])
4) If you can read the handwritten signature, or any other handwriting, please transcribe it
5) Tables should be transcribed with pipes ( | ) as separators (for example: “Royalties | 10% | 12% | 15%”
6) Please include any typed page numbers or other document references that appear on the page.
7) Please include a single space only between each Article of the contract.

**Comment by SamCCSI** [comment]
Thanks all! Slightly reformated version of instructions to be included is below:

Other instructions for transcribers: 
1) Original letters and accents should be preserved (for example for French language contracts, the letter/ symbols “œ” and “æ” and the following accents should be transcribed: à ç è é ê ö)
2) Original symbols should be transcribed where possible (for example: ° as used in “N°”, or in coordinates like 53°14’477’’)
3) For non-transcribed objects such as maps, photos or illegible signatures, please provide a bracketed entry (for example: [map], [photo] or [signature])
4) If you can read the handwritten signature, or any other handwriting, please transcribe it
5) Tables should be transcribed with pipes ( | ) as separators (for example: “Royalties | 10% | 12% | 15%”)
6) Please include any typed page numbers or other document references that appear on the page.
7) Please include a single space only between each Article of the contract.

**Comment by anderspeders** [comment]
Thanks @SamCCSI, 

This adjustment to the instruction will be made.  

The general French language disclaimer has already been added.

**Comment by SamCCSI** [comment]
Hi all,

I have received a few emails like the below.

Is there a way to indicate to MT transcribers what language the HIT is, so that they don't accept the job if they don't speak the language? Right now it seems that they can't tell until they accept the HIT, and there may be a reason that they cannot rfuse to transcribe once they have accepted it (but of course we don't want to pay for blank pages).

We have been rejecting these because work not done - should we continue to do so?


---------- Forwarded message ----------
From: K Satish <mturk-noreply@amazon.com>
Date: Tue, Nov 17, 2015 at 5:48 AM
Subject: Regarding Amazon Mechanical Turk HIT 3VO4XFFP15A7H8URY0O6EM1ELQB7Q7
To: "RC.org Mechanical Turk" <rc-turk@resourcegovernance.org>


Message from K Satish (k_satish25@rediffmail.com)
---------------------------------
Customer ID: AJ6IIWWL0KF5Q
Dear Requester,

Greetings!

I did not transcribe as the language was neither english nor french.

Please review and do the needful by approving the HIT.

Thanks a lot!
Satish.
---------------------------------

Greetings from Amazon Mechanical Turk,

The message above was sent by an Amazon Mechanical Turk user.
Please review the message and respond to it as you see fit.

Sincerely,
Amazon Mechanical Turk
https://requester.mturk.com

**Comment by manishgs** [comment]
Instructions text has been added in the form. we've also update the form layout before accepting HIT and after HIT accepted. Please confirm by visiting following URL:

After HIT accpeted:
https://task-manish707.rhcloud.com/?pdf=https://rc-demo.s3-us-west-2.amazonaws.com/71/1.pdf&assignmentId=123&hitId=123RVWYBAZW00EXAMPLE&turkSubmitTo=https://www.mturk.com/&workerId=AZ3456EXAMPLE#instructions

Before accepting HIT
https://task-manish707.rhcloud.com/?pdf=https://rc-demo.s3-us-west-2.amazonaws.com/71/1.pdf&assignmentId=ASSIGNMENT_ID_NOT_AVAILABLE&hitId=123RVWYBAZW00EXAMPLE&turkSubmitTo=https://www.mturk.com/&workerId=AZ3456EXAMPLE#instructions

**Comment by anjesh** [comment]
As for the language, it is mentioned in the title when the workers are searching for the Tasks e.g.

![image](https://cloud.githubusercontent.com/assets/120488/11294391/3ebd39a0-8f8b-11e5-9754-f34022aa9798.png)

**Comment by anjesh** [comment]
Superseded by https://github.com/NRGI/resourcecontracts.org/issues/690
