### ISSUE TITLE
Annotation module - linking one annotation to multiple pages

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#562]
Still no way to link one annotation to multiple pages. The annotations column will group multiple annotations listed under the same category, but they still appear as separate annotations.

**Comment by JesseCCSI** [comment]
A related point: when we are annotating a PDF, there doesn't appear to be a way to make the yellow marker extend over text that runs across multiple pages.

**Comment by SamCCSI** [comment]
One idea for how this could work:
add a button to the annotation window asking whether annotator would like to add another page / text selection to that specific annotation. Annotator clicks that button, and then can select more text / add in another PDF reference point. All age refs / text selection refs would then link back to the one annotation.

![screen shot 2015-10-22 at 11 41 15 am](https://cloud.githubusercontent.com/assets/12913915/10670156/3d74a2b2-78b2-11e5-87b7-3e36e49ca270.png)

**Comment by SamCCSI** [comment]
Here is the same screenshot but for PDF annotation (rather than OCR annotation):

![screen shot 2015-10-22 at 11 45 34 am](https://cloud.githubusercontent.com/assets/12913915/10670240/a1199f16-78b2-11e5-8f9d-054e228218bc.png)

**Comment by anjesh** [comment]
One possibility here is to have the same text for these multiple annotations and the system will recognize the same text and show the multiple annotations as a single but referenced in different pages like this one (see Term)
![image](https://cloud.githubusercontent.com/assets/120488/10684428/9cf9bd7a-7912-11e5-825c-aef9884560e3.png)

The one @SamCCSI suggested is something @charlesyoung  and I have discussed in the past. This is something we need to work out in details to avoid big change in the existing annotation module.

**Comment by JesseCCSI** [comment]
Thanks @anjesh. Re this: 

"A related point: when we are annotating a PDF, there doesn't appear to be a way to make the yellow marker extend over text that runs across multiple pages." 

How do we make the yellow rectangle extend across more than one page?

**Comment by anjesh** [comment]
I am afraid that can't be done with the existing annotation module we are using. Because of that feature lacking, we are not doing pdf-scroll like text-scroll (which was also used to be page-wise display for the texts). I think we should be able to extend the yellow box within the page only and not across, with the existing modules we are using. 

cc @byndcivilization

**Comment by JesseCCSI** [comment]
Hi @anjesh 

Re attaching annotations to multiple page numbers, your suggestion worked when I tested it ("One possibility here is to have the same text for these multiple annotations and the system will recognize the same text and show the multiple annotations as a single but referenced in different pages"). 

However this does increase the time it takes for annotators to complete annotations. Sam's suggestion of adding a button to the annotation window might streamline the process - do you think this functionality could be added to the annotation module? 

Also, is there a better way (visually) of presenting the page numbers in the annotation column rather than just having "Page 13, 16, 28" etc. (as in the example below)? This format may be confusing for the user, particularly where there are many articles and page numbers listed. 

Many thanks! 

![screen shot 2015-10-28 at 21 05 21](https://cloud.githubusercontent.com/assets/14910764/10807636/1914a600-7db8-11e5-9a57-3763549ef1d3.png)

**Comment by JesseCCSI** [comment]
Through correcting annotations today, I realized the following: 

1. If an annotation is entered several times because it appears on multiple pages (and we've included it several times in order to link to each relevant page), in order to correct any errors, you have to correct each annotation. 
2. For example, the "Date-contract signature" field for a particular contract was incorrect and linked to multiple pages - I had to edit the annotation attached to each separate page associated with the "Date-contract signature" field in order for the correction to become effective. 

This is another good reason to come up with an alternative solution for linking annotations to multiple pages - entering and re-entering (in the case of errors by annotators) seems inefficient. 

Many thanks.

**Comment by anjesh** [comment]
Superseded by https://github.com/NRGI/resourcecontracts.org/issues/694
