### ISSUE TITLE
Annotation module - attaching annotations to corresponding OCR text and PDF 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#571]
When you annotate a contract by attaching annotations to the PDF, the annotation does not appear to attach to the corresponding OCR text (and the relevant OCR text is not highlighted). So if a user is reading the annotations alongside the OCR text, and clicks on e.g. Page 2 under an annotation in the left hand column, this will take them to the relevant PDF page, not the relevant OCR text. 

The vice versa is also true - if you annotate OCR text, clicking on the annotation page number takes you to the OCR text even if you are reading the PDF. 

Many thanks.

@KaitlinCCSI @samCCSI

**Comment by JesseCCSI** [comment]
A couple of points to clarify the above: 

1. We'd like the links to be "3-way", i.e. links between the annotations, the OCR text, and the PDF. 
2. When a user clicks on a PDF annotation topic while in PDF view, ideally the contract would auto-scroll to where the annotation is located on the PDF. When the user switches to text view, this view should also automatically scroll to the specific part of the text that is relevant to the annotation topic. 

cc @KaitlinCCSI @samCCSI @jedm

**Comment by anjesh** [comment]
OCR text and pdf are different entities and there's no relation between the two except for the page number. Ideally all the annotations should have been done in the OCR text as per my original discussion. However we enabled PDF annotations to accommodate the previous resourcecontracts annotations. 

>  So if a user is reading the annotations alongside the OCR text, and clicks on e.g. Page 2 under an annotation in the left hand column, this will take them to the relevant PDF page, not the relevant OCR text.

That is because that particular annotation is done in the PDF. In Pdf annotation position is calculated from the top left and stored as numbers. Whereas in Text, annotation is the stored as [xpath](https://en.wikipedia.org/wiki/XPath). These two could in no way be linked. In fact when the text is edited, the position of annotation might change because xpath position gets shifted. 

> When a user clicks on a PDF annotation topic while in PDF view, ideally the contract would auto-scroll to where the annotation is located on the PDF. When the user switches to text view, this view should also automatically scroll to the specific part of the text that is relevant to the annotation topic.

First thing we are trying to do is to popup the annotation in the pdf view when the annotation is clicked on the left bar. But we won't be able to move the text to the exact position in text-view (if it's pdf annotation), except for taking to that specific page where the annotation is done in pdf. 

I think we need some discussion around here on how do we want the annotations to behave. Perhaps develop some step-by-step user stories. 

@anderspeders

**Comment by jedm** [comment]
Hi, @anjesh. The desired "3-way" behavior was broken down in #389 . The primary user story is simply that as a government, civil society or other reader (e.g., researcher, journalist) I want to know the location AND the contents of a contract term so that I can better understand the meaning of the contract through reference to the original text by knowing the term's location in the original signed document.

**Comment by KaitlinCCSI** [comment]
And to add to Jed's comment, annotations and their links to original
contracts are one of the most valuable features for all of the identified
user profiles, as the annotations help users understand the contract, but
the link between the annotations and the contract is crucial for a user's
ability to check and locate the original language.

On Fri, Oct 23, 2015 at 5:08 AM, jedm <notifications@github.com> wrote:

> Hi, @anjesh <https://github.com/anjesh>. The desired "3-way" behavior was
> broken down in #389
> <https://github.com/NRGI/resourcecontracts.org/issues/389> . The primary
> user story is simply that as a government, civil society or other reader
> (e.g., researcher, journalist) I want to know the location AND the contents
> of a contract term so that I can better understand the meaning of the
> contract through reference to the original text by knowing the term's
> location in the original signed document.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/571#issuecomment-150534609>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pwy8Cjm&m=5a1b46c8dd94&t=20151023&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pwy8Cjm&m=5a1b46c8dd94&t=20151023&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Pwy8Cjm&m=5a1b46c8dd94&t=20151023&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by upasna01** [comment]
Annotations and contracts are linked at present. So, I think this issue can be closed.
