### ISSUE TITLE
Liberia Tarpeh Timber Corp > annotations mapping to non-existent page 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#572]
The "Signatories, state" and "Signatories, company" fields are mapping to page 38/37. They should map to page 37. I tried changing this through the annotation content editing module, but was unable to do so (as the yellow placemarkers for these annotation categories don't show up). 

http://www.openlandcontracts.org/contract/ocds-591adf-LR2308129439OL/view#/pdf/page/38/annotation/25019

![screen shot 2015-10-22 at 12 10 27](https://cloud.githubusercontent.com/assets/14910764/10670985/33fab4de-78b6-11e5-9054-30986064e537.png)

**Comment by SamCCSI** [comment]
A related need:

As an annotator I need to be able to edit page numbers of previously entered annotations (both for text annotations and PDF annotations).

**Comment by anjesh** [comment]
@JesseCCSI This might have been because annotation was imported from excel and pdf might have been changed/replaced from the original one. For now we can fix this directly from the backend. Shall we?

> As an annotator I need to be able to edit page numbers of previously entered annotations (both for text annotations and PDF annotations).

Editing page number for text annotation is not possible because of the way annotation is stored for text (as xpath). But this is something that could be done in pdf. Commented here https://github.com/NRGI/resourcecontracts.org/issues/573#issuecomment-150460629

**Comment by JesseCCSI** [comment]
Please do @anjesh thanks. Have commented re editing page numbers in #573

**Comment by JesseCCSI** [comment]
The specific issue re the Tarpeh contract has been fixed, but Sam's comment (included below) is still relevant re the issues discussed in #573

**Comment by anjesh** [comment]
Fixed the page number of the contract. 
There's separate issue for Editing of the page number https://github.com/NRGI/resourcecontracts.org/issues/573. Closing this.
