### ISSUE TITLE
Annotation links to PDF not intuitive (particularly when annotation at bottom of page)

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#584]
When you click on an annotation field, it takes you to the correct page of the contract where the content annotated can be found (when working correctly). However, when the page pulls up, all you see are the yellow boxes, with no information unless you hover over the box. This is confusing when there are multiple yellow boxes on the page, as a user has to then hover over each yellow box to find the relevant one. It is particularly confusing when the relevant box is at the bottom of the page, and thus can't be seen in the screen unless scrolling the page down. 

Would be useful to address this somehow, possibly by having the relevant yellow box pop the information up automatically without having to hover over it? This may have been addressed in another ticket; not sure.

![screen shot 2015-10-24 at 8 51 44 pm](https://cloud.githubusercontent.com/assets/14825437/10713679/079d399c-7a92-11e5-988f-2cec0bf4907e.png)

**Comment by jedm** [comment]
Yes this is mentioned as item "5" in #389 from 25 September.

**Comment by JesseCCSI** [comment]
Hi @anjesh this is linked to #573 - if we had the ability to move the yellow boxes around the page, we could place them more accurately (beside the relevant provision, rather than at the top/ bottom/ middle of the page). 

cc @KaitlinCCSI

**Comment by sadhakbj** [comment]
- It's fixed now.

![584 issue](https://cloud.githubusercontent.com/assets/5828622/12838508/1ca5a1ec-cbf7-11e5-857a-05ce6ad49666.png)

**Comment by JesseCCSI** [comment]
Thanks @sadhakbj 

We noticed today that sometimes the pop ups don't appear. We were looking at this contract http://www.resourcecontracts.org/contract/ocds-591adf-PH7733849609RC/view#/pdf/page/10/annotation/26427

In some cases, the pop ups appeared on every page. However, we noticed that if we clicked outside of one of the annotation boxes (i.e. anywhere else on the contract page), the pop ups disappeared and did not re-appear when we hovered over or clicked on the relevant annotation box (or they re-appeared after 30 seconds or so). This problem seems to occur intermittently.  

Both @KaitlinCCSI and I experienced this problem (using Chrome)
