### ISSUE TITLE
Sidebar searching

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#609]
Should we not replicate the Philippines sidebar searching methodology of using a drop-down list for resources, countries and years? The current method is cumbersome because if I want to find all contracts relating to Philippines I have to click on 'View all', scroll down to the Philippines flag and then click on the flag. Seems like too many clicks. 

![image](https://cloud.githubusercontent.com/assets/13888372/10787018/8ba3618a-7d76-11e5-9c70-109c94df4aaa.png)

**Comment by anjesh** [comment]
This doesn't seem good from UI perspective and not sure if the use case is strong enough. Would like to hear others' thoughts.

**Comment by KaitlinCCSI** [comment]
Not sure about this suggestion, as there is something nice about having at least some things listed out rather than another dropdown. But if it is too many steps to find a specific country, could the "View all" instead function to expand the full list within the left sidebar, rather than taking user to another page?

(A bigger problem is that the existence of this left sidebar is still not obvious, and I suspect many users don't even know it is there. This should be one of the items that will be addressed in efforts to improve pathways from home page.)

**Comment by anjesh** [comment]
Closing this one as https://github.com/NRGI/resourcecontracts.org/issues/862 addresses the sidebar.
