### ISSUE TITLE
Can't open contracts on mobile phones

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#625]
In contract view page on mobile phone, I can only see annotations. Clicking on "TEXT" or "PDF" doesn't do anything (except it makes the page numbers listed to right of box move slightly), and I can't find any way of actually opening up a contract document.

![img_1666](https://cloud.githubusercontent.com/assets/14825437/10913384/3863d0f8-8213-11e5-8552-b180b05bf98d.PNG)

**Comment by JesseCCSI** [comment]
We noticed today that the contract appears at the bottom of the contract view page on mobile devices - however, this is likely to be missed by the user (not so intuitive that the user would have to scroll past the long list of annotations to see the contract), and it's difficult to scroll to both the contract and the metadata. Also noted the following issues: 

1. You can't zoom in or out on the contract;
2. Once you scroll down to the contract view box, it's cumbersome for the user to scroll back up (they have to do this by scrolling in the space to the left or right of the contract, which is very narrow - if they scroll on the contract itself, the page of the contract just moves around). [see screenshot]
3. On both the contract view and summary pages, the name of the contract is cut off. 
4. On the summary page, nothing happens when you click on "View All Annotations" in the annotations category box.  
5. To view different contract pages, you have to use the arrows at the top of the page, which again means you need to scroll back up to the top to change pages, and then back down to the contract to actually view the page. This could be resolved by keeping the page number box and arrows beside the contract, or changing the order in which different sections appear on the contract page (e.g. Contract > Annotations> Metadata). If we opt for changing the order, we still need to address the other issues so that users don't miss the annotations. A third option might be to have the contract annotations, etc. scroll underneath the Text/PDF/Search/ page number arrows (currently, when you scroll down the page, these disappear). 

![image](https://cloud.githubusercontent.com/assets/14910764/10956469/02d299ac-832a-11e5-9321-987477fc9470.png)

![image](https://cloud.githubusercontent.com/assets/14910764/10956472/0a4ac088-832a-11e5-8085-c27752b68f17.png)

**Comment by anjesh** [comment]
Closing this. Will be taken care by https://github.com/NRGI/resourcecontracts.org/issues/689
