### ISSUE TITLE
Mech turk: Could not be approved?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#626]
![image](https://cloud.githubusercontent.com/assets/1101585/10918398/6db5fd92-8233-11e5-9b47-eb41638ba44e.png)

I regularly encounter issues where I cannot approve a task. 

There is money in the acount. What is the hold up here?

**Comment by anderspeders** [comment]
Checked this with @byndcivilization who is unable to approve as well. 

@anjesh please follow up

**Comment by anderspeders** [comment]
I have checked more or less all pages for this contract http://resourcecontracts.elasticbeanstalk.com/mturk/1188/ and none of them can be approved. All shows red error. 

This is urgent to get fixed as we have 600 pages awaiting approval in mechanical turk.

**Comment by anjesh** [comment]
We see that these assignments have already been approved in the system when the assignments are pulled from the Mturk API and our database doesn't have approved flag on as it's not being approved by the user from the system. It's kind of strange - not sure how this is happening. There are still other assignments that are approved when pulled from Mturk but the action is not taken in the system. We should know that because if the action is taken in the system, the approve-flag gets on. 

We will set all the assignments which have already been approved (but not reflected in the system) to approved. We are not sure how this is happening, we see that there's maximum number of days of 30 when the assignments get auto-approved if the requester doesn't take any action. We could change this default limit - which we haven't done anything as of now. 

There's not much amount left in Mturk account - around 2$ only, as the amount gets allocated once the tasks get created. Now we won't be able to create any HIT tasks for new contracts. 

We are trying to see if we could log more info to find the abnormal behaviour.

**Comment by anderspeders** [comment]
Here is another example of a task that cannot get approved: 
http://resourcecontracts.elasticbeanstalk.com/mturk/1191/1417

The issue seems to be completely systemic.

**Comment by anjesh** [comment]
We have set the approved flag of all the tasks which have been already approved when the API call was made to pull the assignment (task result from the worker).

**Comment by SamCCSI** [comment]
More examples of this problem encountered today - nb: it doesn't affect every page in the contract. Some were able to be approved, some were not.

http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3571

![image](https://cloud.githubusercontent.com/assets/12913915/11132978/23a37114-8961-11e5-9f45-349bd7612346.png)

**Comment by SamCCSI** [comment]
Please see the links below. These could not be approved:

http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3571
http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3547
http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3550
http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3552
http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3564
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3620
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3623
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3624
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3626
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3627
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3632
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3633
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3643
http://resourcecontracts.elasticbeanstalk.com/mturk/682/3651

**Comment by SamCCSI** [comment]
http://resourcecontracts.elasticbeanstalk.com/mturk/1344/3438

http://resourcecontracts.elasticbeanstalk.com/mturk/1278/3356

http://resourcecontracts.elasticbeanstalk.com/mturk/1236/2025

http://resourcecontracts.elasticbeanstalk.com/mturk/1233/2567

http://resourcecontracts.elasticbeanstalk.com/mturk/1233/2572

http://resourcecontracts.elasticbeanstalk.com/mturk/1189/1459

http://resourcecontracts.elasticbeanstalk.com/mturk/1189/1462

http://resourcecontracts.elasticbeanstalk.com/mturk/1189/1465

http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3571

http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3547

http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3550

http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3552

http://resourcecontracts.elasticbeanstalk.com/mturk/1167/3564

http://resourcecontracts.elasticbeanstalk.com/mturk/187/295

http://resourcecontracts.elasticbeanstalk.com/mturk/185/311

http://resourcecontracts.elasticbeanstalk.com/mturk/185/304

http://resourcecontracts.elasticbeanstalk.com/mturk/185/304

http://resourcecontracts.elasticbeanstalk.com/mturk/185/307

http://resourcecontracts.elasticbeanstalk.com/mturk/184/276

http://resourcecontracts.elasticbeanstalk.com/mturk/161/254

http://resourcecontracts.elasticbeanstalk.com/mturk/161/260

http://resourcecontracts.elasticbeanstalk.com/mturk/161/262

http://resourcecontracts.elasticbeanstalk.com/mturk/161/263

http://resourcecontracts.elasticbeanstalk.com/mturk/161/264

http://resourcecontracts.elasticbeanstalk.com/mturk/161/265

http://resourcecontracts.elasticbeanstalk.com/mturk/161/266

http://resourcecontracts.elasticbeanstalk.com/mturk/161/267

http://resourcecontracts.elasticbeanstalk.com/mturk/161/255

http://resourcecontracts.elasticbeanstalk.com/mturk/161/256

http://resourcecontracts.elasticbeanstalk.com/mturk/161/257

http://resourcecontracts.elasticbeanstalk.com/mturk/161/258

http://resourcecontracts.elasticbeanstalk.com/mturk/161/259

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3620

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3623

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3624

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3626

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3627

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3632

Please see the links below. These could not be approved. 

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3633

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3638

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3643

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3651

http://resourcecontracts.elasticbeanstalk.com/mturk/682/3575

**Comment by SamCCSI** [comment]
Previous comment updated.

**Comment by anjesh** [comment]
We see that the HITs are already approved when the API pulls the info from Mturk. We have set the above HITs as approved manually. Similarly some of these HITs are deleted from Mturk. We are not sure how this is happening. We will be now logging all the API response https://github.com/NRGI/resourcecontracts.org/issues/672 so that we know what's happening. Right now we don't have a clue how this happening. 

This can be closed now. We should have more info later when such event occurs.

**Comment by SamCCSI** [comment]
Hi @anjesh I'm adding additional pages that could not be approved - please let me know if I should add them to issue 672 instead?

http://resourcecontracts.elasticbeanstalk.com/mturk/679/3703
http://resourcecontracts.elasticbeanstalk.com/mturk/679/3705
http://resourcecontracts.elasticbeanstalk.com/mturk/679/3710
http://resourcecontracts.elasticbeanstalk.com/mturk/679/3712
http://resourcecontracts.elasticbeanstalk.com/mturk/679/3715
http://resourcecontracts.elasticbeanstalk.com/mturk/1179/3683
http://resourcecontracts.elasticbeanstalk.com/mturk/1179/3689
http://resourcecontracts.elasticbeanstalk.com/mturk/1179/3690
http://resourcecontracts.elasticbeanstalk.com/mturk/1164/4536
http://resourcecontracts.elasticbeanstalk.com/mturk/1164/4537
http://resourcecontracts.elasticbeanstalk.com/mturk/1153/3372
http://resourcecontracts.elasticbeanstalk.com/mturk/1160/3481
http://resourcecontracts.elasticbeanstalk.com/mturk/108/51
http://resourcecontracts.elasticbeanstalk.com/mturk/1179/3683
http://resourcecontracts.elasticbeanstalk.com/mturk/1179/3689
http://resourcecontracts.elasticbeanstalk.com/mturk/1179/3690
http://resourcecontracts.elasticbeanstalk.com/mturk/1164/4536
http://resourcecontracts.elasticbeanstalk.com/mturk/1164/4537
http://resourcecontracts.elasticbeanstalk.com/mturk/1153/3372
http://resourcecontracts.elasticbeanstalk.com/mturk/1160/3481

**Comment by SamCCSI** [comment]
More pages that could not be approved:

http://resourcecontracts.elasticbeanstalk.com/mturk/1267/2893
http://resourcecontracts.elasticbeanstalk.com/mturk/1267/2899
http://resourcecontracts.elasticbeanstalk.com/mturk/1213/1361
http://resourcecontracts.elasticbeanstalk.com/mturk/1213/1364
http://resourcecontracts.elasticbeanstalk.com/mturk/1213/1366
http://resourcecontracts.elasticbeanstalk.com/mturk/1213/1370
http://resourcecontracts.elasticbeanstalk.com/mturk/1075/1068
http://resourcecontracts.elasticbeanstalk.com/mturk/1075/1083
http://resourcecontracts.elasticbeanstalk.com/mturk/1075/1054
http://resourcecontracts.elasticbeanstalk.com/mturk/1075/1060
http://resourcecontracts.elasticbeanstalk.com/mturk/1075/1076
http://resourcecontracts.elasticbeanstalk.com/mturk/1075/1078
http://resourcecontracts.elasticbeanstalk.com/mturk/1075/1081
http://resourcecontracts.elasticbeanstalk.com/mturk/187/295

**Comment by SamCCSI** [comment]
More links to pages "unable to approve":
http://resourcecontracts.elasticbeanstalk.com/mturk/1278/3281
http://resourcecontracts.elasticbeanstalk.com/mturk/1192/1263 (was able to approve by clicking approve all)

**Comment by SamCCSI** [comment]
More links to pages "unable to approve":
http://resourcecontracts.elasticbeanstalk.com/mturk/1156/4852
http://resourcecontracts.elasticbeanstalk.com/mturk/1156/4853

**Comment by SamCCSI** [comment]
More links to pages "unable to approve":

http://resourcecontracts.elasticbeanstalk.com/mturk/1575?status=1&approved=0
http://resourcecontracts.elasticbeanstalk.com/mturk/1572?status=1&approved=0
http://resourcecontracts.elasticbeanstalk.com/mturk/1568?status=1&approved=0
http://resourcecontracts.elasticbeanstalk.com/mturk/1566?status=1&approved=0
http://resourcecontracts.elasticbeanstalk.com/mturk/1565?status=1&approved=0
http://resourcecontracts.elasticbeanstalk.com/mturk/1399?status=1&approved=0
http://resourcecontracts.elasticbeanstalk.com/mturk/1512?status=1&approved=0

Cant reject p37:
http://resourcecontracts.elasticbeanstalk.com/mturk/1512?status=1&approved=0

As you can see we are still regularly encountering this error, so I'm not sure that spot fixes are sufficient. @anderspeders @anjesh any thoughts?

**Comment by KaitlinCCSI** [comment]
Reopened to address Sam's comment/question above.

**Comment by anjesh** [comment]
It appears that these assignments are approved by Mturk as no action was taken in a month after submission of the assignment, as can be seen for one such assignment below. 

![image](https://cloud.githubusercontent.com/assets/120488/13343537/933e2138-dc75-11e5-944e-e8b376194c81.png)

As per discussion with Anders, we will approve these assignments (which are auto approved by the system due to inaction) so that the contract process could be moved ahead.

**Comment by SamCCSI** [comment]
There are still some MT entries that haven't been auto approved, and some rejections that haven't been automatically reset. 

I was not able to approve this:
http://resourcecontracts.elasticbeanstalk.com/mturk/1278/3281

Also, I cannot reject the pages on this URL:
http://resourcecontracts.elasticbeanstalk.com/mturk/161?status=1&approved=0

**Comment by anderspeders** [comment]
Thanks - @manishgs please review

**Comment by manishgs** [comment]
Now system handles HIT that auto approved by MTurk due to no action was taken for 30 days after assignment submitted by the worker. 

If user approve HIT, the HIT status updated to `Approved` and following message will be shown.

`HIT already approved on Mechanical Turk since no action was taken for 30 days after assignment submission.`

If user reject HIT, the HIT status updated to `Approved` and following message will be shown:

`HIT already approved on Mechanical Turk since no action was taken for 30 days after assignment submission. Click here to reset HIT`

There is an optional link in message to reset the HIT.
