### ISSUE TITLE
Menu bar icon (homepage)

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#631]
Is it possible to make this icon larger/ clearer? Users may be confused on where to go next when they land on the homepage (possibly leading to a higher bounce rate than we might hope for). Perhaps there are some suggestions on how to improve the icon generally? 

cc @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
This is linked to #524. Among other issues with current icon, it does not intuitively indicate what it does -- I originally assumed it was a menu that shows different pages on the site, rather than a way to find a list of categories of contracts.

This is particularly important as it currently is the only way to get to the "all contracts" page as well.

**Comment by anjesh** [comment]
Addressed here https://github.com/NRGI/resourcecontracts.org/issues/862
