### ISSUE TITLE
Change how OpenLandContracts (and possibly RC) appears in search engines

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#633]
When you search "Resource Contracts" in a search engine, the return shows the site as "Resource Contracts". When you search "Open Land Contracts", the return shows the site as "OPENLAND Contracts". Can you please rename OLC site for search engine purposes so that it shows up as "OpenLandContracts.org"? 

Not sure if @anderspeders or others would also like Resource Contracts to show up as "ResourceContracts.org" rather than "Resource Contracts"?

**Comment by KaitlinCCSI** [comment]
Screenshots attached

![screen shot 2015-11-05 at 4 47 51 am](https://cloud.githubusercontent.com/assets/14825437/10966473/68660f5c-8379-11e5-84b1-adb6da1a35b5.png)
![screen shot 2015-11-05 at 4 47 38 am](https://cloud.githubusercontent.com/assets/14825437/10966474/686796d8-8379-11e5-9b86-595e7f949717.png)

**Comment by anjesh** [comment]
We will create sitemap for both RC and OLC for fix this issue and this needs to be submitted to goggle indexing https://support.google.com/webmasters/answer/183668?hl=en&ref_topic=4581190#sitemapformat

**Comment by anjesh** [comment]
The following titles/descriptions are to be updated in the meta headers in the pages so that the search engine shows the text accordingly. 

For OLC Index page,
Title: OpenLandContracts.org
Description: OpenLandContracts.org is an online repository of publicly available contracts for large-scale land, agriculture, and forestry projects. The repository includes the full text of contracts; plain language summaries of each contract’s key social, environmental, human rights, fiscal, and operational terms; and tools for searching and comparing contracts. 

About page:
Title: OpenLandContracts.org - About
Description: OpenLandContracts.org is an online repository of publicly available contracts for large-scale land, agriculture, and forestry projects. The repository includes the full text of contracts; plain language summaries of each contract’s key social, environmental, human rights, fiscal, and operational terms; and tools for searching and comparing contracts. 

FAQs page:
Title: OpenLandContracts.org - FAQs
Description: Frequently Asked Questions about OpenLandContracts.org. 

Resources
Title: OpenLandContracts.org - FAQs
Description: See different guides and documents to learn more about the contracts. 

Glossory
Title: OpenLandContracts.org - Glossory
Description: A number of key terms are critical for conducting contract analysis. OpenLandContracts.org provides a growing glossary that can help you navigate the language of the contracts.

Publish Contracts
Title: OpenLandContracts.org - Publish Contracts
Description: Learn more about how the OpenLandContracts.org team can support host governments, investors, and other relevant stakeholders in their efforts to disclose contracts.

Contact
Title: OpenLandContracts.org - Contact
Description: Please send your questions, comments, and feedback by email at info@openlandcontracts.org

API
Title: OpenLandContracts.org - API
Description: Learn more about how to use API to build your own applications. 

Country
Title: OpenLandContracts.org - Country
Description: See and search OpenLandContracts from different countries - Cambodia, Cameroon, Ethiopia, Liberia... (can this list be auto-generated) 

Resource
Title: OpenLandContracts.org - Resource
Description: See and search OpenLandContracts in different resources - Acaria, Coffee, Cotton, Biofuels (can this list be auto-generated) 

Search and contract listing page
Title: OpenLandContracts.org - Search Contracts
Description: Search OpenLandContracts using different criteria - year signed, company name, contract type, annotation category.


The same goes for ResourceContracts
Replace all the instances of OpenLandContracts with ResourceContracts 

Title: ResourceContracts.org

**Comment by anderspeders** [comment]
@KaitlinCCSI @samCCSI can you confirm the language above?

If not, please provide full text for any corrections.

**Comment by sadhakbj** [comment]
We have updated the information and the following result is displayed now:

For OLC:
![olc_google](https://cloud.githubusercontent.com/assets/5828622/13067722/a72d57f4-d49b-11e5-9293-943c38a40659.png)

For RC:
![rc_google](https://cloud.githubusercontent.com/assets/5828622/13067731/ce5d6e5e-d49b-11e5-909e-88c77c93181a.png)

**Comment by SamCCSI** [comment]
Apologies for the slow reply. Our proposed language for each is attached.

One question for @jedm @byndcivilization @anderspeders: will including "OpenLandContracts.org" at the beginning of each title ever lead to the title being cut off as it is in this screenshot for RC
[For OLC Index page.docx](https://github.com/NRGI/resourcecontracts.org/files/133390/For.OLC.Index.page.docx)
:
![image](https://cloud.githubusercontent.com/assets/12913915/13094005/370c90bc-d4d6-11e5-9c99-07c1f10eeeb1.png)

**Comment by KaitlinCCSI** [comment]
Re-opened to address Sam's proposed language above. Didn't realize this would be implemented before we responded (though apologies for slow response).

**Comment by sadhakbj** [comment]
The changes has been updated. Google will take some time to update the details. Closing for now.

**Comment by SamCCSI** [comment]
Google does not seem to be presenting the pages as we had planned. Is there anything further we can work on for this?

Here is how RC displays on google:
![image](https://cloud.githubusercontent.com/assets/12913915/13652626/37b2ece0-e61b-11e5-8a28-0070dea234e0.png)

Here is how OLC displays on google:
![image](https://cloud.githubusercontent.com/assets/12913915/13652612/1899b140-e61b-11e5-857f-be0a6e27046a.png)

cc @KaitlinCCSI

**Comment by KaitlinCCSI** [comment]
Re-opening until we can confirm that we've made all changes necessary, in light of Sam's comment.

**Comment by manishgs** [comment]
@SamCCSI @KaitlinCCSI 

> Google does not seem to be presenting the pages as we had planned. Is there anything further we can work on for this?
The pages or Sitelinks are automatically generated by google. You can only demote page If you don't want a page to appear as a sitelink. 

Here is the link for the webmasters tool. https://www.google.com/webmasters/tools/sitelinks?hl=en&authuser=0&siteUrl=http://resourcecontracts.org/

You need to have the permission on webmasters. Let me if you need permission or any help.

**Comment by manishgs** [comment]
@SamCCSI  
Closing this issue. Please create new issue if you have any issue related to google indexing.
