### ISSUE TITLE
Missing contracts on the RC public site

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#647]
1. Cambodia
Three contracts published but none on the RC public site

2. Albania
Twelve contracts published but only ten on the RC public site 

3. Azerbaijan 
Six contracts published but only five on the RC public site

4. Cameroon
Nine contracts published but only seven on the RC public site

5. China
Sixteen contracts published but only ten on the RC public site

6. Ethiopia
Twenty contracts published but none on the RC public site

7. Russia
Three contracts published but none on the RC public site

8. South Sudan
One contract published but none on the RC public site

9. Ukraine 
Two contracts published but none on the RC public site

10. etc

**Comment by KaitlinCCSI** [comment]
Charles, some but not all of the missing contracts are missing because they
only appear on OLC. The land lease agreement that you show a screenshot of
is an OLC contract (and OLC has 20 Ethiopian Ks). But the Albania,
Azerbaijan, and China missing docs are missing for another reason.

On Thu, Nov 12, 2015 at 2:24 AM, Charles Young <notifications@github.com>
wrote:

>
>    1.
>
>    Cambodia
>    Three contracts published but none on the RC public site
>    2.
>
>    Albania
>    Twelve contracts published but only ten on the RC public site
>    3.
>
>    Azerbaijan
>    Six contracts published but only five on the RC public site
>    4.
>
>    Cameroon
>    Nine contracts published but only seven on the RC public site
>    5.
>
>    China
>    Sixteen contracts published but only ten on the RC public site
>    6.
>
>    Ethiopia
>    Twenty contracts published but none on the RC public site
>    7.
>
>    etc
>
> I noticed that all of the missing contracts, expect the Chinese contracts,
> are still waiting for full transcription.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/13888372/11113415/5a794cfe-8925-11e5-94bd-ce10809aa14e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/647>.
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEwoOzp&m=30f7032793ff&t=20151112&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEwoOzp&m=30f7032793ff&t=20151112&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PEwoOzp&m=30f7032793ff&t=20151112&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by charlesyoung** [comment]
Thanks for the clarification Kaitlin. @anjesh can you please investigate.

**Comment by anjesh** [comment]
Same problem as https://github.com/NRGI/resourcecontracts.org/issues/648, this is now fixed.

**Comment by charlesyoung** [comment]
Although not all the contracts showing because of missing category (RC / OLC). 

Related to case #655
