### ISSUE TITLE
Annotation module improvement - linking to multiple pages and section_info

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#694]
We are thinking of the following UI to capture the information during the annotation process which will address the issue with the annotation linking to multiple pages. When the annotator selects the text in OCR content or highlights the content in the pdf, the following popup will appear. 

![image](https://cloud.githubusercontent.com/assets/120488/11466246/9f1d3e1a-9767-11e5-9940-06d9a5f49ed9.png)

**Section information**
Till now section information is captured as a part of the annotation text, however we have segregated the section info from the text during rendering. It makes more sense to have a separate box for the section information. 

**Annotation parent category**
Once the annotation selects the category, the box makes an api call to pull all the annotations for that particular category from that particular contracts and lists under "annotation parent". The annotator if selects the parent, then that will be linked to that annotation. 

The following activities need to carried out

* Develop annotator plugin for "section information" text input
* Develop annotator plugin for "annotation parent category" select input
* Develop API to pull the "annotations" based on the selected "annotation category" to list in "annotation parent"
* Write script to fix the existing "section information" data. Remove the "section information" from the annotation content and save it as a separate field in the annotation model for all the existing annotations. 
* Fix the API in the admin section for this new model (to include section-info, annotation-parent-category) 
* Fix the UI in the admin
* Fix the ES indexing API that indexes the annotation in the elasticsearch
* Fix the API for the subsite
* Fix the UI in the subsite for these two fields (section-info, annotation-parent-category)

https://docs.google.com/drawings/d/1WRLYbxFGf5LiF9POigDdyogyhZrdEgruHbWlDnKF-98/edit
![image](https://cloud.githubusercontent.com/assets/120488/11467445/3eecf5ea-9770-11e5-8cd5-a131e1848dbe.png)

The following json data model will be generated by the above UI.

Text annotation json
```
{
  "ranges": [
    {
      "start": "/div[2]/span[1]/span[2]",
      "startOffset": 892,
      "end": "/div[2]/span[1]/span[2]",
      "endOffset": 1003
    }
  ],
  "quote": "GANOUB EL-WADI HOLDING PETROLEUM",
  "category_key": "legal-enterprise-identifier",
  "cluster": "General"
  "text": "testing",
  "section_info": "Annex-1",
  "annotation_parent": 1
}
```

PDF based annotation json 
```
{
  "shapes": [
    {
      "type": "rect",
      "geometry": {
        "x": 0.33781512605042,
        "width": 0.37142857142857,
        "y": 0.21038961038961,
        "height": 0.094805194805195
      }
    }
  ],
  "category_key": "legal-enterprise-identifier",
  "cluster": "General"
  "text": "testing",
  "section_info": "Annex-1",
  "annotation_parent": 1
}
```

The annotation will be stored in the following structure in the database 

```
annotation-id
annotation-json { 
          annotation-position (ranges for text, shapes for pdf, 
          category, 
          cluster, 
          text, 
          section_info 
    } 
page-no
annotation-parent-id
```

When the annotation is indexed in the ES, there won't be annotation-parent-category field, the system will automatically fill the annotation-text from the annotation-parent-category, so that there will be less need of changes in the subsite. We will still need to fix for the section-info part in the subsite.

**Comment by anjesh** [comment]
Linked to https://github.com/NRGI/resourcecontracts.org/issues/562 and https://github.com/NRGI/resourcecontracts.org/issues/71

**Comment by anjesh** [comment]
Thoughts and feedbacks? @anderspeders @charlesyoung @SamCCSI

**Comment by anjesh** [comment]
Missed @byndcivilization

**Comment by KaitlinCCSI** [comment]
@anjesh could you please provide more info and a mockup of how this would
look and act in terms of the UI? Thanks.

On Mon, Nov 30, 2015 at 3:13 AM, Anjesh <notifications@github.com> wrote:

> Missed @byndcivilization <https://github.com/byndcivilization>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/694#issuecomment-160565508>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PLJcRR6&m=8b4d6e716f8a&t=20151130&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PLJcRR6&m=8b4d6e716f8a&t=20151130&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PLJcRR6&m=8b4d6e716f8a&t=20151130&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by SamCCSI** [comment]
Exciting, thanks Anjesh.

One question: will this enable one annotation to link to multiple places in
the document (by selecting the parent) or will it still mean that we are
linking three separate annotations?

We want to have one annotation link to multiple places.

On Mon, Nov 30, 2015 at 8:21 PM, KaitlinCCSI <notifications@github.com>
wrote:

> @anjesh could you please provide more info and a mockup of how this would
> look and act in terms of the UI? Thanks.
>
> On Mon, Nov 30, 2015 at 3:13 AM, Anjesh <notifications@github.com> wrote:
>
> > Missed @byndcivilization <https://github.com/byndcivilization>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/NRGI/resourcecontracts.org/issues/694#issuecomment-160565508
> >
> > .
> > ------------------------------
> >
> > Spam
> > <
> https://antispam.law.columbia.edu/canit/b.php?i=01PLJcRR6&m=8b4d6e716f8a&t=20151130&c=s
> >
> > Not spam
> > <
> https://antispam.law.columbia.edu/canit/b.php?i=01PLJcRR6&m=8b4d6e716f8a&t=20151130&c=n
> >
> > Forget previous vote
> > <
> https://antispam.law.columbia.edu/canit/b.php?i=01PLJcRR6&m=8b4d6e716f8a&t=20151130&c=f
> >
> >
>
>
>
> --
>
>
> *KAITLIN Y. CORDES*
>
> *Head: Land and Agriculture**Columbia Center on Sustainable Investment*
> Columbia Law School - The Earth Institute, Columbia University
> 435 West 116th St. New York, NY 10027
> | +1 (917) 658 5172
> | kaitlin.cordes@law.columbia.edu
> | www.ccsi.columbia.edu | @CCSI_Columbia <
> https://twitter.com/CCSI_Columbia>
> | @kaitlincordes <https://twitter.com/kaitlincordes>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/694#issuecomment-160816442>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
Level 1, Warren Hall, 410 W116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by JesseCCSI** [comment]
Hi @anjesh will this approach allow annotators/ reviewers to: 

1. Change the contract page number to which an existing annotation is anchored? 
2. Move the annotation box around the page?

(requested in ticket #573 ) 

Many thanks.

**Comment by anjesh** [comment]
https://github.com/NRGI/resourcecontracts.org/issues/708#issuecomment-162871802 issue will supercede this issue, where moving the annotation box will also be possible and the process of annotation will be easy compared to existing one. 

As for changing the page number, it doesn't work in case of text based annotation because of the way annotations are handled in text. This is something we could have in pdf. I am assuming this page number changing is for the existing annotations only, for the new ones - these hardly should be the case when the annotators start to annotate using the system.

**Comment by JesseCCSI** [comment]
Hi @anjesh 

Having the ability to move the annotation box will be really useful, so thank you for incorporating that. 

Re the page numbers, in most cases this is needed to fix existing annotations that are anchored to incorrect pages. Going forward, we may need to change the page numbers where annotators make a mistake and attach an annotation to the wrong provision.

If the ability to change page numbers is incorporated, but only applies to PDF annotations, does that mean that the highlighted text in the text version of contracts will not be moved to the correct portion of text?

**Comment by anderspeders** [comment]
As requested by @KaitlinCCSI, please provide mock ups of:
a) How this would look on the front end and 
b) How  on the back end for an annotating user including workflow

**Comment by charlesyoung** [comment]
@anjesh can we get mock ups as requested? I had a call with Perrine and Joan Serrano today about annotating contracts for the Philippines and this was raised as a problem that needs to be addressed as soon as possible. We should also include Perrine in this discussion.

**Comment by jedm** [comment]
Small question - I think for @JesseCCSI - are we still using *contract page numbers* in the citations? There seems to be a greater risk of confusion if we were to default to using *PDF page numbers* (ie, whatever number the page is in the PDF, even if the page number shown in the original contract doc is different).

On the other hand, if this policy has already been set the other way, it's definitely not worth re-opening!

**Comment by JesseCCSI** [comment]
Hi @jedm - Apologies for the delayed reply. The page numbers that appear on OLC under the annotations are PDF page numbers - annotators using the Excel template to annotate contracts also used PDF page numbers when signalling the location of relevant provisions. 

Hope this answers your question?

**Comment by jedm** [comment]
Hi Jesse - if that is the consistent practices for all future documents in all RC/OLC repositories and subsites then I guess that's ok, but it will certainly confuse some people sometimes -- especially for the (hopefully small number?) of documents that happen to have original page numbers visible that do not correspond. 

I can see the value of doing it this way, but, again, should be enforced for all annotators including for country sites and should also be noted clearly as the standard practices in the site FAQ.

**Comment by JesseCCSI** [comment]
Many thanks @jedm - we could switch to using the contract page numbers, but this would require a lot of retro-fitting (particularly for RC), so we'll likely stick with the PDF page numbers. Some contracts don't have page numbers, and at least this way the page number under the annotation will match the number in the box at the top of the PDF (hopefully this reduces user confusion!). 

Both RC and OLC should, as far as we know, be using PDF page numbers.

**Comment by SamCCSI** [comment]
Hi all,

I can confirm that this has been the consistent practice for both RC and
OLC.

On Tue, Jan 19, 2016 at 2:22 PM, JesseCCSI <notifications@github.com> wrote:

> Many thanks @jedm <https://github.com/jedm> - we could switch to using
> the contract page numbers, but this would require a lot of retro-fitting
> (particularly for RC), so we'll likely stick with the PDF page numbers.
> Some contracts don't have page numbers, and at least this way the page
> number under the annotation will match the number in the box at the top of
> the PDF (hopefully this reduces user confusion!).
>
> Both RC and OLC should, as far as we know, be using PDF page numbers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/694#issuecomment-172957925>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment]
With regards to the original issue of this particular issue (i.e. linking one annotation to multiple page), i have prepared a wiki page on the potential solution. This is doable solution compared to https://github.com/NRGI/resourcecontracts.org/issues/708 where it appears that we will need to do lot of work (need to do estimatation). 

See https://github.com/NRGI/resourcecontracts.org/wiki/Annotation-Module

I will ensure that the document reflects our further discussion and decisions on the annotation module. There has been lots of discussion in different issues, that is an attempt to bring in one page. 

Once we are ok with the annotation capture process, view part will be quick.

**Comment by SamCCSI** [comment]
Regarding the Wiki for the Annotation Module:

This looks great. We would suggest the following changes:  

1. **We don't need to have more than one annotation per category.** In fact, we have a policy of having only one annotation per category, so please do not create this functionality.  A single annotation may draw content from multiple annotations, which is why we need to attach one annotation to multiple places within the contract.   

2. Can you change the format of "Related annotations" so that the Annotation just sets out all page references, one after the other. Eg:
![image](https://cloud.githubusercontent.com/assets/12913915/12768038/0b942cd4-c9db-11e5-8ca1-1f47c137dca5.png)

3. If there a multiple references to the same page, we could distinguish this by 
(a) Having the article references in brackets next to the page number so that it reads “Pages 4 (Arts. 2, 16, 33), 7, 9." 
OR 
(b) Have each page only listed once, but highlighting all annotation ribbons on the page (so that when a user clicks on a particular annotation, the annotation ribbons are highlighted).

4. More generally, is it possible to include article references next to each page reference?

![image](https://cloud.githubusercontent.com/assets/12913915/12768079/4ced9c74-c9db-11e5-8cad-a54f4f9de69f.png)

5.The parent annotation must be changeable when you are adding the second, and third etc. page references. This will be essential for annotators, who will be adding information to the annotation as the read and add each additional page reference. 

6.Terminology: For clarity, I suggest:  "Section" --> should be "Article Reference" "Comments" --> should be "Annotation Text" or “Annotation”   

7.Changing the location of annotations  We need to be able to:  
(a) change the page number to which an annotation is anchored;  
(b) change the article number that relates to an annotation; and  
(c) change the location of the yellow annotation box on the page after annotators add their annotations. This will allow us to correct any errors that annotators may make.

**Comment by SamCCSI** [comment]
(That last comment was from Jesse and Sam on behalf of CCSI)

**Comment by anjesh** [comment]
I have updated the wiki as per your comments https://github.com/NRGI/resourcecontracts.org/wiki/Annotation-Module that addresses points 1,2,3,4,5,6.

With regards to 7,
> (a) change the page number to which an annotation is anchored;

The page number could be changed from the annotation listing page. It can't be changed during the annotation edit process in the annotation editor. 

> (b) change the article number that relates to an annotation; and

Article Reference could be changed from the Annotation editor as well as annotation listing page in the contract details page in admin. 

> (c) change the location of the yellow annotation box on the page after annotators add their annotations. This will allow us to correct any errors that annotators may make.

This is something that might take time or something that might be tremendously difficult to implement due to the plugin we are using (annotorious.js for the pdf annotation). It doesn't support the moving boxes by default, that means we have to write lots of things over the original implementation - ensuring that it doesn't break. This has to wait for later.

**Comment by anjesh** [comment]
With this new model, we need to migrate the existing annotations to fit into that model - there are annotation categories which contains two different types "Annotation Text". That won't fit into the new model. We need to define the logic to fix those annotations. We will prepare the list of all the annotations, do some analysis and send you the list to decide on how to go about these annotations errors.

**Comment by SamCCSI** [comment]
This bug just occurred for me again. Clicking page back, and then page forward got it to appear the right way though.
![image](https://cloud.githubusercontent.com/assets/12913915/12853313/717c968a-cc01-11e5-89dc-aac807b6b67a.png)

**Comment by JesseCCSI** [comment]
Thanks @anjesh 

Kaitlin, Sam and I discussed this today -- it would really help us if you could provide an estimate of the cost and time involved in implementing the following: 

1. having the ability to change the location of the yellow annotation box on the page; and 
2. having the ability to re-size the annotation box. 

Re point (2), we were looking at how this contract (http://www.resourcecontracts.org/contract/ocds-591adf-PH7733849609RC/view#/pdf/page/10/annotation/26427) was annotated by the Philippines EITI team. The way they have placed the annotation boxes helps to draw the user's eye to the relevant place on the page. We'd like to have the ability to do the same with new contracts on OLC, and to update the existing contracts without having to re-upload them. 

Also, as annotators start to add contracts directly to the site, it's likely that they will make errors in how they place the annotation boxes. Having the ability to change the location and size of annotation boxes will help our team to be more efficient, and will cut down the time needed to review contracts. Currently, if an annotator makes a mistake re the location or size of the box, the reviewer has to re-annotate. This can take a lot of time if many of boxes are incorrectly sized/ placed. 


**We also had the following comments re the updated solution **(https://github.com/NRGI/resourcecontracts.org/wiki/Annotation-Module) 

A. Under "Potential solution", change "Each category may have only one or more annotation." to "Each category may have only one annotation." 

B. In the example, you refer to the category of "Environmental monitoring", but the screenshots use the category "Environmental Protection". Could you please alter the wording of the example so that it refers to "Environmental Protection" (or change the screenshots so that they refer to "Environmental monitoring". This will help avoid confusion.

C. Just confirming that at the exact same annotation window at the end of the example (screenshot below) would appear at each annotation box? Ie. each annotation window for "Environmental Protection" will auto-update when we change the wording in a subsequent annotation window? And similarly, whenever I edit any annotation window for "Environmental Protection", all windows with that annotation will auto-update.

![image](https://cloud.githubusercontent.com/assets/14910764/12853228/e86bec7e-cc00-11e5-9c9c-29df51e01a28.png)


D. Please add the following definition to the Terminology section
Annotation box - the yellow rectangular marker that locates each annotation on the PDF version of the contract.

**Comment by anjesh** [comment]
> having the ability to change the location of the yellow annotation box on the page; and
having the ability to re-size the annotation box.

I totally get this point. However as I have mentioned in couple of other issues, this changing location and re-sizing abiliy in the plugin we are using is not easily doable due to the way the plugin is developed, as far as i have seen the insides of the working-code. I can't come up with effort required and hence cost at this moment. We still need to explore the code to ensure how to cleverly inject these two features in it. Internally we discussed about implementing this functionality under different mode like "box mode", where you will be able to move the boxes and re-size them, then you won't be able to add/edit/delete annotations in that mode. This still requires some research and before that it's hard for me to come up with any numbers. We are not prioritizing this at the moment, but will set aside some time to explore on this. 

Thanks @JesseCCSI for these. 

> A. Under "Potential solution", change "Each category may have only one or more annotation." to "Each category may have only one annotation."

Fixed.

> B. In the example, you refer to the category of "Environmental monitoring", but the screenshots use the category "Environmental Protection". Could you please alter the wording of the example so that it refers to "Environmental Protection" (or change the screenshots so that they refer to "Environmental monitoring". This will help avoid confusion.

Fixed. 

>  C. Just confirming that at the exact same annotation window at the end of the example (screenshot below) would appear at each annotation box? Ie. each annotation window for "Environmental Protection" will auto-update when we change the wording in a subsequent annotation window? And similarly, whenever I edit any annotation window for "Environmental Protection", all windows with that annotation will auto-update.

Yes, whenever you edit annotation-text of any annotation-window for that category, the updated text will be reflected in all the annotations for that category. 

> D. Please add the following definition to the Terminology section
> Annotation box - the yellow rectangular marker that locates each annotation on the PDF version of the contract.

Added in the wiki

**Comment by charlesyoung** [comment]
Relating to the the ability to change the location of the annotation box on the page mentioned by @SamCCSI and @KaitlinCCSI. 

Sierra Leone contracts were annotated on the side and not over the text as shown below. 

![image](https://cloud.githubusercontent.com/assets/13888372/13204851/b4c3b098-d8e2-11e5-8295-4a2884e41bfe.png)

The annotations will all have to be redone if the annotation boxes cannot be moved.

**Comment by charlesyoung** [comment]
Tested the new annotation module.

The link is http://resourcecontracts-demo1.elasticbeanstalk.com/contract/785/annotate#/pdf/page/1/annotation/8134

Results as follows: 

**A. Admin Module**
1. Using the same tag for multiple annotations works but I picked up minor issues that will be logged later. 
2. Editing an annotation category doesn't work. I added GANOUB EL-WADI HOLDING PETROL
COMPANY as the Legal Enterprise and wanted to change it to the Name of company executing document but it didn't work. 
3. The annotation boxes disappear and the only way show it again is to exit the contract.  
4. Is this by design but the 'more' text link isn't displayed anymore.  
5. Incorrect display of annotation summaries as shown below. Also cannot click to edit. 

![image](https://cloud.githubusercontent.com/assets/13888372/13351550/0bc531ea-dc90-11e5-88eb-095cb808c88e.png)

**B. Public Module**
1. Couldn't test because although published it didn't show on the demo RC site

The new annotation module still needs lots of testing.

**Comment by charlesyoung** [comment]
Related annotations for multiple annotations don't always show all the page numbers. In below screenshot page 11 isn't shown which could be correct because the user is on page 11. 

![image](https://cloud.githubusercontent.com/assets/13888372/13390866/a9f4ad46-ded9-11e5-8a8a-bd59c21593aa.png)

But then on page 5 the related annotation on page 11 is displayed. 

![image](https://cloud.githubusercontent.com/assets/13888372/13392178/79df758e-dee1-11e5-9dfc-7b2b6ef6f0bf.png)

**Comment by SamCCSI** [comment]
We have started to test this module as well. Some initial reactions:

1. Please change display of page refs in the annotation window to make it the same as in the left column. I.e. include all pages and art refs. 
![image](https://cloud.githubusercontent.com/assets/12913915/13399059/5dc851d4-decf-11e5-8c73-2e39ef46a3ef.png)
![image](https://cloud.githubusercontent.com/assets/12913915/13399080/814e0d74-decf-11e5-852b-c1f7b424099b.png)

2. Left hand column needs to say "Page**s**" when there are two or more page refs.

3. I assume we will be able to edit the contract page number? I couldn't do it from the backend contract listing page, but that might just be because it is a stage site.

**Comment by SamCCSI** [comment]
Illustrating Charles' point 4, above. We need to be able to expand / contract the annotation:

![image](https://cloud.githubusercontent.com/assets/12913915/13437187/e0aae526-dfb0-11e5-97ff-0f07da779f43.png)

**Comment by charlesyoung** [comment]
1. This isn't new but it's cumbersome to have two vertical scroll bars. 

![image](https://cloud.githubusercontent.com/assets/13888372/13456710/29521e18-e06d-11e5-8c46-b42bc28eacbe.png)

2. Category hyperlink removed. Is this by design? 

![image](https://cloud.githubusercontent.com/assets/13888372/13457101/f8d03f02-e06e-11e5-9aa9-00d48e710e8b.png)

Existing site. 

![image](https://cloud.githubusercontent.com/assets/13888372/13456943/2b5ef3f6-e06e-11e5-8b24-19974ecedd44.png)

3. Cannot select the entire annotation box when zoomed in past 150%

![image](https://cloud.githubusercontent.com/assets/13888372/13457239/c3d0aebc-e06f-11e5-8a3f-1aca804dca45.png)

4. Caches the free text annotation information. Is this by design? 

![image](https://cloud.githubusercontent.com/assets/13888372/13457341/5e734506-e070-11e5-839f-54a993d6dece.png)

**Comment by charlesyoung** [comment]
Linked to case #791

**Comment by charlesyoung** [comment]
Will we need to provide annotation support for other languages like Spanish and if so how will this be presented in an already 'full' category drop down list? 

![image](https://cloud.githubusercontent.com/assets/13888372/13458919/ded088e6-e078-11e5-8bc0-2701080196a8.png)

**Comment by charlesyoung** [comment]
Annotation boxes are not displayed on the correct place when flipping between pages. 

![image](https://cloud.githubusercontent.com/assets/13888372/13459420/1ec6c23c-e07c-11e5-8481-96c6d71475ec.png)

**Comment by SamCCSI** [comment]
As discussed with @anderspeders we are happy for this module to be deployed once the 3 issues I mention above are incorporated, with the understanding that future changes / fixes may be needed. Can you please let me know when this is ready? 

If I start an annotation now. Can I amend it once the new module is running, or do I need to start from scratch?

**Comment by KaitlinCCSI** [comment]
Hi @anjesh do you know when this will be deployed? We are hoping to start annotating again this week.

**Comment by manishgs** [comment]
We are working on fixing issues which are reported on comments. We haven't work on API and subsite to reflect new annotation module. Once @anderspeders  confirm this annotation process is ready to go then will work on API, Subsite and annotation harmonization.

> .If I start an annotation now. Can I amend it once the new module is running, or do I need to start from scratch?

We'll harmonize the existing annotations to fit on new annotation module. you don't need to start form scratch.

**Comment by charlesyoung** [comment]
Couple of minor points relating to below image. 

1. 'Click on hyperlink to edit' and not 'Double click to edit'. 
2. Should the page numbers not also be hyperlinked?
3. Do we not show the summary annotation info anymore? 

![image](https://cloud.githubusercontent.com/assets/13888372/13636593/55333c1c-e60b-11e5-8261-aa47e3412884.png)

**Comment by manishgs** [comment]
Latest work deployed in [admin](http://resourcecontracts-demo1.elasticbeanstalk.com/) and [subsite](http://rc-site-demo.elasticbeanstalk.com/rc/public/) demo server.  Please review once and let us know your feedback and comment.

**Comment by SamCCSI** [comment]
This is looking great. Some things to be improved:

1. Change "Related Annotations" to "See also":
![image](https://cloud.githubusercontent.com/assets/12913915/13933161/1ef1f56e-ef82-11e5-83cd-a9e3c9d1c8ba.png)

2. Article references need to be save-able and amendable. Right now, when I manually amend an article reference it currently does not update anywhere. E.g. For above screen shot, I changed one of the article references from "1.7" to "Art. 1.7" but that change isn't incorporated on any of the markers.

Another note: If I enter in multiple references for one annotation category on multiple pages, the system wont then let me change the annotation category. It stays as the initial category I selected. This is probably wise, to avoid losing annotations, but I just wanted to note it here.

@JesseCCSI will also do a review today. I recommend that after that, barring any large problems, we deploy the module on the live site, and then communicate any other problems as we go about using the module.

**Comment by SamCCSI** [comment]
I have just significantly edited the above comment -- please re-read. Thank you!

**Comment by JesseCCSI** [comment]
Thanks, this seems to be working well. I noticed the following: 


1. When I changed the annotation category, this didn't seem to work -- it removed the relevant annotation attached to the particular article reference for which I edited the category, and the new category I selected then appeared at the bottom of the page (without an annotation underneath) -- see screenshot below. I suggest that we address this by: (1) not giving the possibility to change the annotation category, and making sure that what happens currently (as reflected in the screenshot) doesn't happen going forward; or (2) allowing annotators to change the annotation category, which might be useful for reviewers where annotators make a mistake. I would prefer option 2, but cc'ing @SamCCSI and @KaitlinCCSI in case they have a preference on this? 
2. The yellow annotation markers are somewhat buggy -- in some cases, when I hover over them, the annotation box appears (allowing me to click on the pencil icon in order to edit the annotation), and other times nothing happens when I hover over or click on the box. 
3. Changes to article references don't appear to be saved/ reflected, as mentioned by Sam above
4. I know this has been mentioned above by myself and others (including @charlesyoung), but having the ability to (1) change the page number of the annotations, and (2) change the location of the yellow annotation markers and adjust the size of the markers would be extremely useful. This is important not only for annotators/ reviewers going forward, but also to fix all the incorrectly placed annotation markers that already exist (both on OLC and RC). Also it's important to note that these abilities are interlinked -- there is little point in being able to change the page number without being able to change the location of the yellow annotation marker. 

![untitled](https://cloud.githubusercontent.com/assets/14910764/13966128/67ae97ce-f047-11e5-940a-b44e9bcb5be4.png)

**Comment by KaitlinCCSI** [comment]
Just a note that changing location/size of yellow markers very important
for cleaning up current annotations as well as for reviewing
annotations moving forward. See this as key to having a workable site for
the long term.

On Tuesday, March 22, 2016, JesseCCSI <notifications@github.com> wrote:

> Thanks, this seems to be working well. I noticed the following:
>
>    1. When I changed the annotation category, this didn't seem to work --
>    it removed the relevant annotation attached to the particular article
>    reference for which I edited the category, and the new category I selected
>    then appeared at the bottom of the page (without an annotation underneath)
>    -- see screenshot below. I suggest that we address this by: (1) not giving
>    the possibility to change the annotation category, and making sure that
>    what happens currently (as reflected in the screenshot) doesn't happen
>    going forward; or (2) allowing annotators to change the annotation
>    category, which might be useful for reviewers where annotators make a
>    mistake. I would prefer option 2, but cc'ing @SamCCSI
>    <https://github.com/SamCCSI> and @KaitlinCCSI
>    <https://github.com/KaitlinCCSI> in case they have a preference on
>    this?
>    2. The yellow annotation markers are somewhat buggy -- in some cases,
>    when I hover over them, the annotation box appears (allowing me to click on
>    the pencil icon in order to edit the annotation), and other times nothing
>    happens when I hover over or click on the box.
>    3. Changes to article references don't appear to be saved/ reflected,
>    as mentioned by Sam above
>    4. I know this has been mentioned above by myself and others
>    (including @charlesyoung <https://github.com/charlesyoung>), but
>    having the ability to (1) change the page number of the annotations, and
>    (2) change the location of the yellow annotation markers and adjust the
>    size of the markers would be extremely useful. This is important not only
>    for annotators/ reviewers going forward, but also to fix all the
>    incorrectly placed annotation markers that already exist (both on OLC and
>    RC). Also it's important to note that these abilities are interlinked --
>    there is little point in being able to change the page number without being
>    able to change the location of the yellow annotation marker.
>
> [image: untitled]
> <https://cloud.githubusercontent.com/assets/14910764/13966128/67ae97ce-f047-11e5-940a-b44e9bcb5be4.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/694#issuecomment-199995531>
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qx84nhR&m=f05fd2f8000d&t=20160322&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qx84nhR&m=f05fd2f8000d&t=20160322&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qx84nhR&m=f05fd2f8000d&t=20160322&c=f>
>


-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by manishgs** [comment]
New Annotation Module has been Implemented. Please review on [admin](http://admin.resourcecontracts.org/contract/1179/annotate) and [subsite](http://www.resourcecontracts.org/contract/ocds-591adf-PY3648285958RC/view).
