### ISSUE TITLE
Pinning: 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#70]
As a user I should have the ability to select and cache individual clauses across contracts for comparison. These clauses should be possible to store in session and export to excel or PDF as a report. Example: I wish to compare stabilization clauses. I search contracts for clauses tagged as such, pin those clauses for later comparison and export a report of the pinned html, data and associated metadata.

**Comment by anjesh** [comment]
There will be pin link while the user is viewing contract or contract text or contract annotation. 
![image](https://cloud.githubusercontent.com/assets/120488/8446939/e1337dc8-1fd0-11e5-9993-248831d92eba.png)

User has to select the text and those gets auto-pinned on the right. They can also remove those pins by clicking on the 'x' on the right or clear all the pins by clicking 'clear all'.
![image](https://cloud.githubusercontent.com/assets/120488/8446942/e4d0fe06-1fd0-11e5-9991-eaf23c4701f6.png)

User can move around the pages or different contracts and select the text to pin them. All the pins get stored in the local storage of the user browser, until the user removes them. 
![image](https://cloud.githubusercontent.com/assets/120488/8446944/eaa209ba-1fd0-11e5-9947-e3f7e93699a2.png)

"Export" will generate the csv for now, with the following information
* Pinned text 
* contract title
* contract url
* page number

cc @byndcivilization @anderspeders

**Comment by anderspeders** [comment]
The pinning option should start with the annotations by enabling a selection of multiple pinned annotations or a <select all> option from across one or multiple contracts. 

So for example: pin and download all annotations for X contract with:
- annotation tag
- annotation string text
- contract text
- URL for annotation
- several metadata fields

See example of pinned and exported annotations:
https://docs.google.com/spreadsheets/d/11RB15slKsPj1lpjtiSdGrlOGJh3CGALeLZCEKQHcR_A/edit#gid=0  

The export format should be done in CSV

**Comment by anjesh** [comment]
" pin and download all annotations for X contract" Can you clarify this line?  My understanding from the user story is - pinning is basically selecting the text in the document to pin in your list for later comparisons, and that might include those annotated as well. Perhaps we could have something like "pin" button or icon in the annotation list as well, so that user can just click that to pin to in his or her pinned items. The one i have prepared above helps users to select and pin any text in the document of his/her interest. Mixing pinning with annotations as you've mentioned above "The pinning option should start with the annotations by enabling a selection of multiple pinned annotations or a option from across one or multiple contracts" is confusing to me.

**Comment by anjesh** [comment]
Basic pinning in place. Closing this, new improvements in new issue #116
