### ISSUE TITLE
search within contract text

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#704]
How does the search within contract text work? Results are returned in lefthand column, but they don't seem to match all of the places within the contract text where a word appears. See 2 screenshots for examples that show a search for "subject" and a search for "infrastructure", and 1 result/page in the left column, although "subject"/"infrastructure" appears multiple times on the page seen in the screenshot. Is this on purpose? If so, is this best practice? It does not seem intuitive to me.

Also, note that the pages at the top do not always match up to the text pages, as shown in one of the screen shots.

cc  @anjesh @byndcivilization 

![screen shot 2015-12-03 at 9 38 35 am](https://cloud.githubusercontent.com/assets/14825437/11565127/31d15e30-99a2-11e5-9c71-c98e6940b92c.png)

![screen shot 2015-12-03 at 9 46 05 am](https://cloud.githubusercontent.com/assets/14825437/11565287/e045f250-99a2-11e5-84e1-b835b20f87c5.png)

**Comment by anjesh** [comment]
This is done on purpose. The reason being if we show all the instances of the "search word" from the page, the results list will get long with the same page appearing multiple times. I am not sure if this can be considered best practice but it helps to narrow down the results list. perhaps more discussion is needed to decide how best to list the search results.

**Comment by KaitlinCCSI** [comment]
More discussion would help, as it's not intuitive to me. Interested in thoughts from @jedm @byndcivilization @samccsi

**Comment by byndcivilization** [comment]
One option might just be to list the number of hits per page. Another might be to limit surrounding text to a shorter chunk.

**Comment by jedm** [comment]
Agree with @byndcivilization re showing # of hits. Some sites use phrasing like "... and [X] more ..."

**Comment by charlesyoung** [comment]
@KaitlinCCSI is this still required?

**Comment by KaitlinCCSI** [comment]
Yes, I think it makes sense to follow the suggestion of Chris/Jed if possible. Think it will make search clearer, more intuitive, and more in line with the practice of other sites.

**Comment by manishgs** [comment]
As per above discussion, search results will be look like below.

**Pg 9** L’etat de cessation de paiement du concessionnaire constitue une cause de decheance et entraine la resiliation du present **contrat**. Article 24: Les infractions mentionnees a ... _and 3 matches more on this page_

--------

**Pg 1** REPUBLIQUE DEMOCRATIQUE DU CONGO Ministre de L'environnement, Conservation de la Nature et Tourisme **CONTRAT** DE CONCESSION FORESTIERE N ........./11 du......... _and 2 matches more on this page_

@jedm  @KaitlinCCSI 

Let us know if you are happy with the wording.

**Comment by charlesyoung** [comment]
@jedm @KaitlinCCSI you happy with the wording?

**Comment by jedm** [comment]
If it is searching ONLY ONE PAGE, suggest change to:

and X more matches on this page

If it is searching ENTIRE DOCUMENT, suggest change to:

and X more matches in this document

**Comment by KaitlinCCSI** [comment]
I agree with @jedm suggestion. Also, if there is only 1 more match, then can it say "and 1 more match on this page" or "in this document" (rather than "matches")?

**Comment by manishgs** [comment]
Search Result text updated on live.

**Comment by SamCCSI** [comment]
@jedm 's suggestion has not been implemented.

> If it is searching ONLY ONE PAGE, suggest change to:
> 
> and X more matches on this page
> 
> If it is searching ENTIRE DOCUMENT, suggest change to:
> 
> and X more matches in this document

**Comment by manishgs** [comment]
Text is searching on entire document but we are displaying hits per page so we are using the word "and X more matches on this page" rather than "and X more matches in this document".

**Comment by SamCCSI** [comment]
Thanks @manishgs 

I think it would be better if the "and X more matches..." text starts on a new line, so that it is recognizable by users. Right now it belnds into the surround text.

@jedm any other thoughts on how this is presented? E.g. right now the X other matches can't be identified by clicking on that line of text. It just informs us that there are other matches. Maybe that's fine but interested in your thoughts.

![image](https://cloud.githubusercontent.com/assets/12913915/23757491/ffea466e-04b4-11e7-9d2a-c3d13df89b68.png)

**Comment by jedm** [comment]
I would like to experiment with this a little more before making a
suggestion. It is a bit confusing to split matches-shown and total-matched
so completely. Probably solvable with language, however.

**Comment by manishgs** [comment]
@jedm @SamCCSI 
We can change the color of the 'and X more matches...' text like shown in the screen. Let us know what do you think.

![screenshot-localhost-8001 2017-03-15 17-32-32](https://cloud.githubusercontent.com/assets/3942999/23947392/b2804bca-09a6-11e7-9354-4ae4428ba0b7.png)

**Comment by charlesyoung** [comment]
@jedm @SamCCSI any comments?

**Comment by charlesyoung** [comment]
@jedm any feedback?

**Comment by jedm** [comment]
My recommendations below and in jpg illustration. Thanks.

1) Change “Search result” to “Search results”

2) Add two lines below “Search results” message:
    “**X** matches in document”
    “**Y** matches on current page”
— text shoud be black like the line above it
— make numbers boldface
— second number changes dynamically based on page shown in viewer

3) “and X more matches” language is good, but please switch to hotlink color the way it is in GitHub mockup to remind user it is hotlink and that it is not Annotation text

![slide1](https://cloud.githubusercontent.com/assets/2153664/24119925/18c22ce2-0d70-11e7-9fd5-dbb128e5c74e.jpg)

**Comment by manishgs** [comment]
@jedm Thank you for you feedback. 

Search result also shows the annotation text. so we have also added annotation matches. Please review the below mockup and let me know your feedback.

![screenshot- 2017-03-21 20-22-44](https://cloud.githubusercontent.com/assets/3942999/24152617/438feeaa-0e74-11e7-9161-5d3da883ab09.png)

**Comment by jedm** [comment]
Hi, @manishgs - This not advised. I would use the phrasing suggested previously:

“X matches in document”
“Y matches on current page”

To further clarify:
- User made their search "in document" so it will be confusing to make distinction between "document" and "annotation" in display at top of column.
- The matches "on current page" means the number of matches on PAGE CURRENTLY DISPLAYED IN VIEWER to the right

If this does not make sense, feel free to send any additional questions before implementing. Thank you again.

cc @anjesh

**Comment by charlesyoung** [comment]
@manishgs have you had time to look at above comments?

**Comment by manishgs** [comment]
@jedm Your suggestions have been implemented. Please review on production and let us know your comment.

**Comment by jedm** [comment]
Hi @manishgs it does not seem to be functioning right. See attached example where matches are found but totals are blank. 

Other errors:

- English syntax is incorrect. It should be "0 matches in document" (with "es")
- System messages should be in the same form, i.e.: "0 matches in document" "0 matches in current page"
- Remove period at end of phrases
- Reduce vertical space between first message and second message

Once these fixes are made we can test function further. Thanks!

![img_7773](https://cloud.githubusercontent.com/assets/2153664/24458184/0ca7bdd0-144d-11e7-94ca-b0124d6b4109.PNG)

**Comment by manishgs** [comment]
We are using fuzzy logic for text search that's why total matches doesn't give the exact count for the searched query but we are working on this issue. We've few things to confirm.

1. The search functionality also search for annotations text. Currently the total count is showing only for pdf text matches, annotation text matches not included while calculating the total matches. 

2. If search result found only in annotation text, then there will be 0 matches in document but search result will have one or more results. Do we still show the text "0 matches in document" or should we include annotation search matches on total count?

3. We're hiding the "X matches in current page" text when click on annotation result as it opens the PDF view.

**Comment by jedm** [comment]
@anjesh can you help us clarify this? I am not sure I fully understand.

**Comment by anjesh** [comment]
Lets say contract has 8 instances of dispute and its annotations has 2 instances of dispute. When you search for dispute, you will see the following now. 
```
8 matches in document
1 match in current page
```
Now the problem is it doesn't include annotations matches.  As you have suggested, the annotation count is not added.

Question 1: do we add annotation count in the above message. If we don't and if "dispute" is found in annotations but not in document you get the following message.
```
0 matches in document
```
That's what you see in your case. 

We need to say either

```0 matches in document and 2 matches in annotation``` 
or 
```2 matches in document``` - which includes the annotation count as well - to avoid confusion. 

What do you say? Need your feedback on this

Next thing is if you click on the search result (found in annotation), you will be taken to pdf page and the message " xx matches in current page" is hidden as it's part of annotation and not part of the page content.

**Comment by jedm** [comment]
Thanks for the clarifications! Two replies:

> We need to say either
> 0 matches in document and 2 matches in annotation
> or
> 2 matches in document - which includes the annotation count as well - to avoid confusion.
> What do you say? Need your feedback on this

Please use second option - so total matches "in document" will actually include in text and in annotation.
 
> Next thing is if you click on the search result (found in annotation), you will be taken to pdf page and the message " xx matches in current page" is hidden as it's part of annotation and not part of the page content.

The message should not be hidden. The message should be displayed until the user clicks the red X or clicks away from the document. Is this possible?

**Comment by manishgs** [comment]
> The message should not be hidden. The message should be displayed until the user clicks the red X or clicks away from the document. Is this possible?

If we are not hiding the message then when user click on annotation result the count will include only the matches found in the current annotation as follow.
```
"2 matches in current annotation"
```
but for text view it will show the total number of matches found in current text as before as shown below.

```
"4 matches in current page"
```

**Comment by jedm** [comment]
No. The message stating total matches on page should always display the total number matches on current page in viewer, INCLUSIVE of text and annotations/PDF. 

Message stating total matches on page should NOT change if user switches between text and PDF view of same page. 

Message with number of total matches on page should change ONLY when user moves to DIFFERENT PAGE. 

Is this behavior possible?

**Comment by manishgs** [comment]
Yes, its possible. So if page 1 has 4 matches in Text and it has 3 annotations with 2 matches in each annotation, the total count will be 10 (4+3*2) and the message will be same if user switch between text and PDF of page as below 

``` 10  matches in current page.```

**Comment by jedm** [comment]
Yes. Because the left column will show all matches in document and icons will distinguish between text matches and annotation matches I think that will be most clear to users. Thank you!

**Comment by manishgs** [comment]
@jedm Please review on [live](http://resourcecontracts.org/contract/ocds-591adf-3757991515/view#/search/participations).

**Comment by jedm** [comment]
@manishgs - I suggest deleting the extra line break between the two totals (document and page)

Also please say "on page" not "in page"

Other comments and functionality problems discovered to come Tuesday/Wednesday 

Thank you

**Comment by jedm** [comment]
Final comments on display, performance, bugs:

1) When you search in single contract, matches in text show page number in results list, but matches in Annotation/PDF do not show page number - see first image below

2) Number of current page matches listed in results does not always match the number shown in results column below it. Please research if this is because of additional matches in Annotation or some other bug. (i.e., If this is a result of the request to show only ONE number for single-page matches, we should tweak user language below for clarity) - see second image below

3) For a specific annotation result in PDF, when you click on the popup, the results display disappears - see third and fourth image below 

4) Also re. above: If functionality requires that results display disappears in above situation, then Search Term (3) should also disappear from “search in document” search box

5) Regarding #3 above, when you use the back button to try to get back to search the results display, the entire left column disappears - see fourth (pdf view) and fifth image (text view) below

6) Please change “No matches found in current page” to “No matches on current page”

![pgnumbers](https://cloud.githubusercontent.com/assets/2153664/24832732/027d1140-1c6b-11e7-8a8d-1b322c966f29.jpg)

![multiplematches](https://cloud.githubusercontent.com/assets/2153664/24832733/07ccfe6c-1c6b-11e7-9631-7d2b69f4ccd9.jpg)

![afterclick](https://cloud.githubusercontent.com/assets/2153664/24832751/70ef2bd6-1c6b-11e7-9132-f6a24f3fa60e.png)

![after back button](https://cloud.githubusercontent.com/assets/2153664/24832738/168245c0-1c6b-11e7-9990-9a8c7720d8e5.png)

![after back button 2](https://cloud.githubusercontent.com/assets/2153664/24832739/1bf9cd8e-1c6b-11e7-8fd0-6d8572687ce1.png)
