### ISSUE TITLE
Double annotation from the backend

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#708]
As a researcher/annotator I would like to have one annotation screen typing in one text - one category and picking annotation location in the *text* and *PDF image*.

**Comment by SamCCSI** [comment]
i.e.
Step 1. Write the annotation.
Step 2. Highlight the text to be selected for the annotation.
Step 3. Place a flag (for the annotation) on the PDF in the right place.

The value-add here is not having to perform Step 1 twice (once for text, once in PDF)

**Comment by anderspeders** [comment]
As per agreed on call today the scoping of the time costs to this should be included in this sprint.

**Comment by anjesh** [comment]
This seems a good idea, however this doesn't seem possible with the existing libraries we are using. We should be able to get this work by writing our own annotation plugin and that should fix most of the issues around annotations, which are constrained by the usage of annotator and annotorious. 

When the annotator goes to annotation space, he sees the following. 
![image](https://cloud.githubusercontent.com/assets/120488/11655797/b0c1fa58-9dd8-11e5-89e1-a542b9dc47d5.png)

He has to first create the annotation (just the category and the annotation-text).
![image](https://cloud.githubusercontent.com/assets/120488/11655805/c16fa6f2-9dd8-11e5-81f7-f1be071d72a1.png)

She chooses the category and fills the text.
![image](https://cloud.githubusercontent.com/assets/120488/11655843/f7f9baaa-9dd8-11e5-9095-1dcf4a571b5b.png)

After she saves the category and annotation, the edit mode gets on and he will be able to select content in the text. Any selection will popup the question to save the annotation - the reason being user might just select unknowingly, which will get attached to the created annotation. 

![image](https://cloud.githubusercontent.com/assets/120488/11655850/06804ed6-9dd9-11e5-859f-c037b3e3f8aa.png)

After selecting the text, she will see the highlighted text gets listed under the annotation on the left, with the option to mention the section info where the text is selected from. 

![image](https://cloud.githubusercontent.com/assets/120488/11655882/488ead7c-9dd9-11e5-9813-98594b410026.png)

He can still highlight text from other pages and the same process continues.

![image](https://cloud.githubusercontent.com/assets/120488/11655908/7fc1df08-9dd9-11e5-81fa-a2c032befb8d.png)

More text gets attached to the annotation. 

![image](https://cloud.githubusercontent.com/assets/120488/11655914/8dab1e18-9dd9-11e5-90df-14326d828b22.png)

She saves the annotation and edit mode is off. Now the user can't attach the text the annotation. The highlighting doesn't work now. 
![image](https://cloud.githubusercontent.com/assets/120488/11655926/b4f3ae72-9dd9-11e5-848d-dd5c199404e8.png)

To attach text to any annotation, she clicks "edit" link, which turns on "edit" mode again and any text could be now attached to the selected annotation.

![image](https://cloud.githubusercontent.com/assets/120488/11655946/d85e8224-9dd9-11e5-90fc-fc3dde0cd8b9.png)

Now he can switch to the pdf content and also being adding the selection to that particular annotation, where text is also attached. 

![image](https://cloud.githubusercontent.com/assets/120488/11655981/13775eee-9dda-11e5-8f73-0e07bc377383.png)

For the pdf selection, just the word pdf appears to let the annotators know that it's the pdf selection. 

![image](https://cloud.githubusercontent.com/assets/120488/11655995/30b9d752-9dda-11e5-9c43-51f584d32e3c.png)

The subsites will continue using the existing annotatorjs, but those could also be changed once we have this in place. The existing annotatorjs and annotorous plugins are big, and the subsites don't need them per se, as these lib are used just for viewing. 

This annotation module will take care of linking an annotation to multiple page issue, and also the issue of moving the pdf highlight area, changing area. We will have to write the module by us and should take somewhere between 6 - 10 days. We also need to take in account the process of migrating the existing annotation into the new annotation model. This would change the entire annotation data model as well.

**Comment by SamCCSI** [comment]
One tiny point: our current position regarding PDF annotation flags is that they should be a standard size and shape, and be placed at the beginning of the text that forms the basis of the annotation, rather than highlighting the entire text as in the mock-ups above. This is because:
1 - annotation module does not support annotation flags extending over more than one PDF page.
2 - annotation module does not support having multiple annotation flags for each annotation.

If the above two points are easily implementable then we would be happy to reassess this -- it would be really useful in making PDF and text based annotation flags / highlights look more similar, which will reduce the chances of causing confusion for users.

**Comment by SamCCSI** [comment]
Currently "edit mode" allows user to edit text of annotation, highlight annotation text, place PDF flag.

Perhaps it would be more intuitive to call it "Edit / Add annotation locator."

**Comment by anjesh** [comment]
> annotation module does not support annotation flags extending over more than one PDF page.

There are number of issues with the existing pdf annotation with the library we are using. I am still thinking about the continuous pdf pages during annotation - we need to load the entire pdf first, and then do the annotation that might extend from one page to another. That selection becomes a bit tricky becauase of the way pdf is rendered. We need to research and experiment on this, before confirming the possiblity of this particular issue. Other than this, i think all other issues could be solved with the new annotation UI and annotation model i have proposed above and this seems to be a little more intuitive (and also can be made more intuitive by adding more instructions during the annotation process something like - 
```you are in "Edit mode" - you may now select text/place pdf flag and link to the annotation```


> our current position regarding PDF annotation flags is that they should be a standard size and shape

That means we don't need to extend the highlight rectangle. The size of the pdf annotation-highlight-flag is fixed? And that means the flag won't extend to two pages. We will have two flags in two different pages for the given annotation. Something like this, where we can have as many flags to pdf as we want but linked to a given annotation. 

![image](https://cloud.githubusercontent.com/assets/120488/11680083/f86ccbb2-9e7d-11e5-8c9c-f0162e24ee14.png)

**Comment by SamCCSI** [comment]
Our current position regarding PDF annotation flags is that they should be a standard size and shape.

This is because:
1 - annotation module does not support annotation flags extending over more than one PDF page.
2 - annotation module does not support having multiple annotation flags for each annotation.
3 - we are not sure how overlapping flags would be presented (this will not be too frequent, but will occur from time to time)
4 - we are not sure exactly what the PDF flags will look like. Eg. if the text to be flagged covers an entire page, what would this look like?

@anjesh maybe some more mock-ups would be of assistance. Could you provide mock-ups that address my points 3 & 4?

Could you also provide a mock-up of how the flag would look if it extended across multiple pages?

cc @KaitlinCCSI @jesseccsi

**Comment by anjesh** [comment]
i am assuming flag as a rectangular box which you can move around or extend. The standard size is not going to help here. I am seeing this similar to what we currently have in the pdf annotation now, except that we are thinking of making those boxes able to drag by mouse, extend by mouse. 

For eg. 

This particular mockup of pdf annotation shows the flagging of content for "Country" category. The overlapping flags could be seen and identifiable by the border. There's one big flag that covers most text. However you will see that on the left side, all these flags are for Page 2. Since they all are representing the same annotation, they all appear under the same category. We can extend that flag to cover the entire page as well if that's the need.

![image](https://cloud.githubusercontent.com/assets/120488/11736143/d7f121e6-9ff2-11e5-8dff-5f3badf953cf.png)

With regards to the multi-page flagging, i am a bit skeptical about that becauase of the way the pdf is rendered. There will be space between two pages. 

There are two ways to flag - one is to flag in each page and place those flags under the given annotation as in 

![image](https://cloud.githubusercontent.com/assets/120488/11736501/348f0cfc-9ff7-11e5-83d4-bf9496387f7d.png)

This is how it looks if we extend the flag to two pages, but in practice, we need to see if this can be done or not, using pdf rendering libraries (pdfjs). This is something we can't commit to do without further research and experimentation. 

![image](https://cloud.githubusercontent.com/assets/120488/11736536/a0de73ac-9ff7-11e5-8c81-e9bbbe78cdc1.png)

**Comment by jedm** [comment]
Dear @anjesh,

I think this is a very good direction to explore for the annotation plugin you are working on. 

My recommendation for priorities would be 1) simplicity of UX for selecting "parallel" locations in the text and PDF image (maybe with 2 panes open at same time, for instance) and 2) maximum ease and stability on the back end for saving locations in images and corresponding location in text.

It may be easier, for example, to select the START and FINISH location in the PDF, rather than using a drag-select function. Sam noted that we seek consistency and good visuals in the display of flags/highlights, but the flag selection process for admins does not need to be WYSIWYG, as long as it is intuitive and reliable. 

To deal with the page break question in PDFs I can also imagine a check box for "multi-page" annotations. Since we have discussed a single annotation with multiple locations already, this would maybe just be an extension of the same functionality.

(@SamCCSI , please advise if anything above sounds bad to you.)

Also, @anderspeders and @KaitlinCCSI can elaborate but I think it will also help to have a _reasonably_ reliable estimate of what it will entail to create the new plugin. (I hope I am right that a new YI plugin for this can integrate text annotation and PDF annotation in a single interface, even if some duplication is required in the code itself!)

With thanks and regards from the holidays in the US!

Jed

**Comment by anjesh** [comment]
I am closing this in favour of https://github.com/NRGI/resourcecontracts.org/issues/694 
As per my earlier discussion with Anders, we will not be developing any new plugins from scratch but try best to make use of other open source libraries. The new mechanism to achieve multiple-page-linking-annotation is documented in wiki https://github.com/NRGI/resourcecontracts.org/wiki/Annotation-Module
