### ISSUE TITLE
Attaching multiple parts of contract to the same annotation

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#71]
As an annotator I need to be able to make an annotation that draws information from different clauses of the contract.

Eg. Art 7 says "Company must have an EIA". Art. 50 says "Company must pay a fine if it does not comply with EIA".

I want just one annotation that says: "The company must prepare an EIA and will be fined if it doesn't comply with it".

But I want the annotation to link physically to Arts 7 and 50.

Also I need the ability to link to more than two articles. One annotation could link to 5 different clauses.

**Comment by anderspeders** [comment]
I would propose that we deal with this in sprint 2 - at least to put together an alpha-version for how this could be solved.

**Comment by anderspeders** [comment]
@anjesh Any thoughts on this?

**Comment by anderspeders** [comment]
Current proposal for a solution: 

a) Have multiple annotations with a common tag that references for example environmental protectiion. 
b) Ensure that all tags under *environmental protection* in the contract can be easily browsable next to each other. 

c) Possibly also include an option to assign one annotation among the various annotation as the a primary/favorite/star annotation. This would enable a specific annotation to appear on top of the list among the similar tags. 

For example: 
Among three annotations tagged under *environmental protection* I wish to *favorite/star* one of these annotations as it includes a detailed string text summary of the envirnmental protection.

**Comment by anjesh** [comment]
During annotation process, the user can also group different annotations. There will be checkboxes besides each annotation. 
![image](https://cloud.githubusercontent.com/assets/120488/8447465/087bcd06-1fd9-11e5-95c2-cd8378d12078.png)

The user can select the annotations that are to be grouped. By default the annotations don't belong to any group hence uncategorized.
![image](https://cloud.githubusercontent.com/assets/120488/8447466/0c5bd72c-1fd9-11e5-87f2-74e470643ebb.png)

After selection of the annotations, the user click "group" button to add the description for the grouped annotations. 
![image](https://cloud.githubusercontent.com/assets/120488/8447467/0fc66e40-1fd9-11e5-94ef-1731a8ed6634.png)

Now the annotations are grouped under a given description. 
![image](https://cloud.githubusercontent.com/assets/120488/8447468/1504994a-1fd9-11e5-8bab-5401374b359b.png)

This grouping will have implication on the existing API services, changes in database and writing the annotation management interface, which happens outside of annotatorjs. 

Thoughts? @anderspeders

**Comment by byndcivilization** [comment]
my understanding of this issue is thats its really about tagging an annotation to multiple parts of a source text. Why not have a model where a single annotation is linked by id to multiple places. I think you're already storing annotations as a table, so just use a link table or link id to connect these. Since the annotations aren't really free form but adhere to a strict typology (i.e. stabilization clause, env protection, etc) you could even prepopulate empty annotations on document upload.

**Comment by anjesh** [comment]
The annotations are stored in a format annotatorjs generates and we add id. This format is to be maintained to make annotatorjs work.
```json
{
  "text": "A note I wrote",                  
  "quote": "the text that was annotated",
  "ranges": [                                
    {
      "start": "/p[69]/span/span",   
      "end": "/p[70]/span/span",    
      "startOffset": 0,                    
      "endOffset": 120                  
    }
  ],
  "tags": [ "review", "error" ],
}
```
The challenge is linking this to another piece of text in different pages of the contract. My current proposal was grouping the annotations in different pages (outside of annotatorjs) so that we don't break the existing annotatorjs process. 

Like you said, if we have strict typology we could introduce  [category plugin](http://annotatorjs.org/plugins/index.html) apart from tags, which would be the basis for the grouping of these annotations. The researcher first annotates one section of the document and gives "stabilization clause" category and also adds free text (might or mightn't add tags), then annotates another part and just selects "stablization clause". They could be then grouped by the categories they are assigned.

**Comment by anjesh** [comment]
Annotations are now grouped by category. However there still seems to be more improvements to be made #113 #112

**Comment by byndcivilization** [comment]
I think we need to reopen this as it is also an issue with multipage annotations. I think your best bet is to do this at the api level. The issue as i see it is that annotator expects to see annotations in a 1 to 1 format but we need to store and manage in a many to one format. So on load, the api should extract annotation content (title, text?), create master annotation record, add with master id to annotation record. On read, you basically reverse the process and propagate out to children annotations. My worry is that the current system looks to be maintaining multi annotation records that will need to be maintained separately.

If my read is incorrect, please correct me.

**Comment by anjesh** [comment]
The annotations are grouped by category. So though they are stored separately, they appear under the given group. Anytime the user can see what are different annotations under different heading and adding new annotation will inject that under the given heading despite any page in the contract. The concern you have put forth may have been addressed by current implementation. Lets discuss. 

The entire annotation list is accessible from annotations button on the top-right

![image](https://cloud.githubusercontent.com/assets/120488/9172820/bbecba9a-3f95-11e5-87ac-c5a86eb075de.png)

**Comment by anjesh** [comment]
superseded by https://github.com/NRGI/resourcecontracts.org/issues/694
