### ISSUE TITLE
Mech Turk workflow broken

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#717]
![image](https://cloud.githubusercontent.com/assets/1101585/11634478/bfba244a-9cde-11e5-85c6-e962d13e9dd9.png)

When I try to approve a task in mech turk I get an error message. I get this error with a number of documents - so not just a single issue. Why is that?

@SamCCSI @KaitlinCCSI Suggest we add this to current sprint as a matter of urgency.

**Comment by anderspeders** [comment]
This si an example: http://resourcecontracts.elasticbeanstalk.com/mturk/1213/1361

**Comment by SamCCSI** [comment]
Agree this should be added to the current sprint.

I have been reporting every time we encounter this error here: https://github.com/NRGI/resourcecontracts.org/issues/626

**Comment by anjesh** [comment]
There has been a problem in a logic when the task (which are older than 10 days and for which the assignments are not submitted yet) is expired and a new task is created in its replacement. This was done to ensure that the contracts don't remain incomplete incase some workers accept the task but doesn't do the transcription. Due to the logical problem, we are suspecting that the tasks got auto-approved by Mturk when pulled from their system. Those are the tasks (that you have reported) which couldn't be approved, as they have already been approved in the MTurk but not yet approved in our system (so we can see the approve/reject button). We have autoapproved all those tasks directly int he database and hoping that such situations shouldn't arise from now on.

**Comment by SamCCSI** [comment]
We just received this email from a MT transcriber:


---------------------------------
Customer ID: ALFBBRNBNW31B
Hi,

     I find many HITs posted by you on this platform.  But on accepting the HIT, the right side part of the HIT is neither opening up for reading nor able to download.  Hence I am constrained to return many HITs posted by you after accepting them.  Please look into the matter and set it straight.

**Comment by anjesh** [comment]
So far we haven't seen any instances of such errors now. Please re-open if you are not able to approve/reject the HIT assignment.
