### ISSUE TITLE
Upload size - need to expand size beyond 100mb

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#718]
As an administrator I will need to upload a contract of more than 100mb. 

Based on user request from both PH-EITI and CCSI for Mozambique contracts. 

It is unclear where the current upload limit is, but there are certainly arriving reports based on size limits.

Conversation started in email by @charlesyoung @anjesh

**Comment by charlesyoung** [comment]
Linked to 'System configuration', #697

**Comment by anjesh** [comment]
We have increased the php memory limit from 256MB to 2GB for now, and were able to fix the upload size issue. We tested with 124MB and were able to upload the file.

![image](https://cloud.githubusercontent.com/assets/120488/11737128/2f6ae1ea-9ffe-11e5-8274-82c9ee327c62.png)

We were looking for other configurations and turned out to be a simple fix later.
