### ISSUE TITLE
Translated Contract - document type?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#745]
What is best practise for indicating when a contract appear as a translation of the original. 

Use case: 
As X government agency we wish to publish contracts and related documents in the official language and in the language of locally impacted comminities. 

@jpmckinney Any thought here?

**Comment by jpmckinney** [comment]
In the schema, there is currently a boolean property `translation_from_original` (proposed renaming to is_translation). However, this doesn't establish any link between the translation and the original.

In general, it depends on whether the two versions of the contract have the same force. In Canada, laws are in English and French, and both have the same force. In some jurisdictions, they may translate laws to make them more accessible, but only the official language version is in force.

If the two documents have the same force, then you can just tag the language for each, and maybe add a link between them (e.g. in RDF, it would be `owl:sameAs` or [`schema:sameAs`](http://schema.org/sameAs)), so that people know that they are, conceptually, the same document, but in different languages.

If one is a translation of the other and has less force, then the relationship is not "same as" but "derived". Dublin Core has [`source`](http://dublincore.org/documents/dcmi-terms/#terms-source) but that's a confusing name. The [W3C Prov (Provenance) Ontology](http://www.w3.org/TR/prov-o/) has `wasDerivedFrom`.

**Comment by anderspeders** [comment]
I would assume that most of the use cases will relate to "was derived from". 

@samCCSI @KaitlinCCSI ?

**Comment by SamCCSI** [comment]
There are some DRC RC contracts where both ENG and FRE versions are listed as official versions & presumably therefore have the same force.

We also have unofficial translations of contracts, which, as Anders suggests would come within the "derived from" category.

One question: we can only have one "main contract", so how do we decide on which is the "main" contract in circumstances like the DRC contracts, where both are considered official and presumably have equal legal force?

**Comment by anderspeders** [comment]
Getting to this a bit late. 

I would suggest that the uploader can make an executive decision? I would not find this very controversial.

**Comment by byndcivilization** [comment]
agree with @jpmckinney but can't we just have a single flag for "derived". Relationship is basically binary (i.e. equal or not). On new contract load for the translation we can add "derived" and "translation_of" of data to new contract record and update existing contract record with appropriate "derived" and "translation_of" data.

**Comment by anderspeders** [comment]
Sounds good to me. 

@anjesh: Is this significant direction?

**Comment by anderspeders** [comment]
Re-capping this conversation so that we can move this forward. 

Decisions: 
- RC / OLC contain normally only one ruling contract. Therefore the relationship is **derived** not **same as**
-  `is_translation` will be used for this 
- document the change in the wiki

@anjesh, @manishgs: please confirm that we can move this forward.

**Comment by manishgs** [comment]
As per above discussion.  Following are the to-dos:
- Add new field `is_translation` having radio buttons  `yes` and `no` (default is `no`)  in contract  form.
- Update API
- Run bulk index
- Display the field on contract summary page (subsite).

Do we need contract drop down list to choose main contract if `is_translation` selected? @anderspeders @jpmckinney @SamCCSI

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
