### ISSUE TITLE
Contract Metadata publishing workflow

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#75]
The contract metadata will go through the workflow before it gets published and available for search/view in the sub-sites for the public. Here's the suggested workflow.

There will be 3 states of the contract - Draft -> Completed -> Published

Researcher uploads contract with metadata and file -> Draft
Researcher makes edits to the metadata -> Draft
Researcher marks it as complete -> Completed
Admin sees the contract is complete and sees button to publish -> Completed
Admin clicks "publish it" -> Published

Anytime researcher can make edits, at that instant, the state changes to Draft and the same workflow will continue.

When the contract gets to Published state, the contract metadata gets pulled and sent to ElasticSearch for the public consumption. When the re-edited contract gets published, then that information is again updated to Elasticsearch, until then previously published contract will be searchable and displayed in the subsites.

cc @anderspeders

**Comment by anderspeders** [comment]
Any concerns about this work flow @samccsi?

Note that the annotation workflow will be outlined elsewhere.

**Comment by SamCCSI** [comment]
That sounds fine @anderspeders as long as the annotation and metadata workflows are effectively 'fused'.

We don't want to have any contract live on the site until it is fully annotated, and we don't want to have to 'publish' it with the metadata and then 'publish' again with the string annotations. As long as the final process will allow metadata and annotations to be done at the same part of the process it should work.

Also, is there scope for the Admin to send the contract back to the researcher if amendments to annotations/metadata need to be made, and the the admin can finalize and publish? This is key to our workflow.

**Comment by anderspeders** [comment]
For RC.org we will need the process of annotation and metadata addition to be split. For example - on the current RC.org a few hundred contracts are published with metadata only, while approx. 150 are published with full annotations. 

For OLC there will be no administrative extra time required of having a step by step process - for first metadata, then annotations. And importantly - CCSI will be free to publish the contract at exactly the time you prefer - after the full annotation process.

For the user story below I would ask if you could describe what kind of work flow you would prefer in a separate issue ticket - how you would like as a researcher and administrator: 
"Also, is there scope for the Admin to send the contract back to the researcher if amendments to annotations/metadata need to be made, and the the admin can finalize and publish? This is key to our workflow." In that way we will make sure that it is being addressed. 

Let me know if that works?

**Comment by SamCCSI** [comment]
I am worried that having the metadata and annotation processes split will involve duplication of process and more clicks for annotators and reviewers. Would it be possible to have the workflow as follows:

Researcher uploads contract with metadata and file -> Draft
Researcher makes edits to the metadata -> Draft
Researcher makes annotations - > Draft
Researcher marks contract as complete -> Completed
Admin sees the contract is complete and reviews the metadata and annotations -> Completed
If needed, Admin notes any revisions that need to be made and marks contract as draft -> Draft
[this process might happen numerous times]
Admin clicks "publish it" -> Published

**Comment by SamCCSI** [comment]
@anderspeders 
I am worried that having the metadata and annotation processes split will involve duplication of process and more clicks for annotators and reviewers. Would it be possible to have the workflow as follows:

Researcher uploads contract with metadata and file -> Draft
Researcher makes edits to the metadata -> Draft
Researcher makes annotations - > Draft
Researcher marks contract as complete -> Completed
Admin sees the contract is complete and reviews the metadata and annotations -> Completed
If needed, Admin notes any revisions that need to be made and marks contract as draft -> Draft
[this process might happen numerous times]
Admin clicks "publish it" -> Published

**Comment by anderspeders** [comment]
thanks @SamCCSI 

RC.org will need a publication process that is split between metadata and annotations. Else, RC essentially need to pull more than 50% of the current (unannotated) contracts off the site, so that would not be a feasable option. 

Separately we can address the the need for the having the contract unpublished until fully annotated as an option. In terms of fear of dublication I am glad to address this, but ask that we do that based on user feedback to the actual alpha model.

**Comment by anjesh** [comment]
Inview of above discussion, I have slightly changed the process and added "rejected" state. "Rejected" might not sound good and could be replaced with "Change suggested", however for clarity, i have used "Rejected" now. The admin may only decide to publish the contract and annotations if both are completed, or admin may publish one before another. 

--- 

As soon as the researcher uploads the contract and as soon as the pdf processing completes, she will see all three are in "Draft" state and options to mark them complete. Please note that annotations could also be taken action from this interface as well as a separate interface where Admin/Researcher can see the annotations in one page. Researcher might decide to complete one or more. 

![image](https://cloud.githubusercontent.com/assets/120488/8225222/c5becd96-15b1-11e5-8614-dd140483fcc9.png)


![image](https://cloud.githubusercontent.com/assets/120488/8225226/cc913046-15b1-11e5-8720-aa98df840469.png)

Admin sees the state of different block and option to reject if admin thinks some changes are required. 

![image](https://cloud.githubusercontent.com/assets/120488/8225234/d97b15e2-15b1-11e5-9075-6a4ec1d18a8d.png)

In case of rejection, admin will have to add comments for the changes. Admin will also have option to change the information/metadata himself if he wants and just publishes if after the self-editing. 

![image](https://cloud.githubusercontent.com/assets/120488/8225238/dcfc91aa-15b1-11e5-94e2-baa4c4595dcd.png)

Incase of rejection, there will be a small icon, which shows what the admin has commented. 

![image](https://cloud.githubusercontent.com/assets/120488/8225239/e0960f58-15b1-11e5-8403-81d022246fb6.png)

Researcher sees the comments and edits accordingly.

![image](https://cloud.githubusercontent.com/assets/120488/8225250/f4ec7fa0-15b1-11e5-8124-4c8b8ea0eed8.png)

After the edits, the state changes back to draft and with the button to mark it complete.

![image](https://cloud.githubusercontent.com/assets/120488/8225255/f88d8992-15b1-11e5-9673-5682a4a69a4c.png)


![image](https://cloud.githubusercontent.com/assets/120488/8225256/fc183c60-15b1-11e5-84b3-281fc353730b.png)


![image](https://cloud.githubusercontent.com/assets/120488/8225258/0021ba70-15b2-11e5-8a96-8b5f862c676c.png)

Finally admin publishes the metadata.

![image](https://cloud.githubusercontent.com/assets/120488/8225260/03bc4790-15b2-11e5-8286-2184d7a1c024.png)

Research may still edit the metadata, after which the state changes back to draft and the process goes back to the beginning.

**Comment by SamCCSI** [comment]
Thanks very much, @anjesh for seeking to incorporate some of the workflow concerns.

As an admin, I need to be able to put a comment beside each metadata entry or annotation entry, rather than only having one comments section for all metadata. This is because comments will always relate to specific clauses. I also need to be able to write general comments about missing annotations / metadata. The workflow you have already proposed meets this latter need (but not the former need for notes for specific metadata cells / annotations).

As Researcher, I need to be able to see the admin's comments on my annotations side by side with the annotation itself for ease of reference.

As a Researcher I need to be able to enter my own notes in the same format to alert the admin as to specific issues.

@anderspeders given this thread, I assume I don't need to create a new thread as you requested in #52 

Finally, @anderspeders I still don't see why metadata and annotations need to be separated. Even for the contracts currently online with no annotations, surely they can still be online, just with the fields of the annotations blank or absent. This separation makes sense for you, but for annotators it is just another step they will have to do, which makes the process last longer, both for Researchers (annotators) and Admins (reviewers). Are there other reasons why you want it to be separated? It would help me to understand if you could speak more about your motivations - that would be appreciated.

**Comment by anjesh** [comment]
Closing this issue. Created  Sam's suggestion as new issue #101 for future.
