### ISSUE TITLE
Annotation comment box paragraphing feature

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#763]
Can we allow for paragraphing in the annotation comment box as this is currently not allowed?

Request from PH-EITI.

**Comment by anjesh** [comment]
By paragraphing, do you mean editor (where one can type ENTER) instead of textarea that we currently have?

**Comment by charlesyoung** [comment]
Yep

**Comment by SamCCSI** [comment]
Related request (based on CCSI's experience liaising with those entering metadata): Can we change the color scheme so that it is more obvious when there is a comment to be responded to? It is confusing to have the comment box red when there is no comment and when there is an unresolved comment.

![image](https://cloud.githubusercontent.com/assets/12913915/13301323/5f72325e-db12-11e5-9815-ecc8bb4b1732.png)


Suggestion:
When no comment entered, color = Grey.
When comment(s) entered and not resolved, color = Red.
When comment(s) entered and resolved, color = Green.

**Comment by manishgs** [comment]
Both paragraphing feature and color changes of comment box have be done.

**Comment by SamCCSI** [comment]
@manishgs this will be very helpful. Thank you.
