### ISSUE TITLE
Confusion over Government entity JDA 

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#786]
Currently it uses the country full name which makes it difficult to query. It could be made easier using the ISO 3166-1 country code (see http://iatistandard.org/201/codelists/Country/). And also the names of the narrower concepts are in lower case. Is there any specific reasons for this? 

From the db, we see that entity is mentioned as "PERUPETRO S.A." which matches against "perupetro sa" in the jda. Need to discuss on this with Beata.

**Comment by lisssek** [comment]
we create concepts in a consistent manner: all lower case, no punctuations for the uniformity of our database and URIs (we use the concept names to create our URIs ). The name "as is" or was found within your db can be found under altLabel. We can change the preferred name from country name to ISO, this is up to you.

**Comment by anderspeders** [comment]
@anjesh: What is your recommended path forward here?

**Comment by anderspeders** [comment]
I'd suggest the following: 
@anjesh: Pull a list of all government entities | contract ID

We will then harmonize the list and return it to YI for upload (as we will do for the companies list). Does this sound good?

**Comment by lisssek** [comment]
We are happy to do the upload for you the harmonized list of gov entities  and even create a new project with rules defined by you if needed (ISO as URIs).

**Comment by anderspeders** [comment]
@anjesh @manishgs Could you please pull a list for government entities?

**Comment by hello-deepak** [comment]
Currently following steps have taken to pull government entities:

We are using  this   [api](http://joinedupdata.org/PoolParty/api/thesaurus/1DCE5BA4-B07D-0001-17D3-93C6F01F18F4/childconcepts?parent=http://joinedupdata.org/NRGI/4c61a3a0-8c34-4391-976d-4065f9d47340&properties=skos:altLabel,skos:narrower&transitive=true) to extract government entities.

* We have taken the prefLabel as country where narrowers are defined.
![narrowers](https://cloud.githubusercontent.com/assets/7577697/15607008/65c532da-242f-11e6-9aa0-3fd6f98a3d69.png)

* Matching its narrower uri and extracting its prefLabel as government entities.
ie. Here afghanistan have two government entities. 
af : ["the ministry of mines","ministry of mines and petroleum"]

### Sugestion 
Some of prefLabel for country does not match our country code configuration . 
So, can we have standard country [code](http://iatistandard.org/201/codelists/Country/) rather than country name to categories government entities?

And some government entities jda does match exactly from database of rc. 
Here is [spreadsheet](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=1708686393)

**Comment by hello-deepak** [comment]
@anderspeders @lisssek . Any update?

**Comment by charlesyoung** [comment]
@anderspeders is this still required?
