### ISSUE TITLE
Mock up requested for new annotation module - how will this look on the front end?

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#791]

**Comment by anjesh** [comment]
The annotation frontend will be same as that of admin. Hovering over any annotation will show the links to the related annotations to other pages as well. 

![image](https://cloud.githubusercontent.com/assets/120488/13460374/3da2a222-e0a2-11e5-8b0a-3fab3ecfbcac.png)

We haven't made that change to the frontend as of now, as we are waiting for the final decision on the data model and process at the backend. Once that is finalized, we will start work on the frontend, as it requires changes in number of places in the codes - in the API and the subsite for the new model.

**Comment by manishgs** [comment]
Below is the screenshot displaying how annotations are listed in contract summary page.

![screenshot from 2016-03-03 13 27 52](https://cloud.githubusercontent.com/assets/3942999/13487683/e438cce6-e143-11e5-9fac-2478a6981cec.png)

We've a confusion for annotation count. Can you please confirm the total annotations (4 or 3) from above image?

**Comment by SamCCSI** [comment]
@manishgs 3

**Comment by anderspeders** [comment]
@manishgs: Please let us know if you need additional feedback here?

**Comment by manishgs** [comment]
We are waiting for your confirmation on new annotation module. if you are okay with this then we can work on API and subsite to reflect new annotation module

**Comment by manishgs** [comment]
Mockup for Annotation listing on contract summary page

![annotations-doc-summary](https://cloud.githubusercontent.com/assets/3942999/13668931/227fd176-e6e8-11e5-9f2e-631487487b80.png)

**The annotation section will act as follows:**

Left side of the screen has a navigation block that will help to navigate to a specific cluster.  This block will remain fixed in the left side of the browser and will always be visible when the user scrolls within the annotation section. Right side has the annotations. The page will scroll on clicking a cluster name (say Fiscal) and will take the user to that particular cluster’s (Fiscal in this case) annotations. In the screenshot, “General” cluster is highlighted meaning the user is currently seeing General cluster’s annotations. As and when the user scrolls and reaches to other clusters, the highlight will be switched to another cluster accordingly.

**Contract view page**
![annotations-sidebar](https://cloud.githubusercontent.com/assets/3942999/13668932/22820d1a-e6e8-11e5-95ea-a76a1fcff25b.png)

**Comment by anderspeders** [comment]
@SamCCSI @KaitlinCCSI: Could you have a look?

**Comment by manishgs** [comment]
New annotation module has been implemented so closing this issue.
