### ISSUE TITLE
Cannot open PDF's 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#797]
Not sure if this is just on my side but no PDF's are loading.

**Comment by manishgs** [comment]
Which page are you referring? Could you please share the screenshot?

**Comment by charlesyoung** [comment]
Its the whole document. Can you open this PDF? 

http://www.resourcecontracts.org/contract/ocds-591adf-PE6396832160RC/view

**Comment by manishgs** [comment]
This contract was already deleted from admin on "2016-01-07 17:02:53" but wasn't removed from subsite. We'll remove this contract from subsite and we will verify and remove other contracts which was deleted from admin but still shown in subsite.

**Comment by charlesyoung** [comment]
What is the workflow re deleting contracts from admin and the resulting impact on the RC public site? It's concerning that deleted contracts are still visible on the RC public site.

**Comment by manishgs** [comment]
When we delete contract from admin it also get deleted from elastic-search database and it will not show in subsite.

Some were not deleted due to mismatched of indexing api in admin site. We will be deleting those contracts from elasticsearch database.

We found following contracts were deleted from admin but still showing in subsite.  
http://www.resourcecontracts.org/contract/1298/view
http://www.resourcecontracts.org/contract/149/view
http://www.resourcecontracts.org/contract/1314/view
http://www.resourcecontracts.org/contract/1290/view
http://www.resourcecontracts.org/contract/1273/view

**Comment by charlesyoung** [comment]
Thanks @anjesh. How can we ensure that this doesn't happen again?

**Comment by hello-deepak** [comment]
We have deleted above contracts from elasticsearch database.

This is due to mismatch of elasticsearch index api during deployment . We have taken some preventive measure while deploying, so it wont happen again.
