### ISSUE TITLE
Resource list containing similar values (like Other, other, ...)

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#809]
Although 'other' has been removed from the backend resource drop down list there are however still contracts with 'Other', 'other', 'Other minerals' and 'other minerals' resources. Should we change these to 'Other Minerals'? 

![image](https://cloud.githubusercontent.com/assets/13888372/13629528/5f1e78aa-e5e2-11e5-9648-a99c84e0ec66.png)

**Comment by hello-deepak** [comment]
Resource field is free text in admin part . So user can also type text and submit rather than selecting from  resource drop down .
![resource contracts](https://cloud.githubusercontent.com/assets/7577697/13983217/6cb160a6-f116-11e5-9341-a9a9c46308af.png) .


We do not have "Other minerals" in resource drop down. So please confirm about changing 'Other', 'other', 'Other minerals' and 'other minerals' to 'Other minerals'  in database.

**Comment by hello-deepak** [comment]
Resource field is free text in admin part . So, unless this field is filled with proper selection from drop down or free text , this problem can rise again.

Closing this issue for now.
