### ISSUE TITLE
Metadata changes not reflected on frontend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#838]
From our researcher:

Under “Resources” we shifted all “platinum” tags to “platinum group metals”. However, one contract still appears on the frontend as “platinum”. If you go into that same contract though on the backend, it is clearly tagged “platinum group metals”

Frontend: http://www.resourcecontracts.org/contract/ocds-591adf-PH9167186836RC/view
Backend: http://resourcecontracts.elasticbeanstalk.com/contract/90

A similar issue exists with YPFB Pluspetrol – Bolivia, 2006. I changed the tag under “contract type” to “service contract” and it says “service contract” on the backend. But it still appears under “service agreement” on the frontend

Frontend: http://www.resourcecontracts.org/contract/ocds-591adf-BO0262708026RC/view
Backend: http://resourcecontracts.elasticbeanstalk.com/contract/987

**Comment by manishgs** [comment]
Its fixed for "Zambales Diversified Metals..." contract when I publish it. Now showing "Platinum Group Metals" on frontend.

For contract  "YPFB Pluspetrol ..." there is an error while indexing in Elastic search due to invalid date format. Please update signature date 2006-10-00 to valid one and publish it.
