### ISSUE TITLE
Clips - questions re. Annotation view, download

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#851]
![image](https://cloud.githubusercontent.com/assets/1101585/14536510/c0dd2274-0240-11e6-8958-013689c11a43.png)

For the annotation clipping we will need to understand if the following options from the spec document submitted can be included: 

1) Can **download file,** include a column with the direct URL links to each clipped annotation: for example: http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/8/annotation/829

2) Per "View" column in attached image from spec, can user launch a pop-up image (daughter window) showing original PDF page with each annotation? (This would **not** be a full viewer like the Contract page, only scrollbars.)

3) For each clipped annotation, can original PDF page be included in a "bundled" PDF that **downloads with the CSV/XLS** download?

**Comment by jedm** [comment]
_edited above post to add some details and clarifications_

**Comment by manishgs** [comment]
> 1) Can download file, include a column with the direct URL links to each clipped annotation: for example: http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/8/annotation/829

Yes , we can include annotation link

> 2) Per "View" column in attached image from spec, can user launch a pop-up image (daughter window) showing original PDF page with each annotation? (This would not be a full viewer like the Contract page, only scrollbars.)

I've a question for clipping an annotation. An annotation is linked to multiple pages, For example, following annotation is linked in 3 pages. In this case user going to clip only one annotation or clip individual page annotation?

Category - Local development agreement//Convention de développement local 
Text - MEGABOIS doit réaliser les infrastructures socio-économiques et des services sociaux au profit des communautés locales et/ou peuples..... 
P 3 - Arts 1
P 4 - Arts.2
P 7 - Arts. 3


> 3) For each clipped annotation, can original PDF page be included in a "bundled" PDF that downloads with the CSV/XLS download?

CSV/XLS file can have only pdf download link.

**Comment by jedm** [comment]
@manishgs:

- Great that the download can include a column with direct URL for each annotation!

- Our suggestion provided previously was to include the URL for the FIRST page in a multiple-page annotation (@KaitlinCCSI please confirm that for the download of clippings this is acceptable.)

- The question is not about embedding a PDF _inside_ a CSV. The question is:
a) Can the 1-page image of the PDF page that has the annotation be included for "View" (right side of image attached by @anderspeders)
b) Can the complete set of PDF pages with each clip/annotation be "bundled" (concatenated) and included as a separate file for download (e.g., a Zip or RAR with the CSV _and_ the PDF excerpts

**Comment by manishgs** [comment]
> a) Can the 1-page image of the PDF page that has the annotation be included for "View" (right side of image attached by @anderspeders)

Yes, we can create a new window screen having few features for view.

>b) Can the complete set of PDF pages with each clip/annotation be "bundled" (concatenated) and included as a separate file for download (e.g., a Zip or RAR with the CSV and the PDF excerpts)?

Do you mean each pdf of clip annotations concatenated to one pdf file?

**Comment by jedm** [comment]
> Do you mean each pdf of clip annotations concatenated to one pdf file?

Exactly. 😄 For each annotation marked in "SELECT" column, the PDF showing the annotation is viewable in "few features" popup from "VIEW" column, then ...

**ALL** PDFs of selected annotations are concatenated into one PDF file and concatenated file is bundled with CSV.

**NEW SUGGESTION** Maybe some users will want the PDFs and some will not (due to file size, use case, etc). Therefore, DOWNLOAD option should offer a menu the same way it does in other places:

- CSV
- CSV plus PDF excerpts

**Comment by manishgs** [comment]
For option "CSV plus PDF excerpts" it might take time to bundle pdfs depending on number of pdfs so 
Do we need to create zip file on the fly or will do background processing and email it to user?

**Comment by jedm** [comment]
Email of PDF is maybe better than a zip file. The group will need to give opinions. If we do not request email anywhere else it is probably better never to request. 

Most important is that the UX and UI make the options clear so that user:

- can choose CSV only or CSV+PDF originals
- sees a clear, accurate message on screen about what is downloading and what requires more steps to receive

@kaitlinccsi @charlesyoung do you have opinions?

**Comment by anderspeders** [comment]
I do not have a strong preference. For the download option I would think that a zip file would be useful given that this provides instant download (in comparison to email).

**Comment by KaitlinCCSI** [comment]
Sorry for slow response on this. Sam will respond soon re the PDF pages. In terms of downloads, I would lean towards NOT requiring email addresses if possible.

**Comment by SamCCSI** [comment]
Regarding the previous suggestion to include the URL for the FIRST page in a multiple-page annotation: whether this will be effective this hinges on the functionality of the pop up page.

If the PDF page that pops up doesn't have the arrow buttons to allow the user to change page, this might be difficult for the user. Not only for annotations drawing for different parts of the contract, but also for annotations tying to one provision that runs over multiple pages. If it does allow the user to change page, however, then it might work. Even better would be for the pop up to indicate other pages (even with hyperlinks) to that the user can be taken to all.

For the download option, including a hyperlink to the first page only would be fine, provided that it would take the user to the regular site (rather than a pop up), which would show the annotation, which would include links to the other source pages.

**Comment by jedm** [comment]
Based on the notes in #861 we may have other options for how multi-page annotations are listed. For the PDF download I think that the first instance remains acceptable.

But since we are seeking some clarification on several elements of Clipping function, we can revisit this in the context of that forthcoming conversation.

**Comment by hello-deepak** [comment]
Please review clipping in demo [site](http://rc-site-demo.elasticbeanstalk.com/rc/public) .

**Comment by hello-deepak** [comment]
Please use #893 issue for any further discussion.
