### ISSUE TITLE
Clips - Columns requested for comparing annotations clipped

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#861]
Per specs provided in PDF, these are the columns that should display for comparing selected Clips. This display should be in same design style as search results pages.

NOTE: Although these are the columns recommended for display/compare, a larger number of columns should be provided in the **download file.** @anderspeders has previously provided specifications for default columns and column order for download file.

![rc_olc_clipping_ux_1 5d](https://cloud.githubusercontent.com/assets/2153664/14578575/6ccc58f2-0340-11e6-95d9-ad5d8133397f.png)
  
See also #552, #851, #785, #789

**Comment by manishgs** [comment]
@jedm  

I've few changes on above UI. 

- Delete column for deleting each clipped annotation
- View button removed.
- Annotation column contains multiple pages so when clicking links open new window to show text/pdf of relevant page.



Select | Contract | Country | Year | Resources | Annotation | Delete |
-------- | -------------- | -------------| -------- | -------|--------|-----|
[ ] | DRC, Megabois, Contrat de concession forestière, 13 dec.. |  Congo  | 2014 | Timber | Clip Size of concession area//Superficie de la concession  <br>[P 1 - Art. 2](http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/1/annotation/2861) <br>[ P 9 - Arts. 25, 31](http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/9/annotation/1116) <br> [P 10 - Arts. 7, 26, 27, 30](http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/9/annotation/1168) |X

**Comment by jedm** [comment]
@manishgs please clarify:

- There is no request involving "deleting each clipped annotation" - where does this suggested column come from?

- The 6th column in the spec at top has the FULL TEXT of the annotation. This is necessary because the Clips feature is supposed to be a tool for **visual comparisons** of annotations. 

- Maybe it is a good idea to remove the View column and put the links in the "Annotation" column, but because the Annotation Text is a necessary column it may be better to keep the View column and link only to the FIRST pdf location of the Annotation 

- View button is also important because it allows user to visually **compare** multiple originals on their screen. This was an important element of the proposed function. I am happy to send the original PDF again if it would help. The View button functions are spec-ed on page 7 of that document (page is pasted again below).

![rc_olc_clipping_ux_1 5p7](https://cloud.githubusercontent.com/assets/2153664/14594276/8da65aa0-04e9-11e6-951f-2d7e2ff26b46.jpg)

**Comment by manishgs** [comment]
> There is no request involving "deleting each clipped annotation" - where does this suggested column come from?

We thought it will be useful to have remove button so we suggested. if not required then we can remove.

>The 6th column in the spec at top has the FULL TEXT of the annotation. This is necessary because the Clips feature is supposed to be a tool for visual comparisons of annotations.

Okay we'll include only full text of annotation on annotation column.

> Maybe it is a good idea to remove the View column and put the links in the "Annotation" column, but because the Annotation Text is a necessary column it may be better to keep the View column and link only to the FIRST pdf location of the Annotation

Okay we'll have view button and link to first pdf/text annotation

**Comment by anderspeders** [comment]
Hi @manishgs, please see below adjusted proposal: 

Select (and deselect) | Contract | Country | Year | Resources | Annotation | View |
-------- | -------------- | -------------| -------- | -------|--------|-----|
[ ] | DRC, Megabois, Contrat de concession forestière, 13 dec.. |  Congo  | 2014 | Timber | Clip Size of concession area//Superficie de la concession  <br>[P 1 - Art. 2](http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/1/annotation/2861) <br>[ P 9 - Arts. 25, 31](http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/9/annotation/1116) <br> [P 10 - Arts. 7, 26, 27, 30](http://rc-site-demo.elasticbeanstalk.com/olc/public/contract/ocds-591adf-CD1063510722OL/view#/pdf/page/9/annotation/1168) |X

**Comment by anderspeders** [comment]
@anderspeders to provide clarification on the columns which should be available for download.

**Comment by hello-deepak** [comment]
Please review clipping on [demo](http://rc-site-demo.elasticbeanstalk.com/rc/public).

Clip can be done in
* contracts [detail page](http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-PH6493643447RC)
* Contract [view page ](http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-PH6493643447RC/view)

Clip View 
http://rc-site-demo.elasticbeanstalk.com/rc/public/clip/view

**Comment by SamCCSI** [comment]
CCSI Feedback

- received an error message regarding a store when I opened up the contract view page

 

UX

- working off the contract summary page, I feel like this just takes me in circles. For example, I clipped 5 annotations on summary page. When I then went to look at my clips, I was taken to a clippings page. On that page, when I clicked on a contract name, it just re-opened up the contract summary page. When I click on the "view" button, it just takes me to the annotation in the contract view page. I'm not quite sure how either of those functions benefit me? The most beneficial seems to be the "Text" column that can be expanded, but (1) it is fairly narrow, making comparisons more difficult, and (2) text doesn't always show up. (See screenshots.)
![screen shot 2016-05-05 at 11 23 46 am](https://cloud.githubusercontent.com/assets/12913915/15057451/ddfcc170-12e4-11e6-8e25-59c483cf9e00.png)
![screen shot 2016-05-05 at 11 25 48 am](https://cloud.githubusercontent.com/assets/12913915/15057459/e3a2b116-12e4-11e6-85a0-44af396c1613.png)

- I think it makes sense for "View" to take the user to the annotation on the contract view page. That seemed to work quite well when I was testing. However, I don't think it makes sense for the title of the contract to take you to the summary page. I would change the hyperlink so that it also takes you to the contract view page. 

- In addition to making the text column wider and deeper, we need to regulate when the "more..." function kicks in. Ideally the text should only be shortened and the "more..." functionality added for really long annotations, otherwise it takes many more clicks to have the annotations (in full) side by side.

- The view icon links nicely to the relevant annotation.


Comparing

- the most useful part about clipping seemed to me that you would be able to compare different annotations, but when I tried to sort via category, no text came up, rendering that useless. 

- For some contracts the annotation doesn't appear at all in the text column. Eg. http://rc-site-demo.elasticbeanstalk.com/rc/public/contract/ocds-591adf-PH6493643447RC

- A couple of suggestions for resolving the above: 
------ We could delete one or more of the Country/ Year / Resource columns. There may be good reasons for keeping them, e.g. sorting by country/ resource/ year, although at the moment it looks like you can't do that?  
------ We could make those columns and the Category column much narrower to give more space to the Text column. 

- I think if this issue could be addressed, Clipping should be helpful for some users. 

 

Downloading

- When I download, the CSV name is spelled wrong "clipp" instead of "clip" - and probably to make more descriptive anyway.

- When I download, it gives you everything you've clipped, rather than just the subselection you're looking at (like if you've chosen 1-2 categories) - not sure if this is an issue, but maybe?

- When I download a clip, each line of the annotation is in a different cell, and the headings in Row 1 therefore don't correspond to the entries in row 2 (see screenshot).
![screen shot 2016-05-05 at 1 16 39 pm](https://cloud.githubusercontent.com/assets/12913915/15057495/0c71e6fc-12e5-11e6-88e0-d1756f1e29c3.png)

- I had RC open in different tabs, same browser, and tried to clip in all of them, and it seems like they sometimes joined together and sometimes not (would have assumed they would always accumulate, as when you're online shopping and can add things to cart from different tabs)

- The link in the csv goes to the contract, but not to the annotation page in question. Suggest changing it so that either (i) the link goes to the specific annotation or (ii) there are two link columns: one that goes to the contract's first page and one that goes to the annotation.

 

Printing

- the printing function seems pretty useless -- see attached doc which is a saved version of what the print would look like.

- The print functionality should default to landscape and the columns / display need to be drastically altered so that the space is used efficiently.

- The printed page also needs to have a smaller font (recommend 11 Times New Roman) and there needs to be either hard lines to separate each row and column or sufficient white space between each row.

- The printed document could be improved -- again, the text column is very narrow, and this isn't improved when you try to print in landscape format (see PDF). 

 
[Clipped Annotations.pdf](https://github.com/NRGI/resourcecontracts.org/files/251219/Clipped.Annotations.pdf)

**Comment by jedm** [comment]
Suggest we pause this until we have a fuller summary of Clippings in a document from YI. 

@anderspeders

**Comment by hello-deepak** [comment]
Please review clipping on demo [site](http://rc-site-demo.elasticbeanstalk.com/rc/public) .

**Comment by hello-deepak** [comment]
Please use #893 issue for any further discussion.
