### ISSUE TITLE
Refined search language

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#892]
Would it be possible to enable basic scripts for specific searches - for example *not* include X country.

Another example could be words located in proximity of each other using ~

**Comment by hello-deepak** [comment]
Search support different special character for better filtering of results.

* +   signifies AND operation
* |    signifies OR operation
* -    negates a single token
* "    wraps a number of tokens to signify a phrase for searching
* *    at the end of a term signifies a prefix query
* (    and ) signify precedence
* ~N after a word signifies edit distance (fuzziness)
* ~N after a phrase signifies slop amount

Eg.
> search word "stabilisation" not in country Guinea.

Use - to negate country name.

![notin](https://cloud.githubusercontent.com/assets/7577697/15528421/902fece0-2263-11e6-8b38-2c61a4d914fd.png)

> Similarly ~N can be used after a word or phrase. N signifies the fuzziness(distance).

 ie.  stabilisation~3

**Comment by hello-deepak** [comment]
@anderspeders Please review and provide feedback.

**Comment by hello-deepak** [comment]
I think we can close this. Please open if you find any issue.

**Comment by SamCCSI** [comment]
@hello-deepak thanks for this. I will add something to the FAQ. 

@hello-deepak/ @anderspeders Could you help me to understand what the following mean? I'm not quite sure from the description. Thanks.

- ( and ) signify precedence
- ~N after a word signifies edit distance (fuzziness)
- ~N after a phrase signifies slop amount

**Comment by SamCCSI** [comment]
@hello-deepak can I have some feedback on the above query? I am updating the FAQ to explain this functionality to users. Thanks!

**Comment by hello-deepak** [comment]
* (  )   signify precedence 

>ie. any phrase or term in ()  operator has higher precedence than other terms or phrase.
("Gas law"  +  "contracts") | regional
 -> Here "Gas law" and "contracts" have high precedence over "regional".

* ~N after a word signifies edit distance (fuzziness)
> When querying string fields , fuzziness is interpreted as the number of character changes that need to be made to one or more string to make it the same as another string .
ie. stabilisation~2
Here 2 is fuzziness.It searches for both "stabilisation", "stabilization" and other terms by interchanging max two character .
Please go through this [link](https://www.elastic.co/guide/en/elasticsearch/guide/current/fuzziness.html) for more information.


* ~N after a phrase signifies slop amount
>The slop parameter tells the query how far apart terms are allowed to be while still considering the document a match.
ie. "gas law"~2
Here 2 signifies slop which means how many times you need to move a term in order to make the query and document match . It search  in document containing "gas law" and other documents closer to "gas law" .
Please go through this [link](https://www.elastic.co/guide/en/elasticsearch/guide/current/slop.html) for more explanation.

@SamCCSI Does it make sense? Let me know if you have any confusion or questions.

**Comment by SamCCSI** [comment]
Very helpful, thanks. I will update the FAQs.
