### ISSUE TITLE
Fix mobile design as per new updates in the design

### ISSUE THREAD

**Issue by anjesh** [NRGI/resourcecontracts.org#896]
Please look into the issue for detailed comments here https://github.com/NRGI/resourcecontracts.org/issues/689#issuecomment-220130476

**Comment by jedm** [comment]
For Contract pages in mobile view:

- "Annotation" and "Metadata" icons (balloon and page-with-i) should not appear within toolbar with contract view buttons - too confusing.
- Orange button for switching between View and Summary pages is too big gif, breaks the page.

**Comment by hello-deepak** [comment]
Review mobile design . http://www.resourcecontracts.org/

**Comment by hello-deepak** [comment]
Please, create new issue if you find any bug.

**Comment by SamCCSI** [comment]
Tested by two separate people in the US while iPhones were connected to strong wifi signals, mobile phone functionality is not working ver well. Specifically:
1 - Is there now an anchor link to allow the user to skip straight to the PDF? I see a PDF button at the top but it is greyed out and doesn't work.

2 - The PDF view never loads. It just says "Loading..."

3 - The text view of the contract never loads. It just says "Loading..."

cc @charlesyoung

**Comment by manishgs** [comment]
@SamCCSI 
There was an issue with fetching data in safari which has been fixed.

**Comment by SamCCSI** [comment]
For 2 and 3 - @manishgs working for me now, thanks. cc @KaitlinCCSI @JesseCCSI any issues?

For 1 - my understanding is that there is supposed to be a link at the top, so that the user can skip the annotations and go straight to the contract file. I don't see any link. @jedm @JesseCCSI Is my understanding correct? If so, @manishgs can you please let us know if this is still on YI's to do list?

**Comment by KaitlinCCSI** [comment]
Contracts load for me.

I also thought that the buttons at the top were supposed to allow you to skip to correct place on page (so that if you click on PDF icon, the page scrolls so you can see the contract). Seems like they don't work in that fashion. Is it possible to add such functionality if it doesn't yet exist? (Also, when I am looking at contract PDF on phone and then click annotation button in top bar, it switches to text view, which doesn't seem correct.)

**Comment by manishgs** [comment]
@SamCCSI  @KaitlinCCSI 

For 1  - We've updated mobile view design. Please test on [staging](http://staging.resourcecontracts.org/contract/ocds-591adf-2500469277/view#/text) and let us know your feedback.

**Comment by SamCCSI** [comment]
Looking good @manishgs many thanks.

When looking at an annotation pop-up on the PDF view, the **_>>_** hyperlink back to the full annotation does not work.

Example:

![image](https://cloud.githubusercontent.com/assets/12913915/22208168/ec45b78e-e14f-11e6-993a-fa73694400bc.png)

**Comment by JesseCCSI** [comment]
Many thanks @manishgs - it looks like the clipping function may not be working on the mobile site - when I turn the clipping tool on and add individual annotations (or "clip all") they don't appear on the View Clips page, and the number of clippings displayed in the View Clips icon remains at 0. 

(am using iOS 10.2)

**Comment by SamCCSI** [comment]
More feedback: Can we please make the PDF view (not the text view) the default? This is consistent with how the main site functions.

**Comment by charlesyoung** [comment]
@SamCCSI, the PDF view is opened by default except on a slow connection where the text view will be opened.

**Comment by charlesyoung** [comment]
@anjesh I noticed that when clicking on the article link it opens more of the annotation text captured. Should it not open the tag on the actual doc?

**Comment by charlesyoung** [comment]
@anjesh you have time to look at this, I want to close all non S19 ASAP.

**Comment by manishgs** [comment]
@SamCCSI @charlesyoung Please test the contract view page in mobile.
@JesseCCSI clipping issue will be addressed in issue #996

**Comment by SamCCSI** [comment]
Hyperlink working nicely, and I can toggle back and forth between an annotation and where it appears on the PDF.

Will it be difficult to allow the user to zoom in and out of the PDF document using two fingers on their phone screen (the way most image zooms work on smart phones)? I ask because right now, the screen can only fit half the width of a contract on the default view:

![image](https://cloud.githubusercontent.com/assets/12913915/22787891/d641de68-eeab-11e6-94a1-144fba868582.png)

**Comment by manishgs** [comment]
You can zoom pdf with phone's built-in zoom feature with two fingers. We have added fullscreen mode and enabled zoom button for pdf view. Could you please test this feature and let us know if this helpful to view pdf. It also works on mobile.
![screenshot-staging resourcecontracts org 2017-02-28 17-10-49](https://cloud.githubusercontent.com/assets/3942999/23403838/16703dbc-fdda-11e6-9470-d6930daa755b.png)

**Comment by SamCCSI** [comment]
Nice feature.

1. I have to click the button twice to enter fullscreen mode, and twice to exit it. Makes sense for entering fullscreenmode, as you have that hover that explains what the button does, but for exiting it should just be one click.

2. It would be great to zoom out more than the system currently allows me (e.g. to 50%), so that I can see the full contract on the screen, without having to scroll to the right. Currently doesn't let me do that.

3. Annotations check box should be a square, not a rectangle:

![image](https://cloud.githubusercontent.com/assets/12913915/23406791/c7330eb4-fd8e-11e6-88c5-7de264bd9e9f.png)

4. in the search results view, can we make the left column much narrower, and the right column wider so that contract names don't take up so many lines? Right now you only see one contract in the screen when you have a list of search results, which is a very inefficient use of space:

![image](https://cloud.githubusercontent.com/assets/12913915/23406841/0071e63c-fd8f-11e6-95ae-120c84bf7169.png)

**Comment by manishgs** [comment]
1. We have removed the tooltip for mobile UI now user can go to full screen and exit on one tap. 
2. If you zoom out to max which is 50% you can see the full pdf on the view you don't have to scroll. 
3. Fixed.
4. Fixed.

@SamCCSI Let me know if we can deploy on production.

**Comment by SamCCSI** [comment]
1. Thanks, works well.

2. It won't let me zoom out to 50%. See screenshots: 
This is how far I can zoom out:
![image](https://cloud.githubusercontent.com/assets/12913915/23553214/e3e314da-ffed-11e6-886d-c9516d5272a2.png)

This is how far I might want to zoom out to see the whole page:
![image](https://cloud.githubusercontent.com/assets/12913915/23553233/f0099d74-ffed-11e6-82db-bd2148fe3e34.png)

3. Thanks.

4. I still think that the search results could show more contracts on the screen. @jedm would you be able to offer your view on this? Right now there is a lot of negative space. I think we can make the left column more narrower, still. Here is how it currently appears with the latest changes -- you still only get 1.3 contract listings on the screen at once. Are there any metadata rows that we can remove – e.g. Date? Others?

![image](https://cloud.githubusercontent.com/assets/12913915/23553308/3cc70480-ffee-11e6-812d-335c6ae4e544.png)

**Comment by manishgs** [comment]
Tested on both chrome and safari in iPhone 4, 6. It is working for me. 
Could you please test again zooming out to 25%?

![17391982_10210662498972885_838693122_n](https://cloud.githubusercontent.com/assets/3942999/24132779/11d21234-0e20-11e7-9d4e-f7b25a66d698.jpg)

Nexus 5
![0-02-06-71f525bf0e2f85209632cd4ffc0008e59ce0b0066dbb374c2f639df61c519edf_full](https://cloud.githubusercontent.com/assets/3942999/24132967/82913d78-0e21-11e7-8d93-c603fb6277e8.jpg)

Samsung galaxy s4
![screenshot_2017-03-21-10-29-59](https://cloud.githubusercontent.com/assets/3942999/24132982/99872c5e-0e21-11e7-9f51-f3b150cb2869.png)

**Comment by SamCCSI** [comment]
Finger zooming does not zoom the PDF: it zooms the whole page, which isn't helpful. Makes it look like this:
![image](https://cloud.githubusercontent.com/assets/12913915/24213248/2e0f4a14-0f08-11e7-9e41-eef2d6468a18.png)

We need it so that finger zooming on the PDF only affects the zoom of the PDF display rather than the whole webpage.

**Comment by charlesyoung** [comment]
@SamCCSI can we move additional requirements, besides any critical items, to a new ticket because all S19 tickets have to be done by next Friday to align with the closing of this dev budget cycle.

**Comment by charlesyoung** [comment]
Closing this ticket but will create a new ticket for additional mobile issues.

**Comment by charlesyoung** [comment]
Link to 'Mobile design #1061'
