### ISSUE TITLE
Appearance of associated documents on search page

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#901]
As a user, I might want to do a general search that reveals search results that include both contracts and associated documents.

We need to sort out/finalize how associated documents appear on the search results page. E.g. will they appear on the search page with contracts, but be differentiated somehow - eg by a dividing line or icon?

**Comment by jedm** [comment]
Instead of adding more dividers or icons in the results, I suggest a checkbox in the Search/Filters above to narrow to "Government contracts" or something like that.

So, as with #891, the user could narrow using those controls:

![search_narrow](https://cloud.githubusercontent.com/assets/2153664/15695965/ff7ba9fc-2760-11e6-821e-030d1a7e9c04.jpg)

**Comment by KaitlinCCSI** [comment]
We already have a dropdown box for "Document Type" that allows user to select only contracts (see screenshot), so the proposed checkbox for contracts isn't necessary. The main question, I think, is how the search results are organized -- (1) does the site give priority to contracts over other documents, so that the contracts are by default provided at the top of the results list and non-contracts at the bottom and/or (2) do we need to clearly distinguish in search results when something is a contract or not? 

For (1), it makes sense to me that if the site is meant to be primarily for contracts, that search results would either (a) default to contracts at top of the list to help users find contracts more easily or (b) default to a results list that groups contracts and associated docs together. For example, if our search results include Contracts A and B and associated documents A1, A2, B1, B2, then they could by default appear as (a) A, B, A1, A2, B1, B2 or as (b) A, A1, A2, B, B1, B2. But perhaps neither of these proposals make sense from a search perspective.

For (2), it may be more important to distinguish contracts somehow if the search results don't somehow prioritize how different documents are ordered in the list. (Also, what appears under "Contract Type" in the far right column? Associated Document?)

![screen shot 2016-05-31 at 9 08 27 pm](https://cloud.githubusercontent.com/assets/14825437/15696206/df908e10-2773-11e6-9d09-c816e6150f45.png)

**Comment by jedm** [comment]
Kaitlin - To me, it is still preferable not to add additional visual
elements or sort options to the results list. I suggest putting the
checkbox above, so that it is visible there even if people don't use the
dropdowns. What do others think? 

On 2016-05-31 19:15, KaitlinCCSI wrote: 

> We already have a dropdown box for "Document Type" that allows user to select only contracts (see screenshot), so the proposed checkbox for contracts isn't necessary. The main question, I think, is how the search results are organized -- (1) does the site give priority to contracts over other documents, so that the contracts are by default provided at the top of the results list and non-contracts at the bottom and/or (2) do we need to clearly distinguish in search results when something is a contract or not? 
> 
> For (1), it makes sense to me that if the site is meant to be primarily for contracts, that search results would either (a) default to contracts at top of the list to help users find contracts more easily or (b) default to a results list that groups contracts and associated docs together. For example, if our search results include Contracts A and B and associated documents A1, A2, B1, B2, then they could by default appear as (a) A, B, A1, A2, B1, B2 or as (b) A, A1, A2, B, B1, B2. But perhaps neither of these proposals make sense from a search perspective. 
> 
> For (2), it may be more important to distinguish contracts somehow if the search results don't somehow prioritize how different documents are ordered in the list. (Also, what appears under "Contract Type" in the far right column? Associated Document?) 
> 
> [1] 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/14825437/15696206/df908e10-2773-11e6-9d09-c816e6150f45.png
[2]
https://github.com/NRGI/resourcecontracts.org/issues/901#issuecomment-222874611
[3]
https://github.com/notifications/unsubscribe/ACDcwD7_ieK0nO9ehJKDqIntzvGkEOwbks5qHOsvgaJpZM4Iq1Ie

**Comment by upasna01** [comment]
We did add checkbox to search annotated contract, Please verify and do suggest changes required.
Please do verify.

http://www.resourcecontracts.org/search?q=&resource%5B%5D=Base+metals&annotated=1

![901](https://cloud.githubusercontent.com/assets/11477899/16478176/f8316466-3eb7-11e6-866b-43bd0bfa4d28.png)

**Comment by hello-deepak** [comment]
Annotated checkbox has been added to search annotated contrats . Please create new issue if you find any.
