### ISSUE TITLE
Save annotation

### ISSUE THREAD

**Issue by magnaibayar** [NRGI/resourcecontracts.org#911]
Hello?
I'm trying to make the application to production mode. And I'm using Apache server and access my site by my-project/public url, annotation is not saving problem. "Sorry we could not connect to the annotations store"

But when use php artisan serve command, and browse localhost:8000, annotation is saved. Without any problem.

Is there any difference?

**Comment by manishgs** [comment]
I have not  run the project with direct url like you are accessing  (http://localhost/my-project/public).
Regarding annotation is not saving. i think its due to annotation store api endpoint.

In file "project-path/public/scripts/contract.view.custom/annotation/rc.annotator.js" find the prefix of store api.
`prefix: '/api',`

In your case update prefix to `'/my-project/public/api'`

@magnaibayar  Let me know if you encounter any issues.

**Comment by magnaibayar** [comment]
It worked, Thank you very much!
