### ISSUE TITLE
Mechanical Turk Improvements

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#930]
- [ ] #795 Currently HIT auto reset time is after 20 days. It should be after HIT expiry date (i.e 10 days).
- [ ] #275 Setup SSL certificate of Mechanical Turk HIT page @anderspeders

**Comment by manishgs** [comment]
Mturk Task form requires https so we have hosted MTurk task form on free openshift server.
If we host the form on RC then we need ssl certificate on RC server. 

@charlesyoung @anderspeders 
Could you please setup ssl certificate on RC?

**Comment by anjesh** [comment]
SSL certificate is setup in shadow production and the transcription page is now served using https in the shadow production server. Once we setup the production, we will be serving the ssl enabled page in Mturk. We can close this for now. As for the HIT expiry page, it doesn't seem to be problem for now.

**Comment by SamCCSI** [comment]
http://admin.resourcecontracts.org/mturk/2524

Page 11 has been pending for a long time. I tried to reset it and got this error message.

![image](https://user-images.githubusercontent.com/12913915/27332563-45cf88d4-5590-11e7-8fff-581c961aeba8.png)

Could you please reset it so that it can be transcribed? all of the other 71 pages have already been processed.

**Comment by charlesyoung** [comment]
@SamCCSI I had the same issue recently and had to ask @manishgs to recreated the HIT.
