### ISSUE TITLE
contract not loading?

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#946]
Clicking on the first contract under this search leads to a 404 page: http://www.resourcecontracts.org/search?q=DRC%2C+CRG%2C+SC%2C+Huayou+-+JVA+Amend+3%2C+2009

**Comment by manishgs** [comment]
@SamCCSI 

These two contracts are main contract of each-other so contract was not found due to wrong OCID. Now fix the issue by updating main contract.
- DRC, CRG, SC, Huayou - JVA Amend 3, 2009 (associated document)
- DRC, Gécamines, Simco, CRG, CRRD, SC, SH, CMG, Huayou, [Sicomines] - JVA Amend 2, 2008 (main contract)


These two contracts are also main contract of each other so please update.
http://admin.resourcecontracts.org/contract/1339
http://admin.resourcecontracts.org/contract/1338

Then update main document of below contract
http://admin.resourcecontracts.org/contract/765


Also Please update associated document of following contracts.
http://admin.resourcecontracts.org/contract/1210
http://admin.resourcecontracts.org/contract/1209
http://admin.resourcecontracts.org/contract/116

**Comment by SamCCSI** [comment]
Thanks @manishgs for identifying the problem! I have now made those changes.

FYI, it is really confusing to figure out how to make these changes because once associated, the Yes or No button is greyed out.

Example:
![image](https://cloud.githubusercontent.com/assets/12913915/17480243/f79c1284-5d44-11e6-845e-efffa7badc0a.png)

I had to experiment with associating one associated contract with another (unrelated) contract so that the greyed out buttons would disappear, so that I could eventually change which contract was the main. But it's done now.

Thanks,
Sam
