### ISSUE TITLE
Localisation of metadata (backend)

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#962]
There has been discussion about the need of localisation of the backend metadata including annotations. Currently localisation is targeted to interface only, however the free text fields like title, company name, concession/licence name take only value. These fields should also accept values in different languages. The feature will impact the entire stack of systems - from backend system, api, frontend and database - and needs to be handled very carefully. 

The following tasks are identified (subjected to change later)
- [ ] Impact assessment of the feature
- [ ] Document the change required in different components (backend, database, api, frontend) to implement this feature
- [ ] Updates in backend/database
- [ ] Updates in API
- [ ] Updates in Frontend
- [ ] Data migration - there might be a need of existing data migrated to new structure
- [ ] Testing and deployment

**Comment by manishgs** [comment]
Our suggestions on localization of metadata:

**1. English will be default language**
It is mandatory for all contracts to have metadata in English whereas metadata in other languages is optional. If a user switches the language  of RC site to other than the English (eg. FR) and if metadata in that language (eg. FR) has not been added for any contract then the contract will be displayed in English by default.

**2. Count of contracts calculated using English Metadata only** 
The uploaded contracts may or may not have metadata in languages other than English. Since English metadata is mandatory, the count of the contracts will be calculated using English metadata only. 


**3. Indexing in English in case of missing other language metadata**
If English metadata is not translated in other languages, the English metadata will be indexed in elastic search database. 


**4. Listing of contracts**
In case the language of RC site is switched to language other than english. For e.g. in Arabic. So, the list of contracts will also consists of contracts in english which are not translated to Arabic. 

**5. Searching contracts**
Suppose the RC site's language is switched to Arabic. When a user searches contracts using Arabic language, contracts translated only in Arabic language will be listed in search result. However, the user can search contracts using English language but contracts not translated in Arabic language will only be listed. 

**6. PDF text search**
Suppose the RC site's language is switched to Arabic. The metadata of a contract is also translated in Arabic. However, if the contract pdf is in English. The text search in the contract will only be possible in English. 

@charlesyoung  @SamCCSI 

Let us know your thoughts.

**Comment by SamCCSI** [comment]
I think we need to automatically have the contract name in each language.

For this, we need to have the document type and contract type metadata fields in the correct language before the contract name is generated. 

We can have a list of all document types / contract types / resources /  countries / disclosure modes in the different languages so that these can automatically change for each contract when the user switches languages. The date can automatically change too. I think this is preferable to us choosing to 'translate' an individual contract, which is not really scalable.

**Comment by manishgs** [comment]
@SamCCSI 
> I think we need to automatically have the contract name in each language.

Yes we'll keep "Generate contract name" button in the contract form so that uploader can automatically generate contract name in each language.

Menu : **utility->Generate contract** 
we'll add new dropdown "language" so that use can update contract name in each language.

Uploader doesn't need to translate all the metadata fields. Following are the fields that need to be translated. Other fields will be translate from codelist.

1. Contract Name
2. Company 
	- Company Name 
	- Registration Agency
	- Company Address
	- Company Number
3. Project Name
4. Project Identifier

5. Concession / License Name
6. Concession / License Identifier

7. Disclosure Mode Text
8. Note

**Comment by manishgs** [comment]
@charlesyoung @SamCCSI 

Initial work is deployed in demo. Please test the feature and let us know your feedback.

**Comment by charlesyoung** [comment]
@SamCCSI have you managed to test this feature?

**Comment by manishgs** [comment]
I attached some screenshot in ordder to help for testing localization feature.

Demo url : http://resourcecontracts-demo1.elasticbeanstalk.com/contract/62

**Add or view translation** 
![screenshot-resourcecontracts-demo1 elasticbeanstalk com 2016-11-22 16-00-26](https://cloud.githubusercontent.com/assets/3942999/20519912/f1a724c8-b0cc-11e6-98c9-36c42e171048.png)

**Edit translation**
Disabled fields are not required to translate. 
![screenshot-resourcecontracts-demo1 elasticbeanstalk com 2016-11-22 16-02-50](https://cloud.githubusercontent.com/assets/3942999/20520015/4f745e7c-b0cd-11e6-83c7-5dc1424548ee.png)

**Add/Edit Translation from contract listing page**
![screenshot-resourcecontracts-demo1 elasticbeanstalk com 2016-11-22 16-04-29](https://cloud.githubusercontent.com/assets/3942999/20520072/77f843ea-b0cd-11e6-9c5a-d1bb9730f16a.png)

After Adding/Editing Translation now publish the metadata and verify on Subsite (It will take more than 5 min to reflect on Frontend as we have implemented cache for 5 min).

**Comment by SamCCSI** [comment]
@manishgs This is looking good but there are some issues with the French terms you use.

E.g. this: 
![image](https://cloud.githubusercontent.com/assets/12913915/20520746/6fe5a802-b0a8-11e6-921f-f953faad266a.png)

The contract type is PSA in English, but:

1.
When I generate contract name in French it becomes "**codelist/contract_type.PSA**" instead the contract type in the title should just be the French translation of PSA – "**Contrat de Partage de Production**"

So, the title should read **OPIC Resource Corporation, Block 106, etc., Contrat de Partage de Production, 2009**

2.
The arabic version doesn't use arabic text when generating the title:

![image](https://cloud.githubusercontent.com/assets/12913915/20521055/b3516850-b0a9-11e6-9889-027605f33c54.png)

**Comment by manishgs** [comment]
1. fixed -  auto generate contract name
2. You need add Arabic text in company name, License Name etc before generating contract name
 Check this link for arabic contract name
 http://resourcecontracts-demo1.elasticbeanstalk.com/contract/1821

**Comment by charlesyoung** [comment]
@SamCCSI  you happy with above?

**Comment by SamCCSI** [comment]
Thanks, it looks like this is working now. We will just need to ensure that all our translated terms are complete.

**Comment by manishgs** [comment]
@charlesyoung @SamCCSI 

If you are happy with current metadata translation workflow then can we continue work for annotation translation?

**Comment by charlesyoung** [comment]
@SamCCSI happy to proceed?

**Comment by SamCCSI** [comment]
Yes, thanks.

**Comment by charlesyoung** [comment]
@manishgs please continue work for annotation translations.

**Comment by anjesh** [comment]
Thanks @charlesyoung we will continue annotation localisation in separate issue https://github.com/NRGI/resourcecontracts.org/issues/1015 as the process is slightly different from metadata annotation. 

We are planning to deploy metadata annotation this sprint (probably this week), we will fix some minor admin UI, and the system will require full re-indexing for metadata localisation to work. 

cc @SamCCSI

**Comment by SamCCSI** [comment]
@anjesh is it easy to make arabic version of site available for OLC, but disabled for now? So that we can then enable it when we are ready to deploy (with minimal work, if any, needed to be done by YI at that stage)? I ask because we need to do more scoping before deciding whether or not an Arabic site makes sense for OLC.

**Comment by charlesyoung** [comment]
@SamCCSI can we deploy the metadata translation workflow to production?

**Comment by SamCCSI** [comment]
@charlesyoung Yes, thanks.

**Comment by charlesyoung** [comment]
Thanks @SamCCS

@anjesh please deploy on production.

**Comment by SamCCSI** [comment]
@anjesh @charlesyoung I am just repeating the below question so that it does not get overlooked:

Is it easy to make arabic version of site available for OLC, but disabled for now? So that we can then enable it when we are ready to deploy (with minimal work, if any, needed to be done by YI at that stage)? I ask because we need to do more scoping before deciding whether or not an Arabic site makes sense for OLC.

**Comment by manishgs** [comment]
@charlesyoung  @SamCCSI 
Metadata localization deployed on production.  Please review once.

**Comment by charlesyoung** [comment]
@SamCCSI can you not use the demo sites (which has English, French and Arabic) for your scoping? 

[OLC](http://rc-site-demo.elasticbeanstalk.com/olc/public/) demo site
[RC](http://rc-site-demo.elasticbeanstalk.com/rc/public/) demo site

**Comment by SamCCSI** [comment]
@charlesyoung yes, we have been using the demo sites. My question is whether it would take much time / effort to hold off on deploying the Arabic on the OLC live site for, say, six months, as opposed to just having it deployed along with RC during this sprint? Does deploying it later incur addition costs?

**Comment by charlesyoung** [comment]
No additional costs will be incurred.

**Comment by anjesh** [comment]
Deployed in live.
