### ISSUE TITLE
Stabilizing annotation category search links

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#968]
A few months ago I searched for a specific type of annotation category and saved the search link with results (http://www.openlandcontracts.org/search?q=&annotation_category%5B%5D=Location%2F%2FEmplacement), which was then shared in a report. Now this link shows zero results, while a new search of the same term shows 125 contracts (http://www.openlandcontracts.org/search?annotation_category%5B%5D=Location). It looks like this happened because the French version of the annotation field name is no longer included along with the English, and thus no longer in the URL. I assume there is no good way of ensuring that any older URLs re-route to the newer ones, but I wanted to flag in case there is any easy way to do this? (Also, I don't remember anyone making a decision to remove the French from the annotation categories?)

**Comment by anjesh** [comment]
@KaitlinCCSI these links got updated when we developed the localisation feature because french labels will appear under fr locale once we enable the [localisation](https://github.com/NRGI/resourcecontracts.org/issues/1004). If these reports (with links) are widely circulated and very important, we will find a mechanism that will enable these links - hack to the existing links like we did for the OCIDs. I apologise for the confusion.
