### ISSUE TITLE
Changes to annotations on back-end not auto-saving

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#969]
A researcher made extensive edits to another person's annotations and these did not save. He checke this by reviewing the backend. (Not clear if (i) the changes are not being saved or (ii) the changes are being saved, but aren't showing on the back-end right away.

This has happened multiple times in the last two weeks and risks wasting time spent to go back and re-enter the changes.

Could you please investigate what might be causing this?

**Comment by SamCCSI** [comment]
Here are two examples where these problems were encountered: http://www.resourcecontracts.org/contract/ocds-591adf-PK4298834549RC/view#/text
http://resourcecontracts.elasticbeanstalk.com/contract/2136

**Comment by manishgs** [comment]
Could please explain where did you update the annotations? view page or on summary page?

Wherever user create/delete/update the annotation, notification will show up on the top. Are you seeing this notification?

![screenshot-resourcecontracts elasticbeanstalk com 2016-10-20 11-18-29](https://cloud.githubusercontent.com/assets/3942999/19547390/575b72d6-96b7-11e6-81e5-e593d826db96.png)
 
If would be great if you explain the steps how you edit the annotations so that we can investigate in detail.

**Comment by SamCCSI** [comment]
Contract view page.

From the researcher whose changes were lost: "the annotation i created
would also appear on the screen. Then I would go to the next page and come
back and it would be gone. "

**Comment by samitalalchan** [comment]
We tried it multiple times, but its working fine. If you still find a problem, please open this issue and inform us in detail with images if possible about the problem you are facing.
