### ISSUE TITLE
Enable clipping in Advance search Page

### ISSUE THREAD

**Issue by hello-deepak** [NRGI/resourcecontracts.org#980]
- [ ] clipping annotation in search result from advance search .
- [ ]  Enable all clipping in search result .

**Comment by manishgs** [comment]
This issue will be addressed in #996

**Comment by jedm** [comment]
@kaitlinccsi @anderspeders Hello. Before I add last suggestions on clippings for search results I am tracking the origin of this request. My recollection is that clipping was removed from all pages unrelated to annotations to avoid complications in UX and clarity of use cases. Do you or @manishgs @Anjesh recall how request resurfaced?

**Comment by jedm** [comment]
See also comment here: https://github.com/NRGI/resourcecontracts.org/issues/893#issuecomment-223736128 Clippings was NOT planned for non-Contract pages as of June 2016. Did we reverse this request? And if so when?

**Comment by manishgs** [comment]
@jedm 
Yes, Clipping was not planned to add clip button on search result during initial phase. We've issue #1022 to add clip button on search result so we've addressed this feature on #996 clipping improvement issue.

**Comment by jedm** [comment]
Thank you @manishgs. My question was about how and why the requirement was brought back after we decided not to have it. 

Separate question: if we do have this feature, what does it do when you clip a contract instead of an individual Annotation? 

@anderspeders @kaitlinccsi if you can provide any context on origin of latest request that may help us clarify.
