### ISSUE TITLE
Both OLC and RC sites down 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#989]
Hi all - both OLC and RC global sites are down this morning (I have not checked country sites), with "temporarily unavailable" messages appearing (screenshots below). 

![image](https://cloud.githubusercontent.com/assets/14910764/19599267/fa51a7ba-976d-11e6-8711-475209ec829c.png)

![image](https://cloud.githubusercontent.com/assets/14910764/19599258/f15734d6-976d-11e6-8c4b-5f56a28fde45.png)

**Comment by manishgs** [comment]
There were issue "errors resolving the DNS hostnames" on amazon server. During auto-scaling on API server, the server failed to build application because server could not resolve github.com (while installing composer packages) hence API server was down during 5:24 AM PDT to 6:36 AM PDT.

![screenshot-status aws amazon com 2016-10-21 20-37-25](https://cloud.githubusercontent.com/assets/3942999/19602923/cf47f6bc-97ce-11e6-9209-7eabec21bac7.png)

**Comment by JesseCCSI** [comment]
Thanks @manishgs
