### ISSUE TITLE
Deleting annotations

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#990]
Someone added test annotations to this [contract](http://resourcecontracts.elasticbeanstalk.com/contract/1897).  

I deleted the annotations form the backend but it still shows on the public [site](http://www.resourcecontracts.org/contract/ocds-591adf-TN3265676379RC-1897/view#/pdf).

**Comment by manishgs** [comment]
When user delete an annotation, annotation can not be publish/unpublish so need to address this issue on current workflow.

I used following steps to unpublished the annotation.
1. create new annotation so that annotation status change to draft
2. complete and then publish annotation 
3. unpublish and then reject annotation
4. delete annotation

**Comment by SamCCSI** [comment]
@manishgs can we build in a more simple way for this, in the long term?

It would seem more useful to have a 'publish' or 'unpublish' button, rather than having to undertake four different steps.

**Comment by manishgs** [comment]
@SamCCSI 
We don't need to following  these four steps if we add publish/unpublish button whenever annotation deleted.

I have mention these steps for quick workaround until we fix the issue.

**Comment by SamCCSI** [comment]
Thanks very much @manishgs

**Comment by charlesyoung** [comment]
Thanks @manishgs. This is something we need to address but not during S18. I've moved this ticket to an unscheduled milestone to be discussed and implemented later.

**Comment by manishgs** [comment]
fixed and deployed.
