### ISSUE TITLE
Clipping Improvements

### ISSUE THREAD

**Issue by manishgs** [NRGI/resourcecontracts.org#996]
Continue from issue #893 

- [x]  Please check functionality of "Clip All" tool by: 
1) clipping All Annotations in a contract 
2) deselecting a single Annotation 
3) toggling Clip All on and off again - This sequence does not work for me and I needed to refresh to re-enable Clip All function

- [x]  recommend we add the CSV file to the Zip file. please confirm this is possible

- [ ]  I tried downloading the CSV and the columns in CSV did not correspond to the columns in the All Clips page,
for a few months there has been discussion of NRGI providing an updated sample CSV file - what is the status of this? See: #552 (comment)

- [x] we requested to make the Annotation Category bold/hotlinked instead of the Document Title, but if we have now decided to link to FIRST PAGE of document, we should REVERT back to Search standard where bold/hotlinked text is the Document Title again. Using Annot. Category as hotlink only makes sense if user can go to corresponding Annotation (see '4' in attached image)

#980 **Enable clipping in Advance search Page**
- [x] clipping annotation in search result from advance search .
- [x]  Enable all clipping in search result .

[#896](https://github.com/NRGI/resourcecontracts.org/issues/896#issuecomment-274526138) **Clipping not working on mobile** 
- [x]  it looks like the clipping function may not be working on the mobile site - when I turn the clipping tool on and add individual annotations (or "clip all") they don't appear on the View Clips page, and the number of clippings displayed in the View Clips icon remains at 0.

**Comment by charlesyoung** [comment]
Provide xls download rather than csv to retain the language formatting. 

![image](https://cloud.githubusercontent.com/assets/13888372/20177944/fa8fc410-a757-11e6-971f-da6b5371933f.png)

**Comment by anjesh** [comment]
Need to have the option to delete individual clips from "All clips" page, instead of only "Clear all clips".

**Comment by charlesyoung** [comment]
Include a details (warning / documentation) on the browser version.

**Comment by SamCCSI** [comment]
1. 'Ordering' arrows don't work on All clips page.
![image](https://cloud.githubusercontent.com/assets/12913915/22352025/70ac5830-e3e8-11e6-80b6-b00c9bd60532.png)

- category arrow does not order by category – it always separates by contract so that if you select two annotation categories and two contracts, it wont let you see 'arbitration' annotations for each contract followed by 'Audit' annotations for each contracts.

- Document arrow does nothing. 

- Text arrow does nothing and probably shouldn't be visible / operational anyway @jedm ?

- Country arrow does nothing

- Year arrow does nothing

- Resource arrow does nothing

- View arrow does nothing and probably shouldn't be visible / operational anyway @jedm ?

**Comment by charlesyoung** [comment]
@anjesh what is the status of this ticket?

**Comment by manishgs** [comment]
@SamCCSI  @charlesyoung 
Please check the clipping improvements on [staging](http://staging.resourcecontracts.org/search?q=&annotated=1)

**Comment by SamCCSI** [comment]
@manishgs @charlesyoung all ordering arrows working well, thanks.

**Comment by charlesyoung** [comment]
Thanks @SamCCSI 

@manishgs how much of the 'continue from issue #893' (top of the ticket) items have been addressed?

**Comment by manishgs** [comment]
@charlesyoung 

Most of issues are fixed. We are testing on staging and planning to deploy on production by March 8.

 > I tried downloading the CSV and the columns in CSV did not correspond to the columns in the All Clips page, for a few months there has been discussion of NRGI providing an updated sample CSV file - what is the status of this? See: #552 (comment)

Could you please help us to provide sample csv file?

**Comment by JesseCCSI** [comment]
Just flagging that we are presenting OLC at a series of events during the week of March 20, so if all clipping improvements could be deployed/ tested by then, that would be great.

**Comment by manishgs** [comment]
@SamCCSI @jedm @JesseCCSI @charlesyoung 
Clipping bug fixes and improvements updated on live. Please review once and let us know your comment.

**Comment by jedm** [comment]
Please see my new comments here in Issue #22 (a nice low number - brings
back memories!):

https://github.com/NRGI/resourcecontracts.org/issues/22#issuecomment-285271870

**Comment by JesseCCSI** [comment]
Many thanks @manishgs I will add comments before Monday.

**Comment by JesseCCSI** [comment]
Thanks again @manishgs my comments as follows: 

1. In terms of clipping individual search results, I had imagined that a check box or clip icon would appear on the very left of the search result, allowing you to clip each individual search result. In its current position, the clip icon gets lost in the rest of the text. 

2. We also need a "clip all" option for search results, as many users will want to, for example, clip and compare all search results for a particular category. 

![image](https://cloud.githubusercontent.com/assets/14910764/23823183/eb694f68-0654-11e7-998f-c05b90f942f6.png)

3. I assume that the clip icon that appears beside the title of the contract and the clip that appears beside the annotation text are for two different things, i.e. the clip beside the title clips all annotations in that contract, while the clip beside the annotation just clips the annotation? To streamline and avoid confusing users, I would remove the option to clip all annotations in a particular contract from the search results page - would just give the option of clipping search results themselves. **Though happy to discuss best approach with rest of CCSI, NRGI, YI teams.** If we decide to keep both options, the difference between these options needs to be clearly communicated to users, e.g. through better distinction in hover or different placement of the icon for different options. 

4. On the View Clips page, when I click on the "View on Document" action, the window that pops up is helpful and looks good, but I was taken to a specific page that only contained some of the relevant articles for the annotation, and I could click on other page numbers to view other relevant articles. E.g. For Megabois, Contrat de Concession Forestière, 2011, I clicked on "View on document" for the arbitration and dispute resolution clipped annotation, and the following happened: 

![image](https://cloud.githubusercontent.com/assets/14910764/23823243/56814da4-0656-11e7-8508-d53e39632677.png)

5. On the "View Clips" page, the user should have the ability to select and delete a selection of clips at once, instead of just the option to either "clear all" or delete individually. (relates to @jedm 's point no. 7 re the "SELECT" column). We had previously suggested modifying the "SELECT" column as follows (in #893): It would be useful to have a button on the top of the far left column so you could uncheck all the boxes at once, or uncheck specific boxes — this would make it easier if you only want to print/save/download a small number of the ones you’ve clipped. The “uncheck” function is the same as the “Unselect All” function in Gmail – allows the user to re-select only the clips she wants. 

6. If you go to “View Clips”, sort your clips in a particular order (e.g. by Year or Country), then click on the page number hyperlink (under the “Text” column) to view a contract, and then go back (via web browser button or RC back button) the site forgets how you had previously sorted the clips. This is the case whether you use the browser's back button on the site's back button. (previous comment from #893). 

(cc @KaitlinCCSI @SamCCSI)

**Comment by manishgs** [comment]
3. yes, These icons have different actions, one for clipping all annotations of contract and another is for clipping specific annotation found from search.
@SamCCSI @jedm @KaitlinCCSI 
Let us know your thought to remove the option to clip all annotations in a particular contract from the search results page

**Comment by manishgs** [comment]
3. Yes, These icons have different actions, one for clipping all annotations of contract and another is for clipping specific annotation.

@SamCCSI @jedm @KaitlinCCSI 
Let us know your thought on removing the option to clip all annotations in a particular contract from the search results page

4. Yes, The popup only contains detail for selected annotation and pdf file so that user can quickly compare with other pdfs.  When user click on the article reference hyperlink it will take you to the current annotation page. If you are thinking it should open annotation pop like contract view page, then it will add good amount of time for us, There is option to view specific annotation position on the pdf when you click on the link from Text Column from the table.

**Comment by JesseCCSI** [comment]
Many thanks @manshigs. Defer to the rest of the teams on point 3 regarding the different actions. 

Re point no. 4: I think it makes sense for the popup to only contain detail for selected annotation and pdf files, but am just curious as to why page 9 appears in the popup (where arts. 25-30 are listed), rather than page 3 (where the first relevant article for the annotation - art. 7 - is listed) and page 9?
 Let me know if I'm missing something.

**Comment by manishgs** [comment]
@JesseCCSI 
Now showing all the article references of a annotation category. Could you please check in the [staging](http://staging.resourcecontracts.org/clip) 

![screenshot-localhost-8001 2017-03-15 17-32-32](https://cloud.githubusercontent.com/assets/3942999/23947283/2ee16d1c-09a6-11e7-871f-78ec3c27d729.png)

**Comment by JesseCCSI** [comment]
Thanks @manishgs looks like it's working well.

**Comment by JesseCCSI** [comment]
Just flagging re point no. 3 above on different actions that I think it's fine to keep both, so no need to amend for now. Thanks. (cc @manishgs)

**Comment by manishgs** [comment]
@JesseCCSI 
Please review point no. 5 and 6 on [staging](http://staging.resourcecontracts.org/clip)

**Comment by charlesyoung** [comment]
@JesseCCSI apologies as I realise that you are at a conference this week but could you look at this ticket when you have time because we have to close all tickets by next Friday due to the closing of the S19 development budget cycle. Thanks

**Comment by JesseCCSI** [comment]
Thanks @manshigs this is working nicely! 

cc @charlesyoung

**Comment by charlesyoung** [comment]
Thanks @JesseCCSI. Can we close this ticket? 

cc @jedm

**Comment by jedm** [comment]
For **All Clips** page, if @charlesyoung and @anjesh approve the restored Select box in the left column, then I recommend:
1) remove trash icon in right column
2) change header for right column back to "VIEW"

I recommend the rest of the ideas in items 2, 3 and 5 be put on hold until next sprint because discussion of connection between Search and Clips is not concluded among the group.

**Comment by JesseCCSI** [comment]
Many thanks @charlesyoung @jedm I'll send thoughts back on clipping this afternoon. If we can keep this ticket open for now, that would be helpful.

**Comment by charlesyoung** [comment]
@JesseCCSI just checking if you have any further input on this ticket.

**Comment by manishgs** [comment]
We've deployed following comments on production.

Point no. 4,5, 6 of @JesseCCSI 's comments.

> 1. remove trash icon in right column
> 2. change header for right column back to "VIEW"

[#22 comment](https://github.com/NRGI/resourcecontracts.org/issues/22#issuecomment-285271870)


Please open new ticket if you have any issue regarding clipping feature.

**Comment by JesseCCSI** [comment]
Sorry for delay - we have been discussing internally. I will send comments this morning. Re-opening for now.

**Comment by JesseCCSI** [comment]
Given offline discussions and due to need to close all tkts by tomorrow (March 31), we will postpone addressing the issue of clipping on the search results page until a later date and prioritize improvements at that time.  Points 1, 2, 3 in my comment above from March 11 can thus be discussed/ addressed at a later date. 

(cc @charlesyoung @jedm @KaitlinCCSI)

**Comment by charlesyoung** [comment]
Thanks @JesseCCSI 

Changing milestone to unscheduled but labeling as priority.

**Comment by KaitlinCCSI** [comment]
FYI clips doesn't always turn on for me. Just tried to turn it on from this page http://openlandcontracts.org/contract/ocds-591adf-5399370669/view#/pdf/page/66/annotation/6993 (which was accessed through link next to annotation on Advanced Search page) and turning it does nothing except making it blue -- there are no clip icons next to annotations. I can get the clip icons if I access the same contract in another way, so think there is a bug here.
![screen shot 2017-03-31 at 10 47 26 am](https://cloud.githubusercontent.com/assets/14825437/24558066/84647d50-15ff-11e7-9913-d775101b4932.png)
![screen shot 2017-03-31 at 10 46 35 am](https://cloud.githubusercontent.com/assets/14825437/24558067/8467c988-15ff-11e7-84e4-8626e0270ffe.png)
